export const supportCenterStrings = {
  eyebrow: "SUPPORT",
  title: "Support & Queries",
  subtitle: "Raise a ticket and track updates from the support team.",
  instituteSubtitle: "Raise a ticket with your institute admin and track its progress.",
  form: {
    title: "Raise a query",
    description: "Describe the issue clearly so the team can route it correctly.",
    instituteDescription: "Your institute admin receives this query first and can forward it to Super Admin when needed.",
    category: "Category",
    subject: "Subject",
    subjectPlaceholder: "Brief summary of the issue",
    message: "Details",
    messagePlaceholder: "What happened, what did you expect, and what have you already tried?",
    submit: "Submit Ticket",
    submitting: "Submitting...",
  },
  categories: {
    general: "General Query",
    account: "Account & Login",
    test_access: "Test Access",
    grading: "Grading & Results",
    technical: "Technical Issue",
    billing: "Billing & Subscription",
  },
  history: {
    title: "My tickets",
    description: "Tickets raised from this account.",
    emptyTitle: "No support tickets yet",
    emptyDescription: "New tickets will appear here after they are submitted.",
    loading: "Loading your tickets...",
    refresh: "Refresh",
    ticketNumber: (id: number) => `Ticket #${id}`,
  },
  status: {
    new: "New",
    open: "In Progress",
    resolved: "Resolved",
    closed: "Closed",
  },
  routing: {
    institute: "With Institute Admin",
    forwarded: "Forwarded to Super Admin",
    platform: "With Super Admin",
  },
  success: "Your support ticket has been submitted.",
  errors: {
    load: "Unable to load your support tickets.",
    submit: "Unable to submit the support ticket.",
  },
} as const;
