export const testsStrings = {
  title: "Test Builder",
  subtitle: "Assemble course question banks into timed IELTS assessments.",
  newTest: "New Test",
  searchPlaceholder: "Search tests...",
  courseAriaLabel: "Course",
  allCourses: "All courses",
  searchCoursesPlaceholder: "Search courses...",
  statusAriaLabel: "Status",
  allStatuses: "All statuses",
  statusLabels: {
    draft: "Draft",
    published: "Published",
    archived: "Archived",
  },
  myTests: "My tests",
  search: "Search",
  loading: "Loading...",
  empty: {
    title: "No tests found",
    description: "Create a test and add questions from one of its course banks.",
    cta: "Create Test",
  },
  noDescription: "No description added.",
  questions: "Questions",
  points: "Points",
  time: "Time",
  untimed: "Untimed",
  minutesSuffix: (minutes: number) => `${minutes} min`,
  courseByAuthor: (course: string, author: string) => `${course} · By ${author}`,
  typeLabels: {
    practice: "Practice",
    module_mock: "Module mock",
    full_mock: "Full mock",
    final: "Final test",
  },
  errors: {
    load: "Failed to load tests.",
  },
} as const;
