import { createBrowserRouter, Navigate } from "react-router-dom";
import { LandingLayout } from "../components/landing/LandingLayout";
import { Login } from "../pages/Login";
import {
  AboutUs,
  AccountForm,
  AttemptResult,
  AttemptResultDetails,
  ChangePassword,
  ContactUs,
  CouponForm,
  Coupons,
  Dashboard,
  DashboardLayout,
  DemoAccounts,
  DeveloperLayout,
  DeveloperPanel,
  DeveloperSettings,
  DirectStudentForm,
  GradingDetail,
  GradingOversight,
  GradingQueue,
  GstRates,
  Home,
  InstituteAnnouncements,
  InstituteBilling,
  InstituteBranding,
  InstituteAiQuota,
  InstituteDashboard,
  InstituteForm,
  InstituteInstructorLayout,
  InstituteLayout,
  InstituteMemberForm,
  InstituteMembers,
  InstituteProfile,
  InstituteSupportTickets,
  InstructorDashboard,
  InstructorForm,
  InstructorLayout,
  InstructorProfile,
  Institutes,
  Invoice,
  Logs,
  ModuleControl,
  ModuleControlDetail,
  ModuleEditor,
  Modules,
  MyCourses,
  NotificationsInbox,
  PaymentMethods,
  Payments,
  PlanForm,
  Plans,
  PlatformNotifications,
  Profile,
  ResetPassword,
  RevenueDashboard,
  Sessions,
  ShowcasePlans,
  StudentAnnouncements,
  StudentAttempts,
  StudentCourseCatalog,
  StudentDashboard,
  StudentLayout,
  StudentOverview,
  StudentProfile,
  StudentProgress,
  StudentPurchaseHistory,

  Subscriptions,
  SupportCenter,
  SupportTickets,
  SuperAdminBlogForm,
  SuperAdminBlogs,
  SuperAdminInstituteAccounts,
  SuperAdminInstituteStudents,
  SuperAdminInstructorForm,
  SuperAdminSEOSettings,
  SuperAdminStudentForm,
  SuperAdminStudentOverview,
  SuperAdminTestimonials,
  Terminal,
  TestRunner,
  TestingLoginSelector,
  TrialConfig,
  Users,
} from "./lazyPages";
import { ProtectedRoute } from "./ProtectedRoute";
import { MonetaryAnalyticsRoute } from "./MonetaryAnalyticsRoute";
import { BlogsList } from "../pages/public/BlogsList";
import { BlogDetail } from "../pages/public/BlogDetail";

const developerAccessSlug = import.meta.env.VITE_DEVELOPER_ACCESS_SLUG || "vh-control-9f4c2a";

export const router = createBrowserRouter([
  {
    element: <LandingLayout />,
    children: [
      { path: "/", element: <Home /> },
      { path: "/login", element: <Home /> },
      { path: "/register", element: <Home /> },
      { path: "/about", element: <AboutUs /> },
      { path: "/plans", element: <ShowcasePlans /> },
      { path: "/contact", element: <ContactUs /> },
      { path: "/blogs", element: <BlogsList /> },
      { path: "/blogs/:slug", element: <BlogDetail /> },
    ],
  },
  { path: "/testing-login", element: <TestingLoginSelector /> },
  { path: "/super-admin/login", element: <Login allowedRoles={["SUPER_ADMIN", "SA_INSTRUCTOR"]} title="Super Admin & Author Portal" subtitle="Sign in to platform management or assessment authoring" /> },
  { path: `/${developerAccessSlug}/login`, element: <Login allowedRoles={["DEVELOPER"]} title="Developer Control" subtitle="Verified developer access only" /> },
  { path: "/sa-instructor/login", element: <Navigate to="/super-admin/login?role=SA_INSTRUCTOR" replace /> },
  { path: "/super-admin", element: <Navigate to="/super-admin/login" replace /> },
  { path: "/super-admin/instructor", element: <Navigate to="/super-admin/instructor/dashboard" replace /> },
  { path: "/admin-login", element: <Navigate to="/super-admin/login" replace /> },
  { path: "/sa-instructor-login", element: <Navigate to="/super-admin/login?role=SA_INSTRUCTOR" replace /> },
  { path: "/instructor", element: <Navigate to="/super-admin/instructor/dashboard" replace /> },
  { path: "/instructor/*", element: <Navigate to="/super-admin/instructor/dashboard" replace /> },
  { path: "/reset-password", element: <ResetPassword /> },
  {
    element: <ProtectedRoute allowedRoles={["SUPER_ADMIN"]} />,
    children: [
      {
        path: "/super-admin",
        element: <DashboardLayout />,
        children: [
          { path: "dashboard", element: <Dashboard /> },
          { path: "testimonials", element: <SuperAdminTestimonials /> },
          { path: "blogs", element: <SuperAdminBlogs /> },
          { path: "blogs/new", element: <SuperAdminBlogForm /> },
          { path: "blogs/:id", element: <SuperAdminBlogForm /> },
          { path: "seo-settings", element: <SuperAdminSEOSettings /> },
          { path: "ai-settings", element: <Navigate to="/super-admin/platform-settings?tab=ai" replace /> },
          // Unified cross-role directory. The per-role create/edit forms below
          // remain the place accounts are actually managed.
          { path: "users", element: <Navigate to="/super-admin/users/super-admins" replace /> },
          { path: "users/:role", element: <Users /> },
          { path: "users/:id/edit", element: <DirectStudentForm /> },
          // The old single-role list screens now live as tabs of the directory.
          { path: "accounts", element: <Navigate to="/super-admin/users/super-admins" replace /> },
          { path: "accounts/new", element: <AccountForm /> },
          { path: "accounts/:id", element: <AccountForm /> },
          { path: "instructors", element: <Navigate to="/super-admin/users/sa-instructors" replace /> },
          { path: "instructors/new", element: <InstructorForm /> },
          { path: "instructors/:id", element: <InstructorForm /> },
          { path: "modules", element: <ModuleControl /> },
          { path: "modules/:id", element: <ModuleControlDetail /> },
          { path: "grading", element: <GradingOversight /> },
          { path: "notifications", element: <PlatformNotifications /> },
          { path: "support-tickets", element: <SupportTickets /> },
          { path: "inbox", element: <NotificationsInbox fallbackRoute="/super-admin/dashboard" /> },
          { path: "courses", element: <Navigate to="/super-admin/modules" replace /> },
          { path: "courses/:id", element: <Navigate to="/super-admin/modules" replace /> },
          { path: "profile", element: <Profile /> },
          { path: "sessions", element: <Sessions /> },
          { path: "change-password", element: <ChangePassword /> },
          { path: "dev-settings", element: <DeveloperSettings /> },
          { path: "platform-settings", element: <DeveloperSettings /> },
          { path: "logs", element: <Logs /> },
          { path: "terminal", element: <Terminal /> },
          { path: "onboarding", element: <Navigate to="/super-admin/institutes" replace /> },
          { path: "onboarding/new", element: <Navigate to="/super-admin/institutes/new" replace /> },
          { path: "onboarding/:id", element: <Navigate to="/super-admin/institutes" replace /> },
          { path: "plans", element: <Plans /> },
          { path: "plans/new", element: <PlanForm /> },
          { path: "plans/:id", element: <PlanForm /> },
          // Institute plans are no longer a catalogue: an institute's plan is
          // part of its access agreement, authored on the institute form.
          { path: "institute-plans", element: <Navigate to="/super-admin/institutes" replace /> },
          { path: "institute-plans/new", element: <Navigate to="/super-admin/institutes" replace /> },
          { path: "institute-plans/:id", element: <Navigate to="/super-admin/institutes" replace /> },
          { path: "subscriptions", element: <Subscriptions /> },
          { path: "institutes", element: <Institutes /> },
          { path: "institutes/new", element: <InstituteForm /> },
          { path: "institutes/:id", element: <InstituteForm /> },
          { path: "institutes/:id/branding", element: <InstituteBranding /> },
          { path: "institutes/:id/accounts", element: <SuperAdminInstituteAccounts /> },
          { path: "institutes/:id/accounts/students/new", element: <SuperAdminStudentForm /> },
          { path: "institutes/:id/accounts/staff/new", element: <SuperAdminInstructorForm /> },
          { path: "institutes/:id/accounts/students/:memberId", element: <SuperAdminStudentOverview /> },
          { path: "institutes/:id/accounts/students/:memberId/edit", element: <SuperAdminStudentForm /> },
          { path: "institutes/:id/accounts/staff/:memberId/edit", element: <SuperAdminInstructorForm /> },
          { path: "institutes/:id/students", element: <SuperAdminInstituteStudents /> },
          { path: "institutes/:id/students/new", element: <SuperAdminStudentForm /> },
          { path: "institutes/:id/students/:studentId", element: <SuperAdminStudentOverview /> },
          { path: "institutes/:id/students/:studentId/edit", element: <SuperAdminStudentForm /> },
          { path: "trial-config", element: <TrialConfig /> },
          { path: "demo-accounts", element: <DemoAccounts /> },
          { path: "coupons", element: <MonetaryAnalyticsRoute><Coupons /></MonetaryAnalyticsRoute> },
          { path: "coupons/new", element: <MonetaryAnalyticsRoute><CouponForm /></MonetaryAnalyticsRoute> },
          { path: "coupons/:id", element: <MonetaryAnalyticsRoute><CouponForm /></MonetaryAnalyticsRoute> },
          { path: "payments", element: <MonetaryAnalyticsRoute><Payments /></MonetaryAnalyticsRoute> },
          { path: "payments/:id/invoice", element: <MonetaryAnalyticsRoute><Invoice /></MonetaryAnalyticsRoute> },
          { path: "payment-methods", element: <MonetaryAnalyticsRoute><PaymentMethods /></MonetaryAnalyticsRoute> },
          { path: "gst-rates", element: <MonetaryAnalyticsRoute><GstRates /></MonetaryAnalyticsRoute> },
          { path: "revenue", element: <MonetaryAnalyticsRoute><RevenueDashboard /></MonetaryAnalyticsRoute> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["DEVELOPER"]} />,
    children: [
      {
        path: `/${developerAccessSlug}`,
        element: <DeveloperLayout />,
        children: [
          { path: "", element: <Navigate to="panel" replace /> },
          { path: "panel", element: <DeveloperPanel /> },
          { path: "settings", element: <DeveloperSettings /> },
          { path: "notifications", element: <NotificationsInbox fallbackRoute={`/${developerAccessSlug}/panel`} /> },
          { path: "change-password", element: <ChangePassword apiBase={`/developer/${developerAccessSlug}`} /> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["SA_INSTRUCTOR"]} />,
    children: [
      {
        path: "/super-admin/instructor",
        element: <InstructorLayout />,
        children: [
          { path: "dashboard", element: <InstructorDashboard /> },
          { path: "workspace", element: <Navigate to="/super-admin/instructor/modules" replace /> },
          { path: "modules", element: <Modules /> },
          { path: "modules/new/:type", element: <ModuleEditor /> },
          { path: "modules/:id", element: <ModuleEditor /> },
          { path: "courses/*", element: <Navigate to="/super-admin/instructor/modules" replace /> },
          { path: "question-banks/*", element: <Navigate to="/super-admin/instructor/modules" replace /> },
          { path: "tests/*", element: <Navigate to="/super-admin/instructor/modules" replace /> },
          { path: "grading", element: <GradingQueue /> },
          { path: "grading/:id", element: <GradingDetail /> },
          { path: "notifications", element: <NotificationsInbox fallbackRoute="/super-admin/instructor/dashboard" /> },
          { path: "support", element: <SupportCenter /> },
          { path: "profile", element: <InstructorProfile /> },
          { path: "sessions", element: <Sessions apiBase="/instructor" /> },
          { path: "change-password", element: <ChangePassword apiBase="/instructor" /> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["INSTITUTE_ADMIN"]} />,
    children: [
      {
        path: "/institute-portal",
        element: <InstituteLayout />,
        children: [
          { index: true, element: <Navigate to="dashboard" replace /> },
          { path: "dashboard", element: <InstituteDashboard /> },
          { path: "students", element: <InstituteMembers role="STUDENT" /> },
          { path: "students/new", element: <InstituteMemberForm role="STUDENT" /> },
          { path: "students/:id", element: <StudentOverview /> },
          { path: "students/:id/edit", element: <InstituteMemberForm role="STUDENT" /> },
          { path: "staff", element: <InstituteMembers role="INST_INSTRUCTOR" /> },
          { path: "staff/new", element: <InstituteMemberForm role="INST_INSTRUCTOR" /> },
          { path: "staff/:id", element: <InstituteMemberForm role="INST_INSTRUCTOR" /> },
          { path: "billing", element: <InstituteBilling /> },
          { path: "ai-quota", element: <InstituteAiQuota /> },
          { path: "announcements", element: <InstituteAnnouncements /> },
          { path: "notifications", element: <NotificationsInbox fallbackRoute="/institute-portal/dashboard" /> },
          { path: "support", element: <SupportCenter /> },
          { path: "support-tickets", element: <InstituteSupportTickets /> },
          { path: "profile", element: <InstituteProfile /> },
          { path: "sessions", element: <Sessions apiBase="/institute" /> },
          { path: "change-password", element: <ChangePassword apiBase="/institute" /> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["INST_INSTRUCTOR"]} />,
    children: [
      {
        path: "/institute-instructor",
        element: <InstituteInstructorLayout />,
        children: [
          { index: true, element: <Navigate to="grading" replace /> },
          { path: "grading", element: <GradingQueue /> },
          { path: "grading/:id", element: <GradingDetail /> },
          { path: "notifications", element: <NotificationsInbox fallbackRoute="/institute-instructor/grading" /> },
          { path: "support", element: <SupportCenter /> },
          { path: "sessions", element: <Sessions apiBase="/institute-instructor" /> },
          { path: "change-password", element: <ChangePassword apiBase="/institute-instructor" /> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["STUDENT"]} />,
    children: [
      {
        path: "/student",
        element: <StudentLayout />,
        children: [
          { path: "dashboard", element: <StudentDashboard /> },
          { path: "courses", element: <StudentCourseCatalog /> },
          { path: "my-courses", element: <MyCourses /> },
          { path: "attempts", element: <StudentAttempts /> },
          { path: "attempts/:id/result", element: <AttemptResult /> },
          { path: "attempts/:id/result/details", element: <AttemptResultDetails /> },
          { path: "progress", element: <StudentProgress /> },
          { path: "announcements", element: <StudentAnnouncements /> },
          { path: "notifications", element: <NotificationsInbox fallbackRoute="/student/dashboard" /> },
          { path: "support", element: <SupportCenter /> },
          { path: "profile", element: <StudentProfile /> },
          { path: "purchase-history", element: <StudentPurchaseHistory /> },
          { path: "sessions", element: <Sessions apiBase="/student" /> },

          { path: "change-password", element: <ChangePassword apiBase="/student" /> },
        ],
      },
      { path: "/student/attempts/:id/take", element: <TestRunner /> },
    ],
  },
]);
