import { createBrowserRouter, Navigate } from "react-router-dom";
import { LandingLayout } from "../components/landing/LandingLayout";
import { Login } from "../pages/Login";
import {
  AboutUs,
  AccountForm,
  AccountsList,
  AttemptResult,
  AttemptResultDetails,
  ChangePassword,
  ContactUs,
  CouponForm,
  Coupons,
  Dashboard,
  DashboardLayout,
  DemoAccounts,
  DeveloperSettings,
  GradingDetail,
  GradingOversight,
  GradingQueue,
  Home,
  InstituteAnnouncements,
  InstituteBilling,
  InstituteBranding,
  InstituteDashboard,
  InstituteForm,
  InstituteInstructorLayout,
  InstituteLayout,
  InstituteMemberForm,
  InstituteMembers,
  InstituteOnboarding,
  InstituteProfile,
  Instructors,
  InstructorDashboard,
  InstructorForm,
  InstructorLayout,
  InstructorProfile,
  Institutes,
  InstituteOnboardings,
  Invoice,
  Logs,
  ModuleControl,
  ModuleControlDetail,
  ModuleEditor,
  Modules,
  MyCourses,
  NotificationsInbox,
  PaymentMethods,
  Payments,
  PlanForm,
  Plans,
  PlatformNotifications,
  Profile,
  Register,
  ResetPassword,
  RevenueDashboard,
  Sessions,
  ShowcasePlans,
  StudentAnnouncements,
  StudentAttempts,
  StudentCourseCatalog,
  StudentDashboard,
  StudentLayout,
  StudentOverview,
  StudentProfile,
  StudentProgress,
  Subscriptions,
  SuperAdminInstituteAccounts,
  SuperAdminInstituteStudents,
  SuperAdminInstructorForm,
  SuperAdminStudentForm,
  SuperAdminStudentOverview,
  Terminal,
  TestRunner,
  TestingLoginSelector,
  TrialConfig,
} from "./lazyPages";
import { ProtectedRoute } from "./ProtectedRoute";
import { BlogsList } from "../pages/public/BlogsList";
import { BlogDetail } from "../pages/public/BlogDetail";
import { SuperAdminTestimonials } from "../pages/superadmin/SuperAdminTestimonials";
import { SuperAdminBlogs } from "../pages/superadmin/SuperAdminBlogs";
import { SuperAdminBlogForm } from "../pages/superadmin/SuperAdminBlogForm";
import { SuperAdminSEOSettings } from "../pages/superadmin/SuperAdminSEOSettings";

export const router = createBrowserRouter([
  {
    element: <LandingLayout />,
    children: [
      { path: "/", element: <Home /> },
      { path: "/about", element: <AboutUs /> },
      { path: "/plans", element: <ShowcasePlans /> },
      { path: "/contact", element: <ContactUs /> },
      { path: "/blogs", element: <BlogsList /> },
      { path: "/blogs/:slug", element: <BlogDetail /> },
    ],
  },
  { path: "/testing-login", element: <TestingLoginSelector /> },
  { path: "/super-admin/login", element: <Login allowedRoles={["SUPER_ADMIN", "SA_INSTRUCTOR"]} title="Super Admin & Author Portal" subtitle="Sign in to platform management or assessment authoring" /> },
  { path: "/sa-instructor/login", element: <Navigate to="/super-admin/login?role=SA_INSTRUCTOR" replace /> },
  { path: "/super-admin", element: <Navigate to="/super-admin/login" replace /> },
  { path: "/super-admin/instructor", element: <Navigate to="/super-admin/instructor/dashboard" replace /> },
  { path: "/admin-login", element: <Navigate to="/super-admin/login" replace /> },
  { path: "/sa-instructor-login", element: <Navigate to="/super-admin/login?role=SA_INSTRUCTOR" replace /> },
  { path: "/instructor", element: <Navigate to="/super-admin/instructor/dashboard" replace /> },
  { path: "/instructor/*", element: <Navigate to="/super-admin/instructor/dashboard" replace /> },
  { path: "/login", element: <Login allowedRoles={["INSTITUTE_ADMIN", "INST_INSTRUCTOR", "STUDENT"]} title="Portal Login" subtitle="Select your role and sign in to your portal" /> },
  { path: "/register", element: <Register /> },
  { path: "/reset-password", element: <ResetPassword /> },
  {
    element: <ProtectedRoute allowedRoles={["SUPER_ADMIN"]} />,
    children: [
      {
        path: "/super-admin",
        element: <DashboardLayout />,
        children: [
          { path: "dashboard", element: <Dashboard /> },
          { path: "testimonials", element: <SuperAdminTestimonials /> },
          { path: "blogs", element: <SuperAdminBlogs /> },
          { path: "blogs/new", element: <SuperAdminBlogForm /> },
          { path: "blogs/:id", element: <SuperAdminBlogForm /> },
          { path: "seo-settings", element: <SuperAdminSEOSettings /> },
          { path: "accounts", element: <AccountsList /> },
          { path: "accounts/new", element: <AccountForm /> },
          { path: "accounts/:id", element: <AccountForm /> },
          { path: "instructors", element: <Instructors /> },
          { path: "instructors/new", element: <InstructorForm /> },
          { path: "instructors/:id", element: <InstructorForm /> },
          { path: "modules", element: <ModuleControl /> },
          { path: "modules/:id", element: <ModuleControlDetail /> },
          { path: "grading", element: <GradingOversight /> },
          { path: "notifications", element: <PlatformNotifications /> },
          { path: "inbox", element: <NotificationsInbox fallbackRoute="/super-admin/dashboard" /> },
          { path: "courses", element: <Navigate to="/super-admin/modules" replace /> },
          { path: "courses/:id", element: <Navigate to="/super-admin/modules" replace /> },
          { path: "profile", element: <Profile /> },
          { path: "sessions", element: <Sessions /> },
          { path: "change-password", element: <ChangePassword /> },
          { path: "dev-settings", element: <DeveloperSettings /> },
          { path: "logs", element: <Logs /> },
          { path: "terminal", element: <Terminal /> },
          { path: "onboarding", element: <InstituteOnboardings /> },
          { path: "onboarding/new", element: <InstituteOnboarding /> },
          { path: "onboarding/:id", element: <InstituteOnboarding /> },
          { path: "plans", element: <Plans /> },
          { path: "plans/new", element: <PlanForm /> },
          { path: "plans/:id", element: <PlanForm /> },
          { path: "subscriptions", element: <Subscriptions /> },
          { path: "institutes", element: <Institutes /> },
          { path: "institutes/new", element: <InstituteForm /> },
          { path: "institutes/:id", element: <InstituteForm /> },
          { path: "institutes/:id/branding", element: <InstituteBranding /> },
          { path: "institutes/:id/accounts", element: <SuperAdminInstituteAccounts /> },
          { path: "institutes/:id/accounts/students/new", element: <SuperAdminStudentForm /> },
          { path: "institutes/:id/accounts/staff/new", element: <SuperAdminInstructorForm /> },
          { path: "institutes/:id/accounts/students/:memberId", element: <SuperAdminStudentOverview /> },
          { path: "institutes/:id/accounts/students/:memberId/edit", element: <SuperAdminStudentForm /> },
          { path: "institutes/:id/accounts/staff/:memberId/edit", element: <SuperAdminInstructorForm /> },
          { path: "institutes/:id/students", element: <SuperAdminInstituteStudents /> },
          { path: "institutes/:id/students/new", element: <SuperAdminStudentForm /> },
          { path: "institutes/:id/students/:studentId", element: <SuperAdminStudentOverview /> },
          { path: "institutes/:id/students/:studentId/edit", element: <SuperAdminStudentForm /> },
          { path: "trial-config", element: <TrialConfig /> },
          { path: "demo-accounts", element: <DemoAccounts /> },
          { path: "coupons", element: <Coupons /> },
          { path: "coupons/new", element: <CouponForm /> },
          { path: "coupons/:id", element: <CouponForm /> },
          { path: "payments", element: <Payments /> },
          { path: "payments/:id/invoice", element: <Invoice /> },
          { path: "payment-methods", element: <PaymentMethods /> },
          { path: "revenue", element: <RevenueDashboard /> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["SA_INSTRUCTOR"]} />,
    children: [
      {
        path: "/super-admin/instructor",
        element: <InstructorLayout />,
        children: [
          { path: "dashboard", element: <InstructorDashboard /> },
          { path: "workspace", element: <Navigate to="/super-admin/instructor/modules" replace /> },
          { path: "modules", element: <Modules /> },
          { path: "modules/new/:type", element: <ModuleEditor /> },
          { path: "modules/:id", element: <ModuleEditor /> },
          { path: "courses/*", element: <Navigate to="/super-admin/instructor/modules" replace /> },
          { path: "question-banks/*", element: <Navigate to="/super-admin/instructor/modules" replace /> },
          { path: "tests/*", element: <Navigate to="/super-admin/instructor/modules" replace /> },
          { path: "grading", element: <GradingQueue /> },
          { path: "grading/:id", element: <GradingDetail /> },
          { path: "notifications", element: <NotificationsInbox fallbackRoute="/super-admin/instructor/dashboard" /> },
          { path: "profile", element: <InstructorProfile /> },
          { path: "sessions", element: <Sessions apiBase="/instructor" /> },
          { path: "change-password", element: <ChangePassword apiBase="/instructor" /> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["INSTITUTE_ADMIN"]} />,
    children: [
      {
        path: "/institute-portal",
        element: <InstituteLayout />,
        children: [
          { index: true, element: <Navigate to="dashboard" replace /> },
          { path: "dashboard", element: <InstituteDashboard /> },
          { path: "students", element: <InstituteMembers role="STUDENT" /> },
          { path: "students/new", element: <InstituteMemberForm role="STUDENT" /> },
          { path: "students/:id", element: <StudentOverview /> },
          { path: "students/:id/edit", element: <InstituteMemberForm role="STUDENT" /> },
          { path: "staff", element: <InstituteMembers role="INST_INSTRUCTOR" /> },
          { path: "staff/new", element: <InstituteMemberForm role="INST_INSTRUCTOR" /> },
          { path: "staff/:id", element: <InstituteMemberForm role="INST_INSTRUCTOR" /> },
          { path: "billing", element: <InstituteBilling /> },
          { path: "announcements", element: <InstituteAnnouncements /> },
          { path: "notifications", element: <NotificationsInbox fallbackRoute="/institute-portal/dashboard" /> },
          { path: "profile", element: <InstituteProfile /> },
          { path: "sessions", element: <Sessions apiBase="/institute" /> },
          { path: "change-password", element: <ChangePassword apiBase="/institute" /> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["INST_INSTRUCTOR"]} />,
    children: [
      {
        path: "/institute-instructor",
        element: <InstituteInstructorLayout />,
        children: [
          { index: true, element: <Navigate to="grading" replace /> },
          { path: "grading", element: <GradingQueue /> },
          { path: "grading/:id", element: <GradingDetail /> },
          { path: "notifications", element: <NotificationsInbox fallbackRoute="/institute-instructor/grading" /> },
          { path: "sessions", element: <Sessions apiBase="/institute-instructor" /> },
          { path: "change-password", element: <ChangePassword apiBase="/institute-instructor" /> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["STUDENT"]} />,
    children: [
      {
        path: "/student",
        element: <StudentLayout />,
        children: [
          { path: "dashboard", element: <StudentDashboard /> },
          { path: "courses", element: <StudentCourseCatalog /> },
          { path: "my-courses", element: <MyCourses /> },
          { path: "attempts", element: <StudentAttempts /> },
          { path: "attempts/:id/result", element: <AttemptResult /> },
          { path: "attempts/:id/result/details", element: <AttemptResultDetails /> },
          { path: "progress", element: <StudentProgress /> },
          { path: "announcements", element: <StudentAnnouncements /> },
          { path: "notifications", element: <NotificationsInbox fallbackRoute="/student/dashboard" /> },
          { path: "profile", element: <StudentProfile /> },
          { path: "sessions", element: <Sessions apiBase="/student" /> },
          { path: "change-password", element: <ChangePassword apiBase="/student" /> },
        ],
      },
      { path: "/student/attempts/:id/take", element: <TestRunner /> },
    ],
  },
]);
