import { createBrowserRouter, Navigate } from "react-router-dom";
import { LandingLayout } from "../components/landing/LandingLayout";
import { RequireActivePlan } from "./RequireActivePlan";
import { RequireInstituteSetup } from "./RequireInstituteSetup";
import { InstituteSignupRedirect } from "./InstituteSignupRedirect";
import { Login } from "../pages/Login";
import {
  AboutUs,
  ExamNews,
  BlogDetail,
  BlogsList,
  AccountForm,
  AllSessions,
  AttemptResult,
  AttemptResultDetails,
  ChangePassword,
  ContactUs,
  CouponForm,
  Coupons,
  Dashboard,
  DashboardLayout,
  DeveloperAnalytics,
  DeveloperControl,
  DeveloperOps,
  DeveloperLayout,
  DeveloperPanel,
  DeveloperSettings,
  DirectStudentForm,
  GradingDetail,
  GradingOversight,
  GradingQueue,
  GrammarContent,
  StudyMaterial,
  GstRates,

  Home,
  InstituteAnnouncements,
  InstituteBilling,
  InstituteBranding,
  InstituteDashboard,
  InstituteForm,
  InstituteInstructorLayout,
  InstituteInstructorProfile,
  InstituteLayout,
  InstituteMemberForm,
  InstituteMembers,
  InstituteProfile,
  InstituteSupportTickets,
  InstructorDashboard,
  InstructorForm,
  InstructorLayout,
  InstructorProfile,
  Institutes,
  Invoice,
  Logs,
  ModuleControl,
  ModuleControlDetail,
  ModuleEditor,
  Modules,
  MyCourses,
  NotificationsInbox,
  PaymentMethods,
  Payments,
  PlanForm,
  Plans,
  PlatformNotifications,
  Profile,
  ResetPassword,
  RetakeRequests,
  RevenueDashboard,
  Sessions,
  InstituteBrandingPage,
  InstituteSetup,
  SuperAdminInstituteSignups,
  ShowcasePlans,
  StudentAnnouncements,
  StudentAttempts,
  StudentCourseCatalog,
  StudentDashboard,
  StudentLayout,
  StudentOverview,
  StudentProfile,
  StudentProgress,
  StudentPurchaseHistory,
  StudentVouchers,
  Subscriptions,
  SupportCenter,
  SupportTickets,
  SuperAdminBlogForm,
  SuperAdminBlogs,
  SuperAdminInstituteAccounts,
  SuperAdminInstituteStudents,
  SuperAdminInstructorForm,
  SuperAdminSEOSettings,
  SuperAdminInstagramSettings,
  SuperAdminStudentForm,
  SuperAdminStudentOverview,
  DeveloperInstituteAccounts,
  DeveloperInstituteStudents,
  DeveloperInstructorForm,
  DeveloperStudentForm,
  DeveloperStudentOverview,
  SuperAdminTestimonials,
  Terminal,
  TestRunner,
  TestingLoginSelector,
  TrialConfig,
  Users,
  Vouchers,
  PublicVouchersPage,
} from "./lazyPages";
import { ProtectedRoute } from "./ProtectedRoute";
import { MonetaryAnalyticsRoute } from "./MonetaryAnalyticsRoute";
import { RouteErrorBoundary } from "./RouteErrorBoundary";

const developerAccessSlug = import.meta.env.VITE_DEVELOPER_ACCESS_SLUG || "vh-control-9f4c2a";

export const router = createBrowserRouter([
  {
    element: <LandingLayout />,
    errorElement: <RouteErrorBoundary />,
    children: [
      { path: "/", element: <Home /> },
      // The lander's own auth: these render the landing page with the login or
      // register overlay on top, so a visitor signing in never loses the page
      // they were reading. Platform roles use this same overlay via role query
      // params so reloads do not jump to a separate login screen.
      { path: "/login", element: <Home /> },
      { path: "/register", element: <Home /> },
      { path: "/about", element: <AboutUs /> },
      { path: "/plans", element: <ShowcasePlans /> },
      // One application form, and it lives on the contact page in the lander's
      // own design language. This path is kept because every footer links to
      // it, and it carries the chosen tier through.
      { path: "/institute-signup", element: <InstituteSignupRedirect /> },
      { path: "/contact", element: <ContactUs /> },
      { path: "/blogs", element: <BlogsList /> },
      { path: "/blogs/:slug", element: <BlogDetail /> },
      { path: "/vouchers", element: <PublicVouchersPage /> },
    ],
  },
  { path: "/testing-login", element: <TestingLoginSelector />, errorElement: <RouteErrorBoundary /> },
  { path: "/super-admin/login", element: <Navigate to="/login?role=SUPER_ADMIN" replace /> },
  { path: `/${developerAccessSlug}/login`, element: <Login allowedRoles={["DEVELOPER"]} title="Developer Control" subtitle="Verified developer access only" /> },
  { path: "/sa-instructor/login", element: <Navigate to="/login?role=SA_INSTRUCTOR" replace /> },
  { path: "/super-admin", element: <Navigate to="/login?role=SUPER_ADMIN" replace /> },
  { path: "/super-admin/instructor", element: <Navigate to="/super-admin/instructor/dashboard" replace /> },
  { path: "/admin-login", element: <Navigate to="/login?role=SUPER_ADMIN" replace /> },
  { path: "/sa-instructor-login", element: <Navigate to="/login?role=SA_INSTRUCTOR" replace /> },
  { path: "/instructor", element: <Navigate to="/super-admin/instructor/dashboard" replace /> },
  { path: "/instructor/*", element: <Navigate to="/super-admin/instructor/dashboard" replace /> },
  { path: "/reset-password", element: <ResetPassword />, errorElement: <RouteErrorBoundary /> },
  {
    element: <ProtectedRoute allowedRoles={["SUPER_ADMIN"]} />,
    errorElement: <RouteErrorBoundary />,
    children: [
      {
        path: "/super-admin",
        element: <DashboardLayout />,
        children: [
          { path: "dashboard", element: <Dashboard /> },
          { path: "testimonials", element: <SuperAdminTestimonials /> },
          { path: "blogs", element: <SuperAdminBlogs /> },
          { path: "blogs/new", element: <SuperAdminBlogForm /> },
          { path: "blogs/:id", element: <SuperAdminBlogForm /> },
          { path: "seo-settings", element: <SuperAdminSEOSettings /> },
          { path: "instagram-settings", element: <SuperAdminInstagramSettings /> },
          { path: "ai-settings", element: <Navigate to="/super-admin/platform-settings?tab=ai" replace /> },
          // Unified cross-role directory. The per-role create/edit forms below
          // remain the place accounts are actually managed.
          { path: "users", element: <Navigate to="/super-admin/users/super-admins" replace /> },
          { path: "users/:role", element: <Users /> },
          { path: "users/:id/edit", element: <DirectStudentForm /> },
          // The old single-role list screens now live as tabs of the directory.
          { path: "accounts", element: <Navigate to="/super-admin/users/super-admins" replace /> },
          { path: "accounts/new", element: <AccountForm /> },
          { path: "accounts/:id", element: <AccountForm /> },
          { path: "instructors", element: <Navigate to="/super-admin/users/sa-instructors" replace /> },
          { path: "instructors/new", element: <InstructorForm /> },
          { path: "instructors/:id", element: <InstructorForm /> },
          { path: "modules", element: <ModuleControl /> },
          { path: "modules/:id", element: <ModuleControlDetail /> },
          { path: "grading", element: <GradingOversight /> },
          { path: "retake-requests", element: <RetakeRequests /> },
          { path: "notifications", element: <PlatformNotifications /> },
          { path: "support-tickets", element: <SupportTickets /> },
          { path: "inbox", element: <NotificationsInbox fallbackRoute="/super-admin/dashboard" /> },
          { path: "courses", element: <Navigate to="/super-admin/modules" replace /> },
          { path: "courses/:id", element: <Navigate to="/super-admin/modules" replace /> },
          { path: "profile", element: <Profile /> },
          { path: "sessions", element: <Sessions /> },
          { path: "all-sessions", element: <AllSessions /> },
          { path: "change-password", element: <ChangePassword /> },
          { path: "dev-settings", element: <DeveloperSettings /> },
          { path: "platform-settings", element: <DeveloperSettings /> },
          { path: "logs", element: <Logs /> },
          { path: "terminal", element: <Terminal /> },
          { path: "onboarding", element: <Navigate to="/super-admin/institutes" replace /> },
          { path: "onboarding/new", element: <Navigate to="/super-admin/institutes/new" replace /> },
          { path: "onboarding/:id", element: <Navigate to="/super-admin/institutes" replace /> },
          { path: "plans", element: <Plans /> },
          { path: "plans/new", element: <PlanForm /> },
          { path: "plans/:id", element: <PlanForm /> },
          // Institute plans are no longer a catalogue: an institute's plan is
          // part of its access agreement, authored on the institute form.
          { path: "institute-plans", element: <Navigate to="/super-admin/institutes" replace /> },
          { path: "institute-plans/new", element: <Navigate to="/super-admin/institutes" replace /> },
          { path: "institute-plans/:id", element: <Navigate to="/super-admin/institutes" replace /> },
          // Public applications waiting on a human decision.
          { path: "institute-signups", element: <SuperAdminInstituteSignups /> },
          { path: "subscriptions", element: <Subscriptions /> },
          { path: "institutes", element: <Institutes /> },
          { path: "institutes/new", element: <InstituteForm /> },
          { path: "institutes/:id", element: <InstituteForm /> },
          { path: "institutes/:id/branding", element: <InstituteBranding /> },
          { path: "institutes/:id/accounts", element: <SuperAdminInstituteAccounts /> },
          { path: "institutes/:id/accounts/students/new", element: <SuperAdminStudentForm /> },
          { path: "institutes/:id/accounts/staff/new", element: <SuperAdminInstructorForm /> },
          { path: "institutes/:id/accounts/students/:memberId", element: <SuperAdminStudentOverview /> },
          { path: "institutes/:id/accounts/students/:memberId/edit", element: <SuperAdminStudentForm /> },
          { path: "institutes/:id/accounts/staff/:memberId/edit", element: <SuperAdminInstructorForm /> },
          { path: "institutes/:id/students", element: <SuperAdminInstituteStudents /> },
          { path: "institutes/:id/students/new", element: <SuperAdminStudentForm /> },
          { path: "institutes/:id/students/:studentId", element: <SuperAdminStudentOverview /> },
          { path: "institutes/:id/students/:studentId/edit", element: <SuperAdminStudentForm /> },
          { path: "trial-config", element: <TrialConfig /> },
          { path: "coupons", element: <MonetaryAnalyticsRoute><Coupons /></MonetaryAnalyticsRoute> },
          { path: "coupons/new", element: <MonetaryAnalyticsRoute><CouponForm /></MonetaryAnalyticsRoute> },
          { path: "coupons/:id", element: <MonetaryAnalyticsRoute><CouponForm /></MonetaryAnalyticsRoute> },
          { path: "vouchers", element: <MonetaryAnalyticsRoute><Vouchers /></MonetaryAnalyticsRoute> },
          { path: "payments", element: <MonetaryAnalyticsRoute><Payments /></MonetaryAnalyticsRoute> },
          { path: "payments/:id/invoice", element: <MonetaryAnalyticsRoute><Invoice /></MonetaryAnalyticsRoute> },
          { path: "payment-methods", element: <MonetaryAnalyticsRoute><PaymentMethods /></MonetaryAnalyticsRoute> },
          { path: "gst-rates", element: <MonetaryAnalyticsRoute><GstRates /></MonetaryAnalyticsRoute> },
          { path: "revenue", element: <MonetaryAnalyticsRoute><RevenueDashboard /></MonetaryAnalyticsRoute> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["DEVELOPER"]} />,
    errorElement: <RouteErrorBoundary />,
    children: [
      {
        path: `/${developerAccessSlug}`,
        element: <DeveloperLayout />,
        children: [
          { path: "", element: <Navigate to="panel" replace /> },
          { path: "panel", element: <DeveloperPanel /> },
          { path: "analytics", element: <DeveloperAnalytics /> },
          { path: "site-control", element: <DeveloperControl /> },
          { path: "operations", element: <DeveloperOps /> },
          { path: "settings", element: <DeveloperSettings /> },
          { path: "notifications", element: <NotificationsInbox fallbackRoute={`/${developerAccessSlug}/panel`} /> },
          { path: "change-password", element: <ChangePassword apiBase={`/developer/${developerAccessSlug}`} /> },
          { path: "institutes", element: <Institutes basePath={`/${developerAccessSlug}`} /> },
          { path: "institutes/new", element: <InstituteForm basePath={`/${developerAccessSlug}`} /> },
          { path: "institutes/:id", element: <InstituteForm basePath={`/${developerAccessSlug}`} /> },
          { path: "institutes/:id/branding", element: <InstituteBranding /> },
          { path: "institutes/:id/accounts", element: <DeveloperInstituteAccounts /> },
          { path: "institutes/:id/accounts/students/new", element: <DeveloperStudentForm /> },
          { path: "institutes/:id/accounts/staff/new", element: <DeveloperInstructorForm /> },
          { path: "institutes/:id/accounts/students/:memberId", element: <DeveloperStudentOverview /> },
          { path: "institutes/:id/accounts/students/:memberId/edit", element: <DeveloperStudentForm /> },
          { path: "institutes/:id/accounts/staff/:memberId/edit", element: <DeveloperInstructorForm /> },
          { path: "institutes/:id/students", element: <DeveloperInstituteStudents /> },
          { path: "institutes/:id/students/new", element: <DeveloperStudentForm /> },
          { path: "institutes/:id/students/:studentId", element: <DeveloperStudentOverview /> },
          { path: "institutes/:id/students/:studentId/edit", element: <DeveloperStudentForm /> },
          { path: "users", element: <Navigate to={`/${developerAccessSlug}/users/super-admins`} replace /> },
          { path: "users/:role", element: <Users basePath={`/${developerAccessSlug}`} /> },
          { path: "users/:id/edit", element: <DirectStudentForm portalBasePath={`/${developerAccessSlug}`} /> },
          { path: "accounts", element: <Navigate to={`/${developerAccessSlug}/users/super-admins`} replace /> },
          { path: "accounts/new", element: <AccountForm basePath={`/${developerAccessSlug}`} /> },
          { path: "accounts/:id", element: <AccountForm basePath={`/${developerAccessSlug}`} /> },
          { path: "instructors", element: <Navigate to={`/${developerAccessSlug}/users/sa-instructors`} replace /> },
          { path: "instructors/new", element: <InstructorForm basePath={`/${developerAccessSlug}`} /> },
          { path: "instructors/:id", element: <InstructorForm basePath={`/${developerAccessSlug}`} /> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["SA_INSTRUCTOR"]} />,
    errorElement: <RouteErrorBoundary />,
    children: [
      {
        path: "/super-admin/instructor",
        element: <InstructorLayout />,
        children: [
          { path: "dashboard", element: <InstructorDashboard /> },
          { path: "workspace", element: <Navigate to="/super-admin/instructor/modules" replace /> },
          { path: "modules", element: <Modules /> },
          { path: "modules/new/:type", element: <ModuleEditor /> },
          { path: "modules/:id", element: <ModuleEditor /> },
          { path: "courses/*", element: <Navigate to="/super-admin/instructor/modules" replace /> },
          { path: "question-banks/*", element: <Navigate to="/super-admin/instructor/modules" replace /> },
          { path: "tests/*", element: <Navigate to="/super-admin/instructor/modules" replace /> },
          { path: "grading", element: <GradingQueue /> },
          { path: "grading/:id", element: <GradingDetail /> },
          { path: "grammar-content", element: <GrammarContent /> },
          { path: "notifications", element: <NotificationsInbox fallbackRoute="/super-admin/instructor/dashboard" /> },

          { path: "support", element: <SupportCenter /> },
          { path: "profile", element: <InstructorProfile /> },
          { path: "sessions", element: <Sessions apiBase="/instructor" /> },
          { path: "change-password", element: <ChangePassword apiBase="/instructor" /> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["INSTITUTE_ADMIN"]} />,
    errorElement: <RouteErrorBoundary />,
    children: [
      {
        path: "/institute-portal",
        // A newly approved institute has no term yet, so the whole portal is
        // held behind the setup wizard until one is paid for.
        element: (
          <RequireInstituteSetup>
            <InstituteLayout />
          </RequireInstituteSetup>
        ),
        children: [
          { index: true, element: <Navigate to="dashboard" replace /> },
          { path: "setup", element: <InstituteSetup /> },
          { path: "dashboard", element: <InstituteDashboard /> },
          { path: "students", element: <InstituteMembers role="STUDENT" /> },
          { path: "students/new", element: <InstituteMemberForm role="STUDENT" /> },
          { path: "students/:id", element: <StudentOverview /> },
          { path: "students/:id/edit", element: <InstituteMemberForm role="STUDENT" /> },
          { path: "staff", element: <InstituteMembers role="INST_INSTRUCTOR" /> },
          { path: "staff/new", element: <InstituteMemberForm role="INST_INSTRUCTOR" /> },
          { path: "staff/:id", element: <InstituteMemberForm role="INST_INSTRUCTOR" /> },
          { path: "billing", element: <InstituteBilling /> },
          // Behind the setup guard like everything else, so it is only reachable
          // once a plan has been paid for.
          { path: "branding", element: <InstituteBrandingPage /> },
          { path: "announcements", element: <InstituteAnnouncements /> },
          { path: "notifications", element: <NotificationsInbox fallbackRoute="/institute-portal/dashboard" /> },
          { path: "support", element: <SupportCenter /> },
          { path: "support-tickets", element: <InstituteSupportTickets /> },
          { path: "profile", element: <InstituteProfile /> },
          { path: "sessions", element: <Sessions apiBase="/institute" /> },
          { path: "change-password", element: <ChangePassword apiBase="/institute" /> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["INST_INSTRUCTOR"]} />,
    errorElement: <RouteErrorBoundary />,
    children: [
      {
        path: "/institute-instructor",
        element: <InstituteInstructorLayout />,
        children: [
          { index: true, element: <Navigate to="grading" replace /> },
          { path: "grading", element: <GradingQueue /> },
          { path: "grading/:id", element: <GradingDetail /> },
          { path: "notifications", element: <NotificationsInbox fallbackRoute="/institute-instructor/grading" /> },
          { path: "support", element: <SupportCenter /> },
          { path: "profile", element: <InstituteInstructorProfile /> },
          { path: "sessions", element: <Sessions apiBase="/institute-instructor" /> },
          { path: "change-password", element: <ChangePassword apiBase="/institute-instructor" /> },
        ],
      },
    ],
  },
  {
    element: <ProtectedRoute allowedRoles={["STUDENT"]} />,
    errorElement: <RouteErrorBoundary />,
    children: [
      {
        path: "/student",
        element: <StudentLayout />,
        children: [
          // Demo students (no active plan) only get My Tests, the plan
          // catalogue and their own account; everything else redirects.
          { path: "dashboard", element: <RequireActivePlan><StudentDashboard /></RequireActivePlan> },
          { path: "courses", element: <StudentCourseCatalog /> },
          { path: "my-courses", element: <MyCourses /> },
          // A demo student must be able to see the score they just earned.
          { path: "attempts", element: <StudentAttempts /> },
          { path: "attempts/:id/result", element: <AttemptResult /> },
          { path: "attempts/:id/result/details", element: <AttemptResultDetails /> },
          { path: "study-material", element: <RequireActivePlan><StudyMaterial /></RequireActivePlan> },
          { path: "progress", element: <RequireActivePlan><StudentProgress /></RequireActivePlan> },

          { path: "news", element: <RequireActivePlan><ExamNews /></RequireActivePlan> },
          { path: "announcements", element: <RequireActivePlan><StudentAnnouncements /></RequireActivePlan> },
          { path: "notifications", element: <RequireActivePlan><NotificationsInbox fallbackRoute="/student/dashboard" /></RequireActivePlan> },
          { path: "support", element: <RequireActivePlan><SupportCenter /></RequireActivePlan> },
          { path: "profile", element: <StudentProfile /> },
          { path: "vouchers", element: <RequireActivePlan><StudentVouchers /></RequireActivePlan> },
          { path: "purchase-history", element: <RequireActivePlan><StudentPurchaseHistory /></RequireActivePlan> },
          { path: "sessions", element: <Sessions apiBase="/student" /> },

          { path: "change-password", element: <ChangePassword apiBase="/student" /> },
        ],
      },
      { path: "/student/attempts/:id/take", element: <TestRunner /> },
    ],
  },
]);
