export const instituteMembersStrings = {
  eyebrow: "People",
  subtitle: "Manage and inspect institute accounts from one place.",
  downloadTemplate: "Download template",
  importCsvExcel: "Import CSV / Excel",
  addStudent: "Add student",
  addInstructor: "Add instructor",
  searchPlaceholder: (label: string) => `Search ${label.toLowerCase()}...`,
  filters: {
    accountType: {
      placeholder: "All account types",
      student: "Students",
      instructor: "Institute instructors",
    },
    status: {
      placeholder: "Any status",
      active: "Active",
      inactive: "Inactive",
      deleted: "Deleted",
      passwordResetPending: "Password reset pending",
    },
    activity: {
      placeholder: "Any test activity",
      hasAttempts: "Has test attempts",
      noAttempts: "No test attempts",
    },
    session: {
      placeholder: "Any device/session",
      activeSession: "Currently signed in",
      knownDevices: "Known devices",
      noDevices: "No known devices",
    },
  },
  bulkActions: {
    selectedSuffix: "selected",
    activate: "Activate",
    deactivate: "Deactivate",
    delete: "Delete",
    clear: "Clear",
  },
  featureLocked: {
    eyebrow: "Feature locked",
    title: "You do not have this feature",
    description:
      "This institute has 0 instructor slots assigned. Contact the Super Admin to enable instructor management for this institute.",
    contactCta: "Contact Super Admin",
    viewSubscription: "View subscription",
    emailPrefix: "Email:",
  },
  table: {
    name: "Name",
    email: "Email",
    type: "Type",
    tests: "Tests",
    devices: "Devices",
    contact: "Contact",
    status: "Status",
    created: "Created",
    actions: "Actions",
    emptyRow: (label: string) => `No ${label.toLowerCase()} found.`,
    passwordResetBadge: "password reset",
  },
  actionTooltips: {
    view: "View member",
    edit: "Edit member",
    resetPassword: "Reset password",
    deactivate: "Deactivate member",
    reactivate: "Reactivate member",
    delete: "Delete member",
  },
  credentialModal: {
    title: "Temporary password",
    shareHint: (name: string) => `Share this with ${name}. It will not be shown again.`,
    passwordLabel: "Password",
    copyPassword: "Copy password",
    done: "Done",
  },
  importModal: {
    title: "Student import",
    summary: (created: number, skipped: number, remaining: number) =>
      `${created} created, ${skipped} skipped, ${remaining} slots remaining.`,
    credentialsHeading: "Credentials",
    downloadCsv: "Download CSV",
    student: "Student",
    email: "Email",
    temporaryPassword: "Temporary password",
    skippedRowsHeading: "Skipped rows",
    row: "Row",
    reason: "Reason",
  },
  confirm: {
    deleteOne: (email: string) =>
      `Are you sure you want to delete member "${email}"? The account will be signed out while test history is retained.`,
    deleteOneTitle: "Delete Member",
    deleteMany: (count: number) =>
      `Are you sure you want to delete ${count} member${count === 1 ? "" : "s"}? Their accounts will be signed out while test history is retained.`,
    deleteManyTitle: "Delete Members",
    resetPassword: (email: string) => `Reset the password for ${email}?`,
  },
  errors: {
    load: (label: string) => `Failed to load ${label.toLowerCase()}.`,
    updateStatus: "Failed to update the member status.",
    resetPassword: "Failed to reset the password.",
    delete: "Failed to delete the member.",
    import: "Failed to import students.",
    bulkToggle: (action: string, failed: number, total: number) =>
      `Failed to ${action} ${failed} of ${total}.`,
    bulkDelete: (failed: number, total: number) => `Failed to delete ${failed} of ${total} members.`,
  },
} as const;
