export const vouchersStrings = {
  eyebrow: "Financial Operations",
  title: "Voucher Purchase & Inventory Management",
  subtitle: "Manage exam voucher types, offerings, bulk code uploads, stock levels, and purchase history",
  tabs: {
    types: "Voucher Master",
    offerings: "Offerings & Pricing",
    upload: "Bulk Code Upload",
    purchases: "Stock & Purchase History",
  },
  types: {
    addType: "Add Voucher Type",
    editType: "Edit Voucher Type",
    typeName: "Voucher Type Name",
    typeCode: "Code / Slug (e.g. language-cert-academic)",
    description: "Description",
    badgeColor: "Badge Color",
    defaultPrice: "Default Price (₹)",
    defaultValidity: "Default Validity (Days)",
    isActive: "Active Status",
    noTypes: "No voucher types created yet.",
  },
  offerings: {
    addOffering: "Create Voucher Offering",
    editOffering: "Edit Offering",
    title: "Offering Title",
    selectType: "Select Voucher Type",
    price: "Price (₹)",
    discountPrice: "Discount Price (₹)",
    validityDays: "Validity (Days)",
    gstRate: "GST Rate",
    isActive: "Active Status",
    noOfferings: "No voucher offerings created yet.",
  },
  upload: {
    title: "Bulk Code Upload",
    subtitle: "Upload PDF, Excel (.xlsx, .csv), Word (.docx), or Text (.txt) files containing 16-digit alphanumeric codes",
    selectType: "Select Voucher Type",
    chooseFile: "Choose File (PDF, XLSX, CSV, DOCX, TXT)",
    uploadBtn: "Extract & Import 16-Digit Codes",
    uploading: "Extracting codes...",
    successMsg: "Codes imported successfully",
  },
  purchases: {
    searchPlaceholder: "Search by purchase number, buyer name, email, phone...",
    purchaseNo: "Purchase Number",
    buyer: "Buyer Details",
    voucherInfo: "Voucher & Offering",
    code: "16-Digit Code",
    amount: "Amount Paid",
    status: "Status",
    date: "Purchase Date",
    validUntil: "Valid Until",
    viewInvoice: "View Invoice",
    noPurchases: "No voucher purchases recorded yet.",
  },
  invoiceModal: {
    title: "Voucher Purchase Tax Invoice",
    close: "Close",
    print: "Print / Save PDF",
  },
};
