export const accountFormStrings = {
  kicker: "Super Admin Access",
  newTitle: "New Super Admin Account",
  editTitle: "Edit Super Admin Account",
  subtitle: "Manage identity, contact details, and account security from one clean workspace.",
  loading: "Loading...",
  avatar: {
    newProfile: "New profile",
    profileImage: "Profile image",
    defaultName: "Super Admin",
    defaultEmailHint: "Add an email address to complete this account.",
    label: "Profile Image",
    uploading: "Uploading...",
    chooseImage: "Choose Image",
    fileHint: "PNG, JPG, or WebP from your system.",
  },
  personalDetails: {
    title: "Personal Details",
    description: "Keep the account profile easy to identify across admin tools.",
    firstName: "First name",
    lastName: "Last name",
    email: "Email address",
  },
  security: {
    title: "Security",
    description: "Create a strong temporary password for the first sign-in.",
    password: "Password",
  },
  contactInfo: {
    title: "Contact Info",
    description: "Optional details for internal records and support handoffs.",
    dob: "Date of Birth (DOB)",
    phone: "Phone Number",
    phonePlaceholder: "+1 (555) 000-0000",
    address: "Address",
    addressPlaceholder: "123 Main Street, Suite 100",
  },
  permissions: {
    title: "Owner Permissions",
    description: "Owner-controlled visibility for financial and revenue analytics.",
    monetaryTitle: "Monetary analytics",
    monetaryDescription: "Allow this Super Admin to open revenue, payments, dues, transactions, and payment method analytics.",
    ownerOnly: "Only the owner account can change this permission.",
  },
  saving: "Saving...",
  saveAccount: "Save Account",
  cancel: "Cancel",
  errors: {
    load: "Failed to load account.",
    uploadImage: "Failed to upload image.",
    save: "Failed to save account.",
  },
} as const;
