export const moduleEditorStrings = {
  typeLabels: {
    reading: "Reading",
    speaking: "Speaking",
    writing: "Writing",
    listening: "Listening",
    full_mock: "Full Mock Test",
    final_test: "Final Test",
  },
  questionLabels: {
    mcq_single: "MCQ — one answer",
    mcq_multiple: "MCQ — multiple answers",
    true_false_not_given: "True / False / Not Given",
    yes_no_not_given: "Yes / No / Not Given",
    short_answer: "Short answer",
    fill_blank: "Fill in the blank",
    matching_unique: "Match once (six from eight)",
    matching_reusable: "Match reusable source (A-D)",
    essay: "Writing task",
    speaking_prompt: "Speaking prompt",
  },
  unknownType: {
    title: "Unknown module type",
    backLink: "Choose a valid module",
  },
  newModule: {
    subtitle: "The correct parts, timing, marks and assessment rubric will be created automatically.",
    allModulesLink: "All modules",
    titleLabel: "Module title",
    titlePlaceholder: (type: string) => `${type} — Academic Set 1`,
    descriptionLabel: "Description",
    descriptionPlaceholder: "What this module covers",
    instructionsLabel: "Candidate instructions",
    instructionsPlaceholder: "Optional instructions shown before the assessment starts",
    compositeHeading: "Choose completed source tests",
    compositeDescription: (type: string) =>
      `The system makes an independent, order-preserving copy of all four tests. Deleting or editing a source later will not change this ${type}.`,
    loadingSources: "Loading your completed tests...",
    selectCompleted: (type: string) => `Select completed ${type}`,
    sourceOption: (title: string, count: number, status: string) => `${title} · ${count} questions · ${status}`,
    searchSourcePlaceholder: (type: string) => `Search ${type} modules...`,
    noCompleted: (type: string) => `No completed ${type} test is available.`,
    createOneFirst: "Create one first",
    creating: "Creating test copy...",
    create: (type: string) => `Create ${type}`,
    validation: "Choose one completed Listening, Reading, Writing, and Speaking module.",
    errors: {
      create: "Failed to create the module.",
    },
    calculatedDurationLabel: "Calculated exam duration",
    calculatedSpeakingDurationHint: "The duration updates automatically from the preparation and recording time of the Speaking prompts you add.",
    calculatedCompositeDurationHint: "The duration is the total of the four selected source modules.",
    shuffle: "Shuffle",
    shuffleTitle: "Randomly pick unused source modules for each section",
    shuffleExhaustedWarning: (sections: string) =>
      `No unique modules left for: ${sections}. All available modules for these sections are already used in existing mock tests — the best available option has been selected instead.`,
    shuffleExhaustedSectionHint: "All modules for this section are already used in an existing mock test. You may still pick any available module below.",
  },
  loading: "Loading...",
  notFound: "Module not found.",
  backToModules: "Back to modules",
  meta: (minutes: number, parts: number, questions: number, version: string) =>
    `${minutes} minutes · ${parts} parts · ${questions} questions · ${version}`,
  readiness: {
    readyTitle: "Ready to publish",
    notReadyTitle: "Publishing checklist",
    readyDescription: "Every required part, mark and audio rule is satisfied.",
    notReadyDescription: "You can work in any order. These checks are enforced only when publishing.",
    ready: "Ready",
    needsWork: "Needs work",
    publish: "Publish module",
    returnToDraft: "Return to draft",
    archive: "Archive",
    restoreAsDraft: "Restore as draft",
  },
  details: {
    heading: "Module details",
    description: "Set the candidate-facing details and the overall time allowed for this test.",
    titleLabel: "Title",
    descriptionLabel: "Description",
    instructionsLabel: "Candidate instructions",
    durationLabel: "Overall test time (minutes)",
    durationHint: "This countdown applies to the complete module, including every part.",
    calculatedDurationHint: "Calculated automatically from the configured Speaking prompts or selected source modules.",
    save: "Save details",
    deleteDraft: "Delete draft",
    working: "Working...",
    errors: {
      load: "Failed to load this module.",
      save: "Failed to save module details.",
      delete: "Failed to delete the module.",
    },
    notices: {
      saved: "Module details saved.",
      published: "Module published.",
      movedTo: (status: string) => `Module moved to ${status}.`,
      statusError: "The module status could not be changed.",
    },
    deleteConfirm: (title: string) =>
      `Are you sure you want to permanently delete "${title}" and all of its questions and audio? Existing Full/Final Mock copies will not be affected.`,
    deleteConfirmTitle: "Delete Module",
  },
  gapTask: {
    eyebrow: "Gapped passage task",
    heading: (partTitle: string) => partTitle,
    description: (gaps: number, options: number) =>
      `A passage with ${gaps} gaps and ${options} options. The candidate drops an option into each gap and scores a mark per correct gap — ${gaps} marks in total.`,
    helpTitle: "How the gaps work",
    help:
      "Place {{blank:1}}, {{blank:2}} and so on in the passage where each gap belongs. The candidate sees the passage with those gaps inline and picks an option for each one. Extra options are distractors.",
    passageLabel: "Passage with gap markers",
    passagePlaceholder: "Paste the passage and put {{blank:1}}, {{blank:2}} ... where the gaps belong.",
    optionsHeading: (count: number) => `Option bank (${count})`,
    optionPlaceholder: (key: string) => `Text for option ${key}`,
    addOption: "Add option",
    answersHeading: "Correct option for each gap",
    gapLabel: (gap: number) => `Gap ${gap}`,
    noGaps: "No gap markers found yet. Add {{blank:1}} to the passage above.",
    createNotice: (gaps: number) => `Saves as ${gaps} scorable gap${gaps === 1 ? "" : "s"}, 1 mark each.`,
    replaceNotice: (existing: number) =>
      `Rebuilds this task, replacing the ${existing} item${existing === 1 ? "" : "s"} currently saved.`,
    create: (gaps: number) => `Save task (${gaps} gaps)`,
    replace: (gaps: number) => `Rebuild task (${gaps} gaps)`,
    saving: "Saving...",
    saved: (gaps: number) => `Task saved — ${gaps} gaps, ${gaps} marks.`,
    error: "Failed to save the gap task.",
    replaceConfirm: (existing: number) =>
      `This rebuilds the task from the passage above, replacing the ${existing} item${existing === 1 ? "" : "s"} currently saved. Continue?`,
    replaceConfirmTitle: "Rebuild gap questions",
    errors: {
      noPassage: "Add the passage.",
      gapCount: (found: number, expected: number) =>
        `Found ${found} gap marker${found === 1 ? "" : "s"}; this part needs ${expected}.`,
      gapSequence: "Gap markers must be numbered 1, 2, 3 ... with no gaps in the sequence.",
      optionCount: (found: number, expected: number) => `Filled ${found} of ${expected} options.`,
      missingAnswers: (missing: number) => `Choose the correct option for ${missing} more gap${missing === 1 ? "" : "s"}.`,
      duplicateAnswers: "Each option may be the answer for only one gap in this part.",
    },
  },
  notepadTask: {
    eyebrow: "Notepad task",
    heading: (partTitle: string) => `${partTitle} — one notepad, one mark per blank`,
    helpTitle: "How the notepad works",
    help:
      "Write the notepad exactly as the candidate sees it — a heading on the first line, then one note per line. Put {{blank:1}}, {{blank:2}} and so on where each answer belongs. Lines without a marker are shown as context.",
    notepadLabel: "Notepad text",
    notepadPlaceholder:
      "The Father of Alternating Current\n\nNikola Tesla, widely regarded as the father of alternating current, was an inventor whose discoveries changed the way electricity is generated.\nTesla's mother, despite her lack of formal schooling, was behind his early instinct for {{blank:1}}.\nDuring his engineering studies, Tesla was introduced to an electrical principle where the direction of current {{blank:2}} repeatedly.",
    answersHeading: "Answer for each blank",
    blankLabel: (blank: number) => `Blank ${blank}`,
    answerPlaceholder: "Accepted answer",
    noBlanks: "No blank markers found yet. Add {{blank:1}} to the notepad above.",
    saving: "Saving...",
    saved: (gaps: number) => `Notepad task saved successfully (${gaps} blanks).`,
    error: "Failed to save the notepad task.",
    errors: {
      noNotepad: "Write the notepad text.",
      blankCount: (found: number, expected: number) =>
        `Found ${found} blank marker${found === 1 ? "" : "s"}; this part needs ${expected}.`,
      blankSequence: "Blank markers must be numbered 1, 2, 3 ... with no gaps in the sequence.",
      missingAnswers: (missing: number) => `Add the answer for ${missing} more blank${missing === 1 ? "" : "s"}.`,
      answerTooLong: (blank: number, maxWords: number) =>
        `The answer for blank ${blank} is longer than ${maxWords} word${maxWords === 1 ? "" : "s"}.`,
    },
  },
  sourceTextTask: {
    eyebrow: "Source-text matching task",
    heading: (partTitle: string) => `${partTitle} — match statements to source texts`,
    description: (texts: number, questions: number) =>
      `${texts} source texts and ${questions} statements. The candidate drags a text onto each statement and scores a mark per correct statement.`,
    helpTitle: "How the matching works",
    help:
      "Each source text below becomes a draggable card. A statement takes one text, and the same text may answer several statements.",
    helpMulti:
      "Each source text below becomes a draggable card. A statement usually takes one text, and the same text may answer several statements. Selecting two or more texts for a statement makes it a multi-answer item — those are marked on an exact match, so a candidate who gets one of two right scores nothing for it.",
    textsHeading: (count: number) => `Source texts (${count})`,
    textPlaceholder: (key: string) => `Full text for source ${key}`,
    addText: "Add source text",
    questionsHeading: (count: number) => `Statements (${count})`,
    questionPlaceholder: "In which text does the writer ...?",
    questionLabel: (index: number) => `Statement ${index}`,
    removeQuestion: (index: number) => `Remove statement ${index}`,
    addQuestion: "Add statement",
    answerFor: (index: number) => `Correct source text for statement ${index}`,
    multiNote: "Multi-answer — exact match, no partial credit",
    multiUnavailable:
      "Selecting a second text is disabled for this part. Run the pending database migration (alembic upgrade head) to enable multi-answer statements here.",
    createNotice: (count: number) => `Saves ${count} statement${count === 1 ? "" : "s"}, 1 mark each.`,
    replaceNotice: (existing: number) =>
      `Rebuilds this task, replacing the ${existing} statement${existing === 1 ? "" : "s"} currently saved.`,
    create: "Save task",
    replace: "Rebuild task",
    saving: "Saving...",
    saved: (count: number) => `Task saved — ${count} statements.`,
    error: "Failed to save the matching task.",
    replaceConfirm: (existing: number) =>
      `This rebuilds the task, replacing the ${existing} statement${existing === 1 ? "" : "s"} currently saved. Continue?`,
    replaceConfirmTitle: "Rebuild matching task",
    errors: {
      textCount: (found: number, expected: number) => `Filled ${found} of ${expected} source texts.`,
      questionCount: (found: number, expected: number) =>
        `Written ${found} of ${expected} statements.`,
      missingAnswers: (count: number) =>
        `Choose the correct source text for ${count} more statement${count === 1 ? "" : "s"}.`,
    },
  },
  sharedPassage: {
    eyebrow: "Shared source text",
    heading: (partTitle: string) => `Source text for ${partTitle}`,
    description: "Enter the passage once. It will apply to all questions in this part.",
    placeholder: "Paste the reading passage or source material for this part...",
    save: "Save source text",
    saving: "Saving...",
    statusApplied: (count: number) => `Applied to ${count} question${count === 1 ? "" : "s"} in this part.`,
    statusNoQuestions: "Saved with the part. Questions you add will use this text.",
    statusMismatch: "Questions in this part currently have different source texts. Save to make them match.",
    saved: (partTitle: string) => `${partTitle} source text saved.`,
    error: "Failed to save the source text for this part.",
  },
  speakingTiming: {
    eyebrow: "Candidate timing",
    heading: (partTitle: string) => `Timing for ${partTitle}`,
    description: "Set how long the candidate prepares and records for each prompt in this Speaking part.",
    preparationLabel: "Preparation time",
    responseLabel: "Recording time",
    hint: "The recording begins automatically after preparation and stops at the response limit.",
    save: "Save part timing",
    saving: "Saving...",
    saved: (partTitle: string) => `${partTitle} timing saved.`,
    error: "Failed to save the Speaking part timing.",
  },
  examinerPicker: {
    title: "Examiner voice",
    hint: "Chosen once for this module. Every speaking prompt is previewed in this examiner's voice.",
    label: "Select the examiner voice for this module",
    sample: "Sample",
    preparingSample: "Preparing...",
    samplePrompt: (name: string) => `Hello, I am ${name}. This is the voice candidates will hear during the Speaking test.`,
    playSample: (name: string) => `Play a sample of ${name}'s voice`,
    sampleError: "Failed to play the examiner sample.",
  },
  avatarPreview: {
    title: "Examiner avatar preview",
    defaultExaminer: "Language CERT Senior Examiner",
    hint: "Play the question in the examiner voice to check it before saving.",
    generate: "Play examiner preview",
    generating: "Preparing examiner audio...",
    replay: "Play again",
    regenerate: "Rebuild audio",
    stop: "Stop",
    speaking: "Examiner speaking...",
    ready: "Preview ready - this is exactly what the candidate will hear.",
    stale: "The question changed. Play the preview again to hear the new wording.",
    error: "Failed to generate the examiner preview.",
  },
  partNav: {
    heading: "Assessment parts",
    hint: "Select a part before adding or uploading anything.",
    autoMarked: "auto-marked",
    examinerMarked: "examiner-marked",
    aiEnabled: "AI evaluation",
    manualOnly: "manual only",
  },
  partSpec: {
    formatPrefix: "Format:",
    autoMarked: "Auto-marked",
    examinerMarked: "Examiner-marked",
    aiEvaluation: "AI evaluation",
    aiEvaluationOn: "Enabled",
    aiEvaluationOff: "Manual only",
    aiEvaluationHint: "When enabled, submitted answers are sent to the configured evaluator before the instructor queue.",
    aiEvaluationUnavailable: "Only examiner-marked Writing and Speaking parts can use AI evaluation.",
    aiEvaluationSaved: (partTitle: string, enabled: boolean) => `${partTitle} AI evaluation ${enabled ? "enabled" : "disabled"}.`,
    aiEvaluationError: "Failed to update AI evaluation for this part.",
    instructionsLabel: "Heading shown to students",
    instructionsPlaceholder: "e.g. Read each sentence. Choose the word that can best replace the bold word without changing the meaning.",
    instructionsEdit: "Edit heading",
    instructionsSave: "Save heading",
    instructionsCancel: "Cancel",
    instructionsEmpty: "No heading set yet — students will see a generic instruction.",
    instructionsSaved: (partTitle: string) => `${partTitle} heading updated.`,
    instructionsError: "Failed to update the heading for this part.",
    rawMarks: (marks: string) => `${marks} raw marks`,
    audioPlays: (count: number) => `Audio plays ${count}×`,
    minimumWords: (count: number) => `Minimum ${count} words`,
    maximumWords: (count: number) => `Maximum ${count} words`,
    rubricSummary: (count: number) => `Assessment criteria — ${count} × 8 marks`,
    marksRange: (max: number) => `0–${max}`,
    questionsCount: (count: number, limit?: number | null) => limit ? `${count} of ${limit} questions` : `${count} questions`,
  },
  listeningAudio: {
    eyebrow: "Required listening media",
    heading: (partTitle: string) => `Audio for ${partTitle}`,
    description: "Upload an existing MP3 or save a transcript for narration on the student's device.",
    uploadHeading: "Upload MP3",
    audioTitleLabel: "Audio title",
    fileLabel: "MP3 file",
    attach: "Attach MP3 to this part",
    generateHeading: "Browser-narrated transcript",
    conversationLabel: "Conversation or transcript",
    conversationPlaceholder: "Interviewer: Welcome to today's discussion.\nStudent: Thank you. I am glad to be here.\nInterviewer: Let us begin.",
    conversationHint: "Put every person's name before their lines, for example ",
    speakerExampleA: "Speaker A:",
    speakerExampleOr: " or ",
    speakerExampleB: "Sarah:",
    conversationHintSuffix: ". Reuse the same name to keep the same voice.",
    speakersDetected: (count: number) => `${count} speaker${count === 1 ? "" : "s"} detected`,
    waitingForConversation: "Waiting for conversation",
    voicesAutomatic: "English system voices will be assigned automatically during the test.",
    tooManySpeakers: "Use no more than six distinct speakers.",
    rateLabel: "Speaking rate",
    rateSlower: "Slower",
    rateNormal: "Normal",
    rateFaster: "Faster",
    savingNarration: "Saving transcript...",
    saveNarration: "Save browser narration",
    working: "Working...",
    noAudio: "No listening media attached to this part yet.",
    browserNarration: (voice: string, rate: string) => `Browser narration · ${voice} · ${rate}`,
    legacyGeneratedVoice: (voice: string) => `Legacy generated audio · ${voice}`,
    generatedOnStudentDevice: "Speech is generated by the student's browser when the test is played. No MP3 is stored.",
    transcript: "Transcript",
    delete: "Delete",
    errors: {
      upload: "Failed to upload the MP3.",
      generate: "The browser narration transcript could not be saved.",
      delete: "Failed to delete the audio.",
    },
    notices: {
      uploaded: (partTitle: string) => `MP3 attached to ${partTitle}.`,
      generated: (voice: string, partTitle: string) => `${voice || "English system voices"} narration saved for ${partTitle}.`,
    },
  },
  manualQuestion: {
    eyebrow: "Single entry",
    editHeading: "Edit question",
    addHeading: (partTitle: string) => `Add to ${partTitle}`,
    partFullHeading: (partTitle: string) => `${partTitle} is complete`,
    partFullBody: (limit: number) =>
      `This part takes exactly ${limit} question${limit === 1 ? "" : "s"} and they are all added. ` +
      "Edit or delete one below to make room for a different question.",
    typeLabel: "Question type",
    typeSummaryLabel: "Creating question type",
    typeSummaryHint: (partTitle: string) => `This is set by ${partTitle}, so the question stays in the correct LanguageCert format.`,
    blankHelpTitle: "How blanks work",
    blankHelp:
      "For one blank, place {{blank}} exactly where the answer belongs. For source-material matching blanks, place {{blank:1}}, {{blank:2}} and so on in the passage; each marker connects to the matching question in order.",
    blankHelpSharedCloze:
      "Paste the full passage once, on every question in this part, with {{blank:1}}, {{blank:2}} and so on marking each gap in order. Each numbered gap then gets its own 3 options below — add question 1 for gap {{blank:1}}, question 2 for gap {{blank:2}}, and so on.",
    addImage: "Add image",
    uploadingImage: "Uploading...",
    changeImage: "Change image",
    removeImage: "Remove image",
    imagePreviewAlt: "Uploaded question visual",
    promptLabel: "Question or task prompt",
    promptPlaceholder: "Enter the candidate-facing prompt",
    inlinePromptPlaceholder: "Enter the notepad line and place {{blank}} where the answer belongs",
    boldSelectionLabel: "Bold",
    boldSelectionHint: "Select the word in the sentence, then click Bold to highlight it for students.",
    groupLabel: "Conversation group",
    turnTypeLabel: "Speaking turn",
    preparationSecondsLabel: "Preparation time",
    responseSecondsLabel: "Response time",
    adaptiveFollowUpLabel: "Generate this follow-up from the previous response",
    optionsLegend: "Options and correct answer",
    addOption: "Add option",
    removeOption: (key: string) => `Remove option ${key}`,
    minimumOptions: "Keep at least two options.",
    acceptedAnswersLabel: "Accepted answer(s)",
    acceptedAnswersPlaceholder: "Separate alternatives with commas",
    pointsLabel: "Raw marks",
    difficultyLabel: "Difficulty",
    difficultyEasy: "Easy",
    difficultyMedium: "Medium",
    difficultyHard: "Hard",
    explanationLabel: "Marking note or answer explanation",
    updateQuestion: "Update question",
    addQuestion: "Add question",
    cancel: "Cancel",
    errors: {
      save: "Failed to save the question.",
      delete: "Failed to delete the question.",
      imageUpload: "Failed to upload the image.",
      boldRequired: "Please bold at least 1 word in the question prompt (select the word and click Bold).",
    },
    notices: {
      updated: "Question updated.",
      added: (partTitle: string) => `Question added to ${partTitle}.`,
    },
    deleteConfirm: "Are you sure you want to delete this question?",
    deleteConfirmTitle: "Delete Question",
  },
  bulkImport: {
    eyebrow: "Bulk import",
    heading: (partTitle: string) => `PDF or CSV → ${partTitle}`,
    hint: (moduleTitle: string, partTitle: string) =>
      `This upload is permanently scoped to ${moduleTitle} / ${partTitle}. Extracted content is listed for review before saving.`,
    extract: "Extract & review",
    extracting: "Extracting...",
    errors: {
      preview: "Could not extract questions from this file.",
      commit: "Review the extracted questions and try again.",
      selectOne: "Select at least one extracted question.",
      tooMany: (selected: number, remaining: number, partTitle: string) =>
        `You selected ${selected} questions but ${partTitle} has room for ${remaining === 0 ? "no more" : `only ${remaining}`}. ` +
        "Deselect the extras before importing.",
    },
    notices: {
      imported: (count: number, partTitle: string) => `${count} questions imported into ${partTitle}.`,
    },
  },
  importReview: {
    heading: "Review extracted content",
    summary: (count: number, filename: string, moduleTitle: string, partTitle: string) =>
      `${count} detected from ${filename} → ${moduleTitle} / ${partTitle}`,
    selectAll: "Select all",
    deselectAll: "Deselect all",
    discard: "Discard",
    import: (count: number) => `Import ${count} selected`,
    warningsHeading: "Extraction warnings",
    sourceTextSummary: "List extracted file text",
    includeItem: (index: number) => `Include item ${index}`,
    typeLabel: "Question type",
    typeAriaLabel: (index: number) => `Question ${index} type`,
    promptLabel: "Extracted question or prompt",
    answerKeysLabel: "Correct answer key(s)",
  },
  savedQuestions: {
    heading: (partTitle: string) => `Saved content — ${partTitle}`,
    gapHeading: (partTitle: string) => `Saved task — ${partTitle}`,
    gapDescription: (count: number) =>
      `${count} gap${count === 1 ? "" : "s"} in this task · ${count} mark${count === 1 ? "" : "s"}. Edit them in the composer above.`,
    /* There is no pool: a part holds exactly the questions the student sits,
       in the order shown here. */
    description: (count: number, limit?: number | null) => {
      if (!limit) return `${count} saved questions`;
      return count === limit
        ? `All ${limit} question${limit === 1 ? "" : "s"} added. Students see them in the order below.`
        : `${count} of ${limit} question${limit === 1 ? "" : "s"} added. Add ${limit - count} more to complete this part.`;
    },
    emptyTitle: "No content yet",
    emptyDescription: "Add one item manually or upload a PDF/CSV specifically to this part.",
    marksSuffix: (points: number) => `mark${points === 1 ? "" : "s"}`,
    edit: "Edit",
    delete: "Delete",
  },
} as const;
