export const moduleEditorStrings = {
  typeLabels: {
    reading: "Reading",
    speaking: "Speaking",
    writing: "Writing",
    listening: "Listening",
    full_mock: "Full Mock Test",
    final_test: "Final Test",
  },
  questionLabels: {
    mcq_single: "MCQ — one answer",
    mcq_multiple: "MCQ — multiple answers",
    true_false_not_given: "True / False / Not Given",
    yes_no_not_given: "Yes / No / Not Given",
    short_answer: "Short answer",
    fill_blank: "Fill in the blank",
    matching_unique: "Match once (six from eight)",
    matching_reusable: "Match reusable source (A-D)",
    essay: "Writing task",
    speaking_prompt: "Speaking prompt",
  },
  unknownType: {
    title: "Unknown module type",
    backLink: "Choose a valid module",
  },
  newModule: {
    subtitle: "The correct parts, timing, marks and assessment rubric will be created automatically.",
    allModulesLink: "All modules",
    titleLabel: "Module title",
    titlePlaceholder: (type: string) => `${type} — Academic Set 1`,
    descriptionLabel: "Description",
    descriptionPlaceholder: "What this module covers",
    instructionsLabel: "Candidate instructions",
    instructionsPlaceholder: "Optional instructions shown before the assessment starts",
    compositeHeading: "Choose completed source tests",
    compositeDescription: (type: string) =>
      `The system makes an independent, order-preserving copy of all four tests. Deleting or editing a source later will not change this ${type}.`,
    loadingSources: "Loading your completed tests...",
    selectCompleted: (type: string) => `Select completed ${type}`,
    sourceOption: (title: string, count: number, status: string) => `${title} · ${count} questions · ${status}`,
    searchSourcePlaceholder: (type: string) => `Search ${type} modules...`,
    noCompleted: (type: string) => `No completed ${type} test is available.`,
    createOneFirst: "Create one first",
    creating: "Creating test copy...",
    create: (type: string) => `Create ${type}`,
    validation: "Choose one completed Listening, Reading, Writing, and Speaking module.",
    errors: {
      create: "Failed to create the module.",
    },
  },
  loading: "Loading...",
  notFound: "Module not found.",
  backToModules: "Back to modules",
  meta: (minutes: number, parts: number, questions: number, version: string) =>
    `${minutes} minutes · ${parts} parts · ${questions} questions · ${version}`,
  readiness: {
    readyTitle: "Ready to publish",
    notReadyTitle: "Publishing checklist",
    readyDescription: "Every required part, mark and audio rule is satisfied.",
    notReadyDescription: "You can work in any order. These checks are enforced only when publishing.",
    ready: "Ready",
    needsWork: "Needs work",
    publish: "Publish module",
    returnToDraft: "Return to draft",
    archive: "Archive",
    restoreAsDraft: "Restore as draft",
  },
  details: {
    heading: "Module details",
    description: "Set the candidate-facing details and the overall time allowed for this test.",
    titleLabel: "Title",
    descriptionLabel: "Description",
    instructionsLabel: "Candidate instructions",
    durationLabel: "Overall test time (minutes)",
    durationHint: "This countdown applies to the complete module, including every part.",
    save: "Save details",
    deleteDraft: "Delete draft",
    working: "Working...",
    errors: {
      load: "Failed to load this module.",
      save: "Failed to save module details.",
      delete: "Failed to delete the module.",
    },
    notices: {
      saved: "Module details saved.",
      published: "Module published.",
      movedTo: (status: string) => `Module moved to ${status}.`,
      statusError: "The module status could not be changed.",
    },
    deleteConfirm: (title: string) =>
      `Are you sure you want to permanently delete "${title}" and all of its questions and audio? Existing Full/Final Mock copies will not be affected.`,
    deleteConfirmTitle: "Delete Module",
  },
  speakingTiming: {
    eyebrow: "Candidate timing",
    heading: (partTitle: string) => `Timing for ${partTitle}`,
    description: "Set how long the candidate prepares and records for each prompt in this Speaking part.",
    preparationLabel: "Preparation time (seconds)",
    responseLabel: "Recording time (seconds)",
    hint: "The recording begins automatically after preparation and stops at the response limit.",
    save: "Save part timing",
    saving: "Saving...",
    saved: (partTitle: string) => `${partTitle} timing saved.`,
    error: "Failed to save the Speaking part timing.",
  },
  partNav: {
    heading: "Assessment parts",
    hint: "Select a part before adding or uploading anything.",
    autoMarked: "auto-marked",
    examinerMarked: "examiner-marked",
    aiEnabled: "AI evaluation",
    manualOnly: "manual only",
  },
  partSpec: {
    formatPrefix: "Format:",
    autoMarked: "Auto-marked",
    examinerMarked: "Examiner-marked",
    aiEvaluation: "AI evaluation",
    aiEvaluationOn: "Enabled",
    aiEvaluationOff: "Manual only",
    aiEvaluationHint: "When enabled, submitted answers are sent to the configured evaluator before the instructor queue.",
    aiEvaluationUnavailable: "Only examiner-marked Writing and Speaking parts can use AI evaluation.",
    aiEvaluationSaved: (partTitle: string, enabled: boolean) => `${partTitle} AI evaluation ${enabled ? "enabled" : "disabled"}.`,
    aiEvaluationError: "Failed to update AI evaluation for this part.",
    rawMarks: (marks: string) => `${marks} raw marks`,
    audioPlays: (count: number) => `Audio plays ${count}×`,
    minimumWords: (count: number) => `Minimum ${count} words`,
    maximumWords: (count: number) => `Maximum ${count} words`,
    rubricSummary: (count: number) => `Assessment criteria — ${count} × 8 marks`,
    marksRange: (max: number) => `0–${max}`,
    questionsCount: (count: number, limit?: number | null) => limit ? `${count} in pool · draws ${limit}` : `${count} questions`,
  },
  listeningAudio: {
    eyebrow: "Required listening media",
    heading: (partTitle: string) => `Audio for ${partTitle}`,
    description: "Upload an existing MP3 or save a transcript for narration on the student's device.",
    uploadHeading: "Upload MP3",
    audioTitleLabel: "Audio title",
    fileLabel: "MP3 file",
    attach: "Attach MP3 to this part",
    generateHeading: "Browser-narrated transcript",
    conversationLabel: "Conversation or transcript",
    conversationPlaceholder: "Interviewer: Welcome to today's discussion.\nStudent: Thank you. I am glad to be here.\nInterviewer: Let us begin.",
    conversationHint: "Put every person's name before their lines, for example ",
    speakerExampleA: "Speaker A:",
    speakerExampleOr: " or ",
    speakerExampleB: "Sarah:",
    conversationHintSuffix: ". Reuse the same name to keep the same voice.",
    speakersDetected: (count: number) => `${count} speaker${count === 1 ? "" : "s"} detected`,
    waitingForConversation: "Waiting for conversation",
    voicesAutomatic: "English system voices will be assigned automatically during the test.",
    tooManySpeakers: "Use no more than six distinct speakers.",
    rateLabel: "Speaking rate",
    rateSlower: "Slower",
    rateNormal: "Normal",
    rateFaster: "Faster",
    savingNarration: "Saving transcript...",
    saveNarration: "Save browser narration",
    working: "Working...",
    noAudio: "No listening media attached to this part yet.",
    browserNarration: (voice: string, rate: string) => `Browser narration · ${voice} · ${rate}`,
    legacyGeneratedVoice: (voice: string) => `Legacy generated audio · ${voice}`,
    generatedOnStudentDevice: "Speech is generated by the student's browser when the test is played. No MP3 is stored.",
    transcript: "Transcript",
    delete: "Delete",
    errors: {
      upload: "Failed to upload the MP3.",
      generate: "The browser narration transcript could not be saved.",
      delete: "Failed to delete the audio.",
    },
    notices: {
      uploaded: (partTitle: string) => `MP3 attached to ${partTitle}.`,
      generated: (voice: string, partTitle: string) => `${voice || "English system voices"} narration saved for ${partTitle}.`,
    },
  },
  manualQuestion: {
    eyebrow: "Single entry",
    editHeading: "Edit question",
    addHeading: (partTitle: string) => `Add to ${partTitle}`,
    typeLabel: "Question type",
    typeSummaryLabel: "Creating question type",
    typeSummaryHint: (partTitle: string) => `This is set by ${partTitle}, so the question stays in the correct LanguageCert format.`,
    blankHelpTitle: "How blanks work",
    blankHelp:
      "For one blank, place {{blank}} exactly where the answer belongs. For source-material matching blanks, place {{blank:1}}, {{blank:2}} and so on in the passage; each marker connects to the matching question in order.",
    passageLabel: "Passage or context",
    passagePlaceholder: "Optional passage, transcript context, visual description, or role-play setup",
    addImage: "Add image",
    uploadingImage: "Uploading...",
    changeImage: "Change image",
    removeImage: "Remove image",
    imagePreviewAlt: "Uploaded question visual",
    promptLabel: "Question or task prompt",
    promptPlaceholder: "Enter the candidate-facing prompt",
    inlinePromptPlaceholder: "Enter the notepad line and place {{blank}} where the answer belongs",
    instructionsLabel: "Prompt instructions",
    groupLabel: "Conversation group",
    turnTypeLabel: "Speaking turn",
    preparationSecondsLabel: "Preparation seconds",
    responseSecondsLabel: "Response seconds",
    adaptiveFollowUpLabel: "Generate this follow-up from the previous response",
    optionsLegend: "Options and correct answer",
    addOption: "Add option",
    removeOption: (key: string) => `Remove option ${key}`,
    minimumOptions: "Keep at least two options.",
    acceptedAnswersLabel: "Accepted answer(s)",
    acceptedAnswersPlaceholder: "Separate alternatives with commas",
    pointsLabel: "Raw marks",
    difficultyLabel: "Difficulty",
    difficultyEasy: "Easy",
    difficultyMedium: "Medium",
    difficultyHard: "Hard",
    explanationLabel: "Marking note or answer explanation",
    updateQuestion: "Update question",
    addQuestion: "Add question",
    cancel: "Cancel",
    errors: {
      save: "Failed to save the question.",
      delete: "Failed to delete the question.",
      imageUpload: "Failed to upload the image.",
    },
    notices: {
      updated: "Question updated.",
      added: (partTitle: string) => `Question added to ${partTitle}.`,
    },
    deleteConfirm: "Are you sure you want to delete this question?",
    deleteConfirmTitle: "Delete Question",
  },
  bulkImport: {
    eyebrow: "Bulk import",
    heading: (partTitle: string) => `PDF or CSV → ${partTitle}`,
    hint: (moduleTitle: string, partTitle: string) =>
      `This upload is permanently scoped to ${moduleTitle} / ${partTitle}. Extracted content is listed for review before saving.`,
    extract: "Extract & review",
    extracting: "Extracting...",
    errors: {
      preview: "Could not extract questions from this file.",
      commit: "Review the extracted questions and try again.",
      selectOne: "Select at least one extracted question.",
    },
    notices: {
      imported: (count: number, partTitle: string) => `${count} questions imported into ${partTitle}.`,
    },
  },
  importReview: {
    heading: "Review extracted content",
    summary: (count: number, filename: string, moduleTitle: string, partTitle: string) =>
      `${count} detected from ${filename} → ${moduleTitle} / ${partTitle}`,
    selectAll: "Select all",
    deselectAll: "Deselect all",
    discard: "Discard",
    import: (count: number) => `Import ${count} selected`,
    warningsHeading: "Extraction warnings",
    sourceTextSummary: "List extracted file text",
    includeItem: (index: number) => `Include item ${index}`,
    typeLabel: "Question type",
    typeAriaLabel: (index: number) => `Question ${index} type`,
    promptLabel: "Extracted question or prompt",
    answerKeysLabel: "Correct answer key(s)",
  },
  savedQuestions: {
    heading: (partTitle: string) => `Saved content — ${partTitle}`,
    description: (count: number, limit?: number | null) => limit
      ? `${count} questions in the pool. Each attempt draws ${limit} at random.`
      : `${count} saved questions`,
    emptyTitle: "No content yet",
    emptyDescription: "Add one item manually or upload a PDF/CSV specifically to this part.",
    marksSuffix: (points: number) => `mark${points === 1 ? "" : "s"}`,
    edit: "Edit",
    delete: "Delete",
  },
} as const;
