export const instituteOnboardingsStrings = {
  searchPlaceholder: "Search institute name or email...",
  statusFilter: {
    allStatuses: "All statuses",
    published: "Published",
    draft: "Draft",
  },
  exportPdf: "Export PDF",
  exportExcel: "Export Excel",
  onboardInstitute: "Onboard institute",
  loading: "Loading...",
  table: {
    institute: "Institute",
    agreement: "Agreement",
    payment: "Payment",
    allocation: "Allocation",
    courses: "Courses",
    status: "Status",
    actions: "Actions",
    empty: "No institute onboardings found.",
    noContactEmail: "No contact email",
    notRecorded: "Not recorded",
    pending: "pending",
    studentsStaffSuffix: (students: number, staff: number) => `${students} students / ${staff} staff`,
    accountsIssuedSuffix: (count: number) => `${count} accounts issued`,
    continueOnboarding: "Continue Onboarding",
    viewDetails: "View Details",
  },
  pdf: {
    header: "IELTS LMS — Institute Onboarding Report",
    generatedPrefix: "Generated:",
    columns: ["#", "Institute", "Contact Email", "Agreement", "Payment", "Allocation", "Courses", "Status"],
    notRecorded: "Not recorded",
  },
  excel: {
    sheetName: "Onboardings",
    columns: ["#", "Institute Name", "Contact Email", "Agreed Amount", "Currency", "Payment Paid", "Payment Status", "Student Limit", "Staff Limit", "Issued Accounts", "Courses Count", "Onboarding Status", "Created At"],
  },
} as const;
