export const instituteOnboardingsStrings = {
  searchPlaceholder: "Search institute name or email...",
  statusFilter: {
    allStatuses: "All statuses",
    published: "Published",
    draft: "Draft",
  },
  exportPdf: "Export PDF",
  exportExcel: "Export Excel",
  onboardInstitute: "Onboard institute",
  loading: "Loading...",
  errors: {
    load: "Failed to load institute onboardings.",
    delete: "Failed to delete draft onboarding.",
  },
  table: {
    institute: "Institute",
    agreement: "Agreement",
    payment: "Payment",
    allocation: "Allocation",
    courses: "Courses",
    status: "Status",
    actions: "Actions",
    empty: "No institute onboardings found.",
    noContactEmail: "No contact email",
    notRecorded: "Not recorded",
    pending: "pending",
    studentsStaffSuffix: (students: number, staff: number) => `${students} students / ${staff} staff`,
    accountsIssuedSuffix: (count: number) => `${count} accounts issued`,
    continueOnboarding: "Continue Onboarding",
    viewDetails: "View Details",
    deleteDraft: "Delete Draft",
  },
  deleteModal: {
    title: "Delete draft onboarding",
    message: (name: string) => `Delete the draft onboarding for ${name}? This removes the draft institute, pending payment record, assigned courses, branding, and draft admin account.`,
    confirmText: "Delete Draft",
  },
  pdf: {
    header: "Language CERT — Institute Onboarding Report",
    generatedPrefix: "Generated:",
    columns: ["#", "Institute", "Contact Email", "Agreement", "Payment", "Allocation", "Courses", "Status"],
    notRecorded: "Not recorded",
  },
  excel: {
    sheetName: "Onboardings",
    columns: ["#", "Institute Name", "Contact Email", "Agreed Amount", "Currency", "Payment Paid", "Payment Status", "Student Limit", "Staff Limit", "Issued Accounts", "Courses Count", "Onboarding Status", "Created At"],
  },
} as const;
