export const instituteFormStrings = {
  breadcrumbInstitutes: "Institutes",
  newTitle: "New Institute",
  editTitlePrefix: "Edit",
  editTitleFallback: "Edit Institute",
  loading: "Loading...",
  accounts: "Accounts",
  branding: "Branding",
  nameLabel: "Institute name",
  contactEmailLabel: "Contact email",
  contactEmailPlaceholder: "Optional",
  firstAdminHeading: "First Institute Admin",
  adminEmailLabel: "Admin email",
  firstNameLabel: "First name",
  lastNameLabel: "Last name",
  passwordHint: "A temporary password is generated automatically and shown once after creation.",
  sessionPolicy: {
    legend: "Session policy",
    description: "Controls how long institute account sessions remain valid after login. Refreshing the page does not extend this limit.",
    lifetimeLabel: "Session lifetime (hours)",
  },
  saving: "Saving...",
  save: "Save",
  cancel: "Cancel",
  /** Multi-step create/edit flow along the top of the form. */
  wizard: {
    previousStep: "Previous Step",
    nextStep: "Next Step",
    createInstitute: "Create Institute",
    savedToast: "Institute saved.",
    selectAllModules: "Select All",
    deselectAllModules: "Deselect All",
    manageAccounts: "Manage Accounts",
  },
  createdModal: {
    heading: "Institute created",
    description: "Share these credentials with the institute admin now — the password won't be shown again. They'll be required to change it on first login.",
    email: "Email",
    temporaryPassword: "Temporary password",
    copyPassword: "Copy password",
    copied: "Copied!",
    allocationToastTitle: "This institute gets",
    done: "Done",
  },
  errors: {
    load: "Failed to load institute.",
    save: "Failed to save institute.",
  },
} as const;
