import type { PermissionKey } from "./types";

export const instituteFormStrings = {
  breadcrumbInstitutes: "Institutes",
  newTitle: "New Institute",
  editTitlePrefix: "Edit",
  editTitleFallback: "Edit Institute",
  loading: "Loading...",
  accounts: "Accounts",
  branding: "Branding",
  nameLabel: "Institute name",
  contactEmailLabel: "Contact email",
  contactEmailPlaceholder: "Optional",
  firstAdminHeading: "First Institute Admin",
  adminEmailLabel: "Admin email",
  firstNameLabel: "First name",
  lastNameLabel: "Last name",
  passwordHint: "A temporary password is generated automatically and shown once after creation.",
  sessionPolicy: {
    legend: "Session policy",
    description: "Controls how long institute account sessions remain valid after login. Refreshing the page does not extend this limit.",
    lifetimeLabel: "Session lifetime (hours)",
  },
  permissions: {
    legend: "Institute Admin permissions",
    description: "Student account creation remains exclusive to the Super Admin.",
    selectAll: "Select all",
  },
  saving: "Saving...",
  save: "Save",
  cancel: "Cancel",
  createdModal: {
    heading: "Institute created",
    description: "Share these credentials with the institute admin now — the password won't be shown again. They'll be required to change it on first login.",
    email: "Email",
    temporaryPassword: "Temporary password",
    copyPassword: "Copy password",
    copied: "Copied!",
    allocationToastTitle: "This institute gets",
    done: "Done",
  },
  errors: {
    load: "Failed to load institute.",
    save: "Failed to save institute.",
  },
  permissionOptions: [
    { key: "view_students" as PermissionKey, label: "View students", description: "See the institute student directory." },
    { key: "manage_students" as PermissionKey, label: "Manage students", description: "Edit, activate, deactivate, and delete student accounts." },
    { key: "view_student_activity" as PermissionKey, label: "View student activity", description: "Review test attempts, grading history, and known devices." },
    { key: "manage_student_sessions" as PermissionKey, label: "Manage student sessions", description: "Revoke a student's active login session." },
    { key: "manage_staff" as PermissionKey, label: "Manage instructors", description: "Create, edit, activate, and deactivate institute instructors." },
    { key: "view_billing" as PermissionKey, label: "View subscription", description: "See the assigned plan, limits, and offline payment history." },
  ],
} as const;
