export const superAdminBlogsStrings = {
  searchPlaceholder: "Search by title, category, or author...",
  statusFilters: ["ALL", "PUBLISHED", "DRAFT"] as const,
  gridViewTitle: "Grid View",
  tableViewTitle: "Table View",
  writeBlogPost: "Write Blog Post",
  loading: "Loading blogs...",
  deleteConfirm: (title: string) => `Are you sure you want to delete the blog post "${title}"? This action cannot be undone.`,
  deleteConfirmTitle: "Delete Blog Post",
  deleteFallbackTitle: "blog post",
  toggleVisibilityConfirm: (title: string, newStatus: string) => `Are you sure you want to change the visibility of "${title}" to ${newStatus}?`,
  toggleVisibilityTitle: "Change Blog Visibility",
  publishLabel: "Publish",
  unpublishLabel: "Unpublish",
  unpublishTooltip: "Unpublish Article",
  publishTooltip: "Publish Article",
  editTooltip: "Edit Article",
  deleteTooltip: "Delete Article",
  minReadSuffix: "min read",
  publishedLabel: "Published",
  draftLabel: "Draft",
  tableHeaders: {
    article: "ARTICLE TITLE & CATEGORY",
    author: "AUTHOR",
    status: "STATUS",
    actions: "ACTIONS",
  },
};
