export const moduleControlDetailStrings = {
  loading: "Loading course details...",
  eyebrow: "Course Control",
  createdBy: "Created by",
  backToCourseTree: "Back to course tree",
  hideFromSite: "Hide from site",
  showOnSite: "Show on site",
  publishCourse: "Publish Course",
  archive: "Archive",
  deleteCourse: "Delete course",
  hidden: "Hidden",
  noDescription: "No description provided.",
  facts: {
    duration: "Duration",
    minutesSuffix: "Minutes",
    parts: "Parts",
    questions: "Questions",
    institutes: "Institutes",
  },
  assignPanel: {
    title: "Assign to institute",
    description: "Grant this published module to an institute.",
    publishFirst: "Publish the course before assigning it to an institute.",
    selectPlaceholder: "Select a published institute...",
    searchPlaceholder: "Type to search institute...",
    emptyMessage: "No available published institutes.",
    granting: "Granting...",
    grantAccess: "Grant access",
  },
  accessTable: {
    title: "Institute access",
    description: "Review active and revoked institute assignments.",
    institute: "Institute",
    assigned: "Assigned",
    status: "Status",
    empty: "Not assigned to any institute yet.",
    active: "Active",
    revoked: "Revoked",
    revokeAccess: "Revoke access",
  },
  confirm: {
    revokeAccess: (moduleTitle: string, instituteName: string) => `Are you sure you want to revoke access to "${moduleTitle}" for ${instituteName}?`,
    revokeAccessTitle: "Revoke Institute Access",
    revokeAccessConfirm: "Revoke access",
    cancel: "Cancel",
    hideCourse: (title: string) => `Are you sure you want to hide "${title}" from the site? Students will no longer see this course.`,
    hideCourseTitle: "Hide Course",
    hideCourseConfirm: "Hide from site",
    makeVisible: (title: string) => `Are you sure you want to publish "${title}" on the public site?`,
    makeVisibleTitle: "Make Course Visible",
    makeVisibleConfirm: "Make visible",
    archiveCourse: (title: string) => `Are you sure you want to archive "${title}"? It will be removed from active listings.`,
    archiveCourseTitle: "Archive Course",
    archiveCourseConfirm: "Archive course",
    publishCourse: (title: string) => `Are you sure you want to publish "${title}"?`,
    publishCourseTitle: "Publish Course",
    publishCourseConfirm: "Publish course",
    deleteCourse: (title: string) => `Are you sure you want to permanently delete "${title}"? Existing attempt history will be retained, but the course will be removed.`,
    deleteCourseTitle: "Delete Course",
  },
  errors: {
    load: "Failed to load course.",
    assign: "Failed to assign course.",
    revoke: "Failed to revoke access.",
    visibility: "Failed to change course visibility.",
    status: "Failed to change course status.",
    delete: "Failed to delete course.",
  },
} as const;
