export const questionBanksStrings = {
  title: "Question Banks",
  subtitle: "Create questions one at a time or extract them from PDF and CSV files.",
  newBank: "New Question Bank",
  searchPlaceholder: "Search question banks...",
  searchAriaLabel: "Search question banks",
  sectionAriaLabel: "IELTS section",
  allSections: "All sections",
  courseAriaLabel: "Course",
  allCourses: "All courses",
  searchCoursesPlaceholder: "Search courses...",
  myBanks: "My banks",
  search: "Search",
  loading: "Loading...",
  empty: {
    title: "No question banks found",
    description: "Create a bank for a course, then add individual questions or import a file.",
    cta: "Create Question Bank",
  },
  noDescription: "No description added.",
  byAuthor: (name: string) => `By ${name}`,
  errors: {
    load: "Failed to load question banks.",
  },
  sectionLabels: {
    listening: "Listening",
    reading: "Reading",
    writing: "Writing",
    speaking: "Speaking",
  },
} as const;
