export const instructorsStrings = {
  passwordNotice: {
    prefix: "Temporary password for",
    copy: "Copy",
    dismiss: "Dismiss",
  },
  searchAriaLabel: "Search instructors",
  searchPlaceholder: "Search name, email, or title...",
  statusFilter: {
    allStatuses: "All statuses",
    active: "Active",
    inactive: "Inactive",
  },
  exportPdf: "Export PDF",
  exportExcel: "Export Excel",
  newInstructor: "+ New Instructor",
  resultCount: {
    showing: "Showing",
    entry: "entry",
    entries: "entries",
  },
  bulkActions: {
    selectedSuffix: "selected",
    activate: "Activate",
    deactivate: "Deactivate",
    delete: "Delete",
    clear: "Clear",
  },
  loading: "Loading...",
  table: {
    instructor: "Instructor",
    status: "Status",
    created: "Created",
    actions: "Actions",
    empty: "No instructors match these filters.",
    resetRequired: "reset required",
    deactivate: "Deactivate Instructor",
    reactivate: "Reactivate Instructor",
    edit: "Edit Instructor",
    resetPassword: "Reset Password",
    delete: "Delete Instructor",
  },
  deleteModal: {
    title: "Delete Instructor",
    message: (email: string) => `Are you sure you want to delete instructor "${email}"? This action cannot be undone.`,
    confirmText: "Delete Instructor",
  },
  deactivateConfirm: (email: string) => `Deactivate ${email}? Their active sessions will be revoked.`,
  resetPasswordConfirm: (email: string) => `Reset the password for ${email}? Their active sessions will be revoked.`,
  bulkDeactivateConfirm: (count: number) => `Deactivate ${count} instructor${count === 1 ? "" : "s"}? Their active sessions will be revoked.`,
  bulkDeleteConfirm: (count: number) => `Are you sure you want to delete ${count} instructor${count === 1 ? "" : "s"}? This action cannot be undone.`,
  bulkDeleteConfirmTitle: "Delete Instructors",
  errors: {
    load: "Failed to load instructors.",
    toggle: (action: string) => `Failed to ${action} instructor.`,
    missingPassword: "Temporary password was not returned by the server. Restart the backend and try Reset Password again.",
    noPasswordToCopy: "No temporary password is available to copy. Try Reset Password again after restarting the backend.",
    resetPassword: "Failed to reset password.",
    delete: "Failed to delete instructor.",
    bulkToggle: (action: string, failed: number, total: number) => `Failed to ${action} ${failed} of ${total} instructors.`,
    bulkDelete: (failed: number, total: number) => `Failed to delete ${failed} of ${total} instructors.`,
  },
  pdf: {
    header: "IELTS LMS — SA Instructors Report",
    columns: ["#", "Instructor Name", "Title & Email", "Status", "Created"],
  },
  excel: {
    sheetName: "SA Instructors",
    columns: ["#", "First Name", "Last Name", "Title", "Email", "Status", "Force Reset", "Created At"],
    yes: "Yes",
    no: "No",
  },
} as const;
