import { type FormEvent, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { API_BASE_URL, apiClient } from "../../api/client";
import { extractErrorMessage } from "../../api/errors";
import type { Course } from "../../api/types";

interface Institute { id: number; name: string; is_active: boolean; subscription_state: string }

export function CourseAssignments() {
  const { id } = useParams(); const [course, setCourse] = useState<Course | null>(null); const [institutes, setInstitutes] = useState<Institute[]>([]); const [selected, setSelected] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function load() { try { const [{ data: courseData }, { data: instituteData }] = await Promise.all([apiClient.get<Course>(`/super-admin/courses/${id}`), apiClient.get<Institute[]>("/super-admin/institutes")]); setCourse(courseData); setInstitutes(instituteData); } catch { setError("Failed to load course assignments."); } }
  useEffect(() => { load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [id]);
  async function assign(event: FormEvent) { event.preventDefault(); if (!selected) return; setSaving(true); setError(null); try { await apiClient.post(`/super-admin/courses/${id}/assignments`, { institute_id: Number(selected) }); setSelected(""); await load(); } catch (err: unknown) { setError(extractErrorMessage(err, "Failed to assign course.")); } finally { setSaving(false); } }
  async function unassign(instituteId: number) { if (!window.confirm("Remove this course from the institute?")) return; try { await apiClient.delete(`/super-admin/courses/${id}/assignments/${instituteId}`); await load(); } catch (err: unknown) { setError(extractErrorMessage(err, "Failed to unassign course.")); } }
  if (!course && !error) return <p>Loading...</p>; if (!course) return <p className="error-text">{error}</p>;
  const activeIds = new Set(course.assignments?.filter((item) => item.is_active).map((item) => item.institute_id)); const available = institutes.filter((item) => item.is_active && !activeIds.has(item.id));
  return <div><div className="page-header"><div><h1>{course.title}</h1><p className="page-subtitle">Catalog oversight and institute assignments.</p></div><Link className="text-link" to="/super-admin/courses">← Course catalog</Link></div>{error && <p className="error-text">{error}</p>}<div className="course-overview"><div><span className={`badge badge-${course.status === "published" ? "green" : course.status === "draft" ? "amber" : "gray"}`}>{course.status}</span><h2>{course.summary || "No summary"}</h2><p>{course.description || "No description provided."}</p></div><dl><div><dt>Instructor</dt><dd>{course.created_by_name}</dd></div><div><dt>Price</dt><dd>{course.currency} {Number(course.price).toLocaleString("en-IN")}</dd></div><div><dt>Level</dt><dd>{course.level.replaceAll("_", " ")}</dd></div><div><dt>Resources</dt><dd>{course.asset_count}</dd></div></dl></div><div className="assignment-grid"><section className="workspace-panel"><h2>Assign to institute</h2>{course.status !== "published" ? <div className="banner warning">The instructor must publish this course before it can be assigned.</div> : <form onSubmit={assign}><label htmlFor="institute">Institute</label><select id="institute" value={selected} onChange={(e) => setSelected(e.target.value)} required><option value="">Select an active institute...</option>{available.map((item) => <option value={item.id} key={item.id}>{item.name} ({item.subscription_state})</option>)}</select><button className="top-gap" type="submit" disabled={saving || !selected}>{saving ? "Assigning..." : "Assign Course"}</button></form>}</section><section className="workspace-panel"><h2>Course resources</h2>{course.assets.length ? <ul className="resource-links">{course.assets.map((asset) => <li key={asset.id}><span className={`asset-icon ${asset.asset_type}`}>{asset.asset_type === "pdf" ? "PDF" : "MP3"}</span><a href={`${API_BASE_URL}${asset.file_url}`} target="_blank" rel="noreferrer">{asset.title}</a></li>)}</ul> : <p className="empty-message">No resources uploaded.</p>}</section></div><h2 className="section-title">Institute history</h2><table className="data-table"><thead><tr><th>Institute</th><th>Assigned</th><th>Status</th><th /></tr></thead><tbody>{!course.assignments?.length ? <tr><td colSpan={4} className="empty-cell">Not assigned to any institute.</td></tr> : course.assignments.map((item) => <tr key={item.id}><td>{item.institute_name}</td><td>{new Date(item.assigned_at).toLocaleDateString()}</td><td><span className={`badge ${item.is_active ? "badge-green" : "badge-gray"}`}>{item.is_active ? "Active" : "Removed"}</span></td><td className="table-actions">{item.is_active && <button className="danger" onClick={() => unassign(item.institute_id)}>Unassign</button>}</td></tr>)}</tbody></table></div>;
}
