export const dashboardLayoutStrings = {
  brandTitle: "Visa House",
  brandSubtitle: "Super Admin",
  notificationEyebrow: "Platform updates",
  menu: {
    mainMenu: "MAIN MENU",
    dashboard: "Dashboard",
    users: "Users",
    usersSuperAdmins: "Super Admins",
    usersSaInstructors: "SA Instructors",
    usersInstituteAdmins: "Institute Admins",
    usersInstituteStaff: "Institute Staff",
    usersStudents: "Students",
    courseControl: "Course Control",
    gradingOversight: "Grading Oversight",
    retakeRequests: "Retake Requests",
    notifications: "Notifications",
    supportTickets: "Support Tickets",
    vouchers: "Vouchers",
    saas: "SaaS",
    saasInstitutes: "Institutes",
    saasOnboarding: "Institute Onboarding",
    saasInstituteSignups: "Institute Applications",
    saasPlans: "Subscription Plans",
    saasSubscriptions: "Access Agreements",
    saasTrial: "Trial Settings",
    saasCoupons: "Coupons",
    saasVouchers: "Voucher Purchase & Stock",
    saasPayments: "Payments",
    saasPaymentMethods: "Payment Methods",
    saasGstRates: "GST Master",
    saasRevenue: "Revenue",
    cmsContent: "CMS & CONTENT",
    testimonials: "Testimonials",
    blogsCms: "Blogs CMS",
    seoSettings: "SEO & Meta Settings",
    instagramFeed: "Instagram Feed",
    settings: "SETTINGS",
    system: "System",
    systemDev: "Platform Settings",
    systemLogs: "Logs",
    systemTerminal: "CMD Terminal",
    myProfile: "My Profile",
    activeSessions: "Active Sessions",
    allSessions: "All Sessions",
    changePassword: "Change Password",
  },
} as const;
