export const dashboardLayoutStrings = {
  brandTitle: "Visa House",
  brandSubtitle: "Super Admin",
  notificationEyebrow: "Platform updates",
  menu: {
    overview: "Overview",
    peopleAccess: "People & Access",
    academics: "Academics",
    billingBusiness: "Billing & Business",
    communication: "Communication",
    dashboard: "Dashboard",
    users: "Users",
    usersSuperAdmins: "Super Admins",
    usersSaInstructors: "SA Instructors",
    usersInstituteAdmins: "Institute Admins",
    usersInstituteStaff: "Institute Staff",
    usersStudents: "Students",
    usersAll: "All Users",
    courseControl: "Course Control",
    gradingOversight: "Grading Oversight",
    retakeRequests: "Retake Requests",
    notifications: "Notifications",
    supportTickets: "Support Tickets",
    vouchers: "Vouchers",
    saasInstitutes: "Institutes",
    saasInstituteSignups: "Institute Applications",
    saasPlans: "Subscription Plans",
    saasSubscriptions: "Access Agreements",
    saasTrial: "Trial Settings",
    saasCoupons: "Coupons",
    saasPayments: "Payments",
    saasPaymentMethods: "Payment Methods",
    saasGstRates: "GST Master",
    saasRevenue: "Revenue",
    cmsContent: "Content",
    testimonials: "Testimonials",
    blogsCms: "Blogs CMS",
    seoSettings: "SEO & Meta Settings",
    instagramFeed: "Instagram Feed",
    systemSection: "System",
    accountSection: "Account",
    systemDev: "Platform Settings",
    systemLogs: "Logs",
    systemTerminal: "CMD Terminal",
    myProfile: "My Profile",
    activeSessions: "Active Sessions",
    allSessions: "All Sessions",
    changePassword: "Change Password",
  },
} as const;
