export const instagramSettingsStrings = {
  heading: "Instagram Feed & Reels Settings",
  subheading:
    "Configure Instagram Graph API integration to showcase recent reels and study tip posts dynamically on your homepage.",
  loading: "Loading Instagram settings...",
  savedBanner: "Instagram settings updated successfully!",
  seedSuccessBanner: "Demo sample reels and posts loaded successfully!",
  fetchSuccessBanner: "Latest Instagram feed refreshed from Meta Graph API!",
  clearSuccessBanner: "All Instagram feed items cleared successfully!",
  deleteSuccessBanner: "Instagram feed item deleted successfully!",
  toggle: {
    enabledLabel: "Instagram Feed is Enabled on Homepage",
    disabledLabel: "Instagram Feed is Disabled on Homepage",
    enabledDesc: "Visitors on the public homepage can view recent Instagram reels, posts, and like counters.",
    disabledDesc: "The Instagram section is completely hidden from the public homepage.",
  },
  credentials: {
    title: "Meta Graph API Credentials",
    tokenLabel: "Long-Lived Access Token",
    tokenPlaceholder: "Enter Instagram Graph API User Access Token (e.g. IGQVJ...)",
    tokenHint: "Generate a User Access Token with 'instagram_graph_user_media' permission in the Meta for Developers portal.",
    tokenConfigured: "Token Configured",
    tokenNotSet: "No Token Set",
    usernameLabel: "Instagram Username / Handle",
    usernamePlaceholder: "e.g. visahouseimmigration",
    usernameHint: "Used for profile link CTA (@username) on the homepage.",
    limitLabel: "Feed Items Limit",
    testConnectionBtn: "Test Connection",
    testConnectionBusy: "Testing...",
    refreshFeedBtn: "Fetch Live Feed",
    refreshFeedBusy: "Fetching...",
  },
  samples: {
    title: "Demo & Test Samples",
    desc: "Instantly populate sample IELTS & LanguageCert reels, student band success stories, and study tips to preview the homepage layout without waiting for API keys.",
    seedBtn: "Populate Sample Reels & Posts",
    seedBusy: "Loading Samples...",
  },
  preview: {
    title: "Live Feed Preview",
    subtitle: "Items currently queued to display in the homepage Instagram showcase.",
    reelsTab: "All Items",
    likes: "likes",
    comments: "comments",
    views: "views",
    empty: "No feed items currently configured. Click 'Populate Sample Reels' to load demo content or connect Meta API.",
    clearBtn: "Clear All Items",
    clearBusy: "Clearing...",
    deleteItem: "Delete Item",
    confirmClear: "Are you sure you want to remove all feed items from the preview and homepage?",
    confirmDelete: "Are you sure you want to delete this feed item?",
  },
  guide: {
    title: "How to connect your Instagram Account",
    step1: "1. Go to developers.facebook.com and create or open your Meta App.",
    step2: "2. Add the Instagram Graph API (or Instagram Basic Display) product.",
    step3: "3. Add your Instagram account as a Test User and generate a User Access Token.",
    step4: "4. Paste the Access Token here and click 'Test Connection'.",
  },
  saveLabel: "Save Configuration",
  saveBusy: "Saving...",
} as const;
