export const invoiceStrings = {
  titlePrefix: "Invoice",
  backToPayments: "Back to Payments",
  downloadPdf: "Download PDF",
  shareLink: "Copy Link",
  emailReceipt: "Email Receipt",
  recordPayment: "Record Payment",
  markAsPaid: "Mark Fully Paid",
  companyName: "Visa House / LanguageCert",
  companySubtitle: "Official SaaS Subscription Invoice & Tax Receipt",
  billedTo: "Billed To",
  directCustomer: "Direct Customer",
  status: "Status",
  paymentDetails: "Payment Information",
  gateway: "Payment Gateway",
  transactionRef: "Transaction Ref",
  issueDate: "Issue Date",
  dueDate: "Due Date",
  timelineTitle: "Payment & Audit History",
  verifiedSeal: "VERIFIED RECEIPT • SHA-256 ENCRYPTED",
  metrics: {
    totalBilled: "Total Invoice Amount",
    amountPaid: "Total Settled",
    balanceDue: "Balance Outstanding",
  },
  table: {
    description: "Description",
    amount: "Amount",
    purchase: "Subscription Purchase",
    discount: "Discount Applied",
    total: "Total Amount",
    amountPaid: "Amount Paid",
    balanceDue: "Balance Due",
  },
  paymentMode: "Payment Mode:",
  fullyPaidOn: "Fully paid on",
  loading: "Loading invoice details...",
  errors: {
    load: "Failed to load invoice details.",
  },
  toasts: {
    copied: "Invoice link copied to clipboard!",
    pdfGenerated: "PDF Invoice generated & downloading...",
    emailSent: "Receipt email sent successfully!",
    paymentRecorded: "Payment recorded successfully!",
  },
  modals: {
    recordPaymentTitle: "Record New Payment",
    recordPaymentDesc: "Enter payment details to update the invoice balance due.",
    amountToPay: "Payment Amount",
    paymentMethod: "Payment Method",
    referenceNotes: "Transaction Ref / Notes",
    confirmRecord: "Submit Payment",
    emailReceiptTitle: "Email Invoice Receipt",
    recipientEmail: "Recipient Email Address",
    customMessage: "Custom Message (Optional)",
    sendEmail: "Send Email Receipt",
    cancel: "Cancel",
  },
} as const;
