import { type FormEvent, useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { apiClient } from "../../api/client";
import { extractErrorMessage } from "../../api/errors";
import type { ExamModule } from "../../api/types";

interface Assignment { id: number; institute_id: number; institute_name: string; is_active: boolean; assigned_at: string }
interface ManagedModule extends ExamModule { assignments: Assignment[] }
interface Institute { id: number; name: string; is_active: boolean; onboarding_status: string }

export function ModuleControlDetail() {
  const { id } = useParams(); const navigate = useNavigate();
  const [module, setModule] = useState<ManagedModule | null>(null); const [institutes, setInstitutes] = useState<Institute[]>([]); const [selected, setSelected] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function load() { const [{ data: moduleData }, { data: instituteData }] = await Promise.all([apiClient.get<ManagedModule>(`/super-admin/modules/${id}`), apiClient.get<Institute[]>("/super-admin/institutes")]); setModule(moduleData); setInstitutes(instituteData); }
  useEffect(() => { load().catch(() => setError("Failed to load course.")); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [id]);
  async function assign(event: FormEvent) { event.preventDefault(); setBusy(true); try { await apiClient.post(`/super-admin/modules/${id}/assignments`, { institute_id: Number(selected) }); setSelected(""); await load(); } catch (err) { setError(extractErrorMessage(err, "Failed to assign course.")); } finally { setBusy(false); } }
  async function revoke(instituteId: number) { if (!window.confirm("Revoke this course from the institute?")) return; await apiClient.delete(`/super-admin/modules/${id}/assignments/${instituteId}`); await load(); }
  async function visibility() { if (!module) return; await apiClient.patch(`/super-admin/modules/${id}/visibility`, { is_visible: !module.is_visible }); await load(); }
  async function status(next: string) { try { await apiClient.post(`/super-admin/modules/${id}/status`, { status: next }); await load(); } catch (err) { setError(extractErrorMessage(err, "Failed to change course status.")); } }
  async function remove() { if (!window.confirm(`Delete "${module?.title}" from the platform? Existing attempt history will be retained.`)) return; await apiClient.delete(`/super-admin/modules/${id}`); navigate("/super-admin/modules"); }
  if (!module) return <p>{error || "Loading..."}</p>;
  const activeIds = new Set(module.assignments.filter((item) => item.is_active).map((item) => item.institute_id)); const available = institutes.filter((item) => item.is_active && item.onboarding_status === "published" && !activeIds.has(item.id));
  return <div><div className="page-header"><div><h1>{module.title}</h1><p className="page-subtitle">Created by {module.created_by_name} on {new Date(module.created_at).toLocaleString()}.</p></div><Link to="/super-admin/modules">Back to course tree</Link></div>{error && <p className="error-text">{error}</p>}<div className="form-actions course-admin-actions"><button onClick={visibility}>{module.is_visible ? "Hide from site" : "Show on site"}</button>{module.status !== "published" && <button onClick={() => status("published")}>Publish</button>}{module.status === "published" && <button className="secondary-button" onClick={() => status("archived")}>Archive</button>}<button className="danger" onClick={remove}>Delete course</button></div><div className="course-overview"><div><span className={`badge ${module.status === "published" ? "badge-green" : module.status === "draft" ? "badge-amber" : "badge-gray"}`}>{module.status}</span>{!module.is_visible && <span className="badge badge-gray">hidden</span>}<h2>{module.module_label}</h2><p>{module.description || "No description."}</p></div><dl><div><dt>Duration</dt><dd>{module.duration_minutes} minutes</dd></div><div><dt>Parts</dt><dd>{module.part_count}</dd></div><div><dt>Questions</dt><dd>{module.question_count}</dd></div><div><dt>Institutes</dt><dd>{module.assignment_count}</dd></div></dl></div><section className="workspace-panel"><h2>Assign to institute</h2>{module.status !== "published" ? <p className="banner warning">Publish the course before assigning it.</p> : <form className="filter-bar" onSubmit={assign}><select value={selected} onChange={(event) => setSelected(event.target.value)} required><option value="">Select a published institute...</option>{available.map((institute) => <option value={institute.id} key={institute.id}>{institute.name}</option>)}</select><button disabled={busy || !selected}>Grant access</button></form>}</section><h2 className="section-title">Institute access</h2><table className="data-table"><thead><tr><th>Institute</th><th>Assigned</th><th>Status</th><th /></tr></thead><tbody>{!module.assignments.length ? <tr><td colSpan={4} className="empty-cell">Not assigned to an institute.</td></tr> : module.assignments.map((assignment) => <tr key={assignment.id}><td>{assignment.institute_name}</td><td>{new Date(assignment.assigned_at).toLocaleDateString()}</td><td><span className={`badge ${assignment.is_active ? "badge-green" : "badge-gray"}`}>{assignment.is_active ? "Active" : "Revoked"}</span></td><td>{assignment.is_active && <button className="danger" onClick={() => revoke(assignment.institute_id)}>Revoke</button>}</td></tr>)}</tbody></table></div>;
}
