import { type FormEvent, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { apiClient } from "../../api/client";
import type { ExamModule } from "../../api/types";

export function ModuleControl() {
  const [modules, setModules] = useState<ExamModule[]>([]);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { const { data } = await apiClient.get<ExamModule[]>("/super-admin/modules", { params: { search: search || undefined, status: status || undefined } }); setModules(data); } finally { setLoading(false); } }
  useEffect(() => { load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [status]);
  function submit(event: FormEvent) { event.preventDefault(); load(); }
  const instructors = useMemo(() => Object.values(modules.reduce<Record<string, { id: number; name: string; modules: ExamModule[] }>>((tree, module) => { const key = String(module.created_by_id); tree[key] ||= { id: module.created_by_id, name: module.created_by_name, modules: [] }; tree[key].modules.push(module); return tree; }, {})), [modules]);
  return <div><div className="page-header"><div><h1>Course Control</h1><p className="page-subtitle">Every course grouped under the SA Instructor who created it.</p></div></div><form className="filter-bar" onSubmit={submit}><input placeholder="Search courses..." value={search} onChange={(event) => setSearch(event.target.value)} /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select><button>Search</button></form>{loading ? <p>Loading...</p> : !instructors.length ? <div className="empty-state"><h2>No courses found</h2></div> : <div className="course-tree">{instructors.map((instructor) => <details open key={instructor.id}><summary><span className="tree-node-mark">I</span><span><strong>{instructor.name}</strong><small>{instructor.modules.length} course{instructor.modules.length === 1 ? "" : "s"}</small></span></summary><div className="course-tree-children">{instructor.modules.map((module) => <article key={module.id}><div className="tree-course-head"><div><span className={`badge ${module.status === "published" ? "badge-green" : module.status === "draft" ? "badge-amber" : "badge-gray"}`}>{module.status}</span>{!module.is_visible && <span className="badge badge-gray">hidden</span>}<h2>{module.title}</h2><p>{module.description || `${module.module_label} course`}</p></div><Link className="button-link" to={`/super-admin/modules/${module.id}`}>Manage</Link></div><dl className="tree-course-facts"><div><dt>Type</dt><dd>{module.module_label}</dd></div><div><dt>Created</dt><dd>{new Date(module.created_at).toLocaleString()}</dd></div><div><dt>Published</dt><dd>{module.published_at ? new Date(module.published_at).toLocaleString() : "Not published"}</dd></div><div><dt>Questions</dt><dd>{module.question_count}</dd></div><div><dt>Institutes</dt><dd>{module.assignment_count}</dd></div><div><dt>Updated</dt><dd>{module.updated_at ? new Date(module.updated_at).toLocaleString() : "No changes"}</dd></div></dl></article>)}</div></details>)}</div>}</div>;
}
