export const seoSettingsStrings = {
  defaults: {
    site_name: "IELTS LMS Pro",
    default_title: "IELTS LMS Pro | Computer-Delivered Exam Platform & AI Feedback",
    title_template: "%s | IELTS LMS Pro",
    default_meta_description: "Experience authentic computer-delivered IELTS environments with AI Speaking & Writing scoring.",
    default_meta_keywords: "IELTS LMS, IELTS Practice, AI IELTS Evaluation, Computer Delivered IELTS",
    default_og_image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80",
    twitter_handle: "@ieltslmspro",
    robots_txt: "User-agent: *\nAllow: /",
    custom_head_tags: "",
  },
  heading: "Centralized SEO & Meta Tag Settings",
  subheading: "Configure site-wide meta titles, descriptions, OpenGraph share images, keywords, and robots indexing.",
  savedBanner: "✓ SEO Settings updated successfully! Public pages will now reflect these tags dynamically.",
  fields: {
    siteName: "Site Brand Name",
    titleTemplate: "Title Template Pattern",
    titleTemplateHint: "Use %s as page title placeholder (e.g. %s | IELTS LMS)",
    defaultTitle: "Default Fallback Document Title",
    metaDescription: "Global Meta Description",
    metaKeywords: "Global SEO Keywords (Comma separated)",
    ogImage: "Default Social Share Image URL (OpenGraph)",
    twitterHandle: "Twitter / X Handle",
    robotsTxt: "Robots.txt Content",
  },
  saveBusy: "Saving...",
  saveLabel: "Save SEO Settings",
};
