export const couponsStrings = {
  searchPlaceholder: "Search coupon code...",
  exportPdf: "Export PDF",
  exportExcel: "Export Excel",
  newCoupon: "New Coupon",
  resultCount: {
    showing: "Showing",
    entry: "entry",
    entries: "entries",
  },
  loading: "Loading...",
  table: {
    code: "Code",
    discount: "Discount",
    scope: "Scope",
    usage: "Redemptions",
    perCustomerSuffix: (limit: number) => `(max ${limit}/customer)`,
    validWindow: "Valid Window",
    status: "Status",
    actions: "Actions",
    empty: "No coupons match these filters.",
    deactivate: "Deactivate Coupon",
    reactivate: "Reactivate Coupon",
    edit: "Edit Coupon",
    delete: "Delete Coupon",
  },
  deleteModal: {
    title: "Delete Coupon",
    message: (code: string) => `Are you sure you want to delete coupon "${code}"?`,
    confirmText: "Delete Coupon",
  },
  errors: {
    load: "Failed to load coupons.",
    toggle: (action: string) => `Failed to ${action} coupon.`,
    delete: "Failed to delete coupon.",
  },
  confirm: {
    toggle: (action: string, code: string) => `Are you sure you want to ${action} coupon code "${code}"?`,
    activateTitle: "Activate Coupon",
    deactivateTitle: "Deactivate Coupon",
  },
  pdf: {
    header: "Language CERT — Discount Coupons Report",
    generatedPrefix: "Generated:",
    columns: ["#", "Coupon Code", "Discount Value", "Scope", "Usage Count", "Valid Window", "Status"],
  },
  excel: {
    sheetName: "Coupons",
    columns: ["#", "Coupon Code", "Discount Type", "Value", "Scope", "Usage Count", "Usage Limit", "Valid From", "Valid Until", "Status"],
    unlimited: "Unlimited",
  },
} as const;
