export const superAdminTestimonialsStrings = {
  searchPlaceholder: "Search by name, role, score or quote...",
  statusFilters: ["ALL", "ACTIVE", "INACTIVE"] as const,
  gridViewTitle: "Grid View",
  tableViewTitle: "Table View",
  addTestimonial: "Add Testimonial",
  loading: "Loading testimonials...",
  emptyTitle: "No testimonials found",
  emptyHint: "Try adjusting your search or filters.",
  deleteConfirm: (name: string) => `Are you sure you want to delete the testimonial by "${name}"? This action cannot be undone.`,
  deleteConfirmTitle: "Delete Testimonial",
  deleteFallbackName: "testimonial",
  toggleVisibilityConfirm: (name: string, newStatus: string) => `Are you sure you want to change the status of "${name}"'s testimonial to ${newStatus}?`,
  toggleVisibilityTitle: "Change Testimonial Visibility",
  publishLabel: "Publish",
  unpublishLabel: "Unpublish",
  dragHandleTitle: "Drag to reorder",
  dragRowHandleTitle: "Drag row to reorder",
  editTooltip: "Edit",
  deleteTooltip: "Delete",
  publishedLabel: "Published",
  draftLabel: "Draft",
  activeLabel: "Active",
  orderPrefix: "Order",
  deactivateTooltip: "Deactivate",
  activateTooltip: "Activate",
  tableHeaders: {
    name: "NAME",
    score: "SCORE",
    quote: "QUOTE",
    status: "STATUS",
    order: "ORDER",
    actions: "ACTIONS",
  },
  newTestimonialDefaults: {
    student_role: "Computer-Delivered Academic Candidate",
    target_score: "Achieved Band 8.0",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
    rating: 5,
  },
  modal: {
    editTitle: "Edit Testimonial",
    addTitle: "Add New Testimonial",
    nameLabel: "Student Name",
    namePlaceholder: "e.g. Ananya Sharma",
    targetScoreLabel: "Target Score",
    targetScorePlaceholder: "e.g. Achieved Band 8.0",
    roleLabel: "Student Role / Context",
    rolePlaceholder: "e.g. Academic Candidate",
    avatarLabel: "Avatar Image URL",
    avatarPlaceholder: "https://example.com/photo.jpg",
    ratingLabel: "Rating (1-5)",
    quoteLabel: "Quote",
    quotePlaceholder: "Student's testimonial text...",
    displayOrderLabel: "Display Order",
    publishImmediatelyLabel: "Publish immediately (Active)",
    cancel: "Cancel",
    saveBusy: "Saving...",
    saveLabel: "Save Testimonial",
  },
};
