export const questionBankEditorStrings = {
  newBank: "New Question Bank",
  allBanksLink: "All question banks",
  loading: "Loading...",
  ownedByBanner: (name: string) => `This bank is owned by ${name}. You can view it, but only its creator can make changes.`,
  bankDetails: {
    heading: "Bank details",
    courseLabel: "Course",
    searchCoursesPlaceholder: "Search courses...",
    sectionLabel: "IELTS section",
    sectionLabels: {
      listening: "Listening",
      reading: "Reading",
      writing: "Writing",
      speaking: "Speaking",
    },
    titleLabel: "Title",
    descriptionLabel: "Description",
    saving: "Saving...",
    createBank: "Create Bank",
    saveDetails: "Save Details",
    deleteBank: "Delete bank",
    errors: {
      load: "Failed to load the question bank.",
      loadCourses: "Failed to load courses.",
      save: "Failed to save the question bank.",
      delete: "Failed to delete the question bank.",
    },
    notices: {
      saved: "Question bank details saved.",
    },
    deleteConfirm: (title: string) => `Are you sure you want to delete "${title}" and all of its questions?`,
    deleteConfirmTitle: "Delete Question Bank",
  },
  manualQuestion: {
    eyebrow: "Single entry",
    editHeading: "Edit question",
    addHeading: "Add one question",
    typeLabel: "Question type",
    difficultyLabel: "Difficulty",
    difficultyEasy: "Easy",
    difficultyMedium: "Medium",
    difficultyHard: "Hard",
    instructionsLabel: "Instructions",
    instructionsPlaceholder: "Optional directions shown above the question",
    passageLabel: "Passage or context",
    passagePlaceholder: "Optional reading passage, transcript, or speaking context",
    promptLabel: "Question",
    choicesLegend: "Choices and correct answer",
    addChoice: "Add choice",
    acceptedAnswersLabel: "Accepted answer(s)",
    acceptedAnswersPlaceholder: "Separate alternatives with commas",
    pointsLabel: "Points",
    explanationLabel: "Answer explanation",
    explanationPlaceholder: "Optional feedback after grading",
    saving: "Saving...",
    updateQuestion: "Update Question",
    addQuestion: "Add Question",
    cancelEdit: "Cancel edit",
    errors: {
      save: "Failed to save the question.",
      delete: "Failed to delete the question.",
    },
    notices: {
      updated: "Question updated.",
      added: "Question added.",
    },
    deleteConfirm: "Are you sure you want to delete this question?",
    deleteConfirmTitle: "Delete Question",
  },
  bulkImport: {
    eyebrow: "Bulk import",
    heading: "Extract PDF or CSV",
    csvTemplate: "CSV template",
    hint: "PDF format: numbered questions, choices such as “A. Choice”, and “Answer: B”. Text-based PDFs work now; scanned pages need OCR first.",
    extracting: "Extracting...",
    extractAndReview: "Extract & Review",
    errors: {
      preview: "Could not extract questions from this file.",
      selectOne: "Select at least one extracted question.",
      commit: "Review the highlighted content and try importing again.",
    },
    notices: {
      imported: (count: number) => `${count} questions imported.`,
    },
  },
  importReview: {
    heading: "Review extracted content",
    summary: (count: number, warnings: number, filename: string) => `${count} detected · ${warnings} warnings · ${filename}`,
    selectAll: "Select all",
    deselectAll: "Deselect all",
    discard: "Discard",
    importing: "Importing...",
    import: (count: number) => `Import ${count} Selected`,
    warningsHeading: "Check these items before import",
    moreWarnings: (count: number) => `And ${count} more warnings in the question cards.`,
    sourceTextSummary: "View extracted file text",
    includeQuestion: (index: number) => `Include question ${index}`,
    typeLabel: "Type",
    answerKeysLabel: "Correct answer key(s)",
    answerKeysPlaceholder: "B or A, C",
    questionLabel: "Question",
  },
  savedQuestions: {
    heading: "Saved questions",
    description: (label: string) => `${label} in this reusable bank.`,
    emptyTitle: "No questions yet",
    emptyDescription: "Add one manually or import PDF/CSV content above.",
    pointsSuffix: "pt",
    accepted: "Accepted:",
    edit: "Edit",
    delete: "Delete",
  },
  questionCountLabel: (count: number) => `${count} question${count === 1 ? "" : "s"}`,
} as const;
