export const instituteBrandingStrings = {
  title: "Institute Branding",
  primaryColor: "Primary color",
  secondaryColor: "Secondary color",
  typographyHeading: "Typography",
  typographyHint: "Applied to the institute admin, instructor, and student portals.",
  fontFamily: "Font family",
  systemUi: "System UI",
  headingWeight: "Heading weight",
  bodyWeight: "Body weight",
  logo: "Logo",
  uploading: "Uploading...",
  uploadLogo: "Upload logo",
  logoHint: "PNG, JPEG, or WebP. Max 2 MB.",
  saving: "Saving...",
  saveBranding: "Save branding",
  livePreviewHeading: "Live preview",
  livePreviewHint: "This is what the institute's own portal will look like once themed with these colors.",
  errors: {
    save: "Failed to save branding.",
    uploadLogo: "Failed to upload logo.",
  },
  notices: {
    saved: "Branding saved.",
    logoUploaded: "Logo uploaded.",
  },
  preview: {
    defaultInstituteName: "Institute Portal",
    instituteStudent: "Institute Student",
    dashboard: "Dashboard",
    myTests: "My Tests",
    myTestHistory: "My Test History",
    progress: "Progress",
    myProfile: "My Profile",
    activeSessions: "Active Sessions",
    portalLabel: "Institute Student Portal",
    welcome: "Welcome, QA",
    description: "Take assigned tests and track CEFR results.",
    viewAssignedTests: "View assigned tests",
    stats: {
      availableTests: "Available tests",
      inProgress: "In progress",
      awaitingGrading: "Awaiting grading",
      graded: "Graded",
    },
    assignedTestsHeading: "Institute assigned tests",
    assignedTestsDescription: "Only tests allotted to your institute are available here.",
    availableNow: "Available now",
    testsCountSuffix: "tests",
    goToMyTests: "Go to My Tests",
    recentActivityHeading: "Recent test activity",
    sampleActivities: ["Sample Full Mock Test", "Sample Final Test", "Sample Reading Course"],
    awaitingGradingLabel: "Awaiting grading",
  },
} as const;
