export const accountsListStrings = {
  searchPlaceholder: "Search admin name or email...",
  statusFilter: {
    allStatuses: "All statuses",
    active: "Active",
    inactive: "Inactive",
  },
  exportPdf: "Export PDF",
  exportExcel: "Export Excel",
  newAccount: "+ New Account",
  resultCount: {
    showing: "Showing",
    entry: "entry",
    entries: "entries",
  },
  bulkActions: {
    selectedSuffix: "selected",
    activate: "Activate",
    deactivate: "Deactivate",
    delete: "Delete",
    clear: "Clear",
  },
  loading: "Loading...",
  table: {
    name: "Name",
    email: "Email",
    status: "Status",
    created: "Created",
    actions: "Actions",
    empty: "No admin accounts found.",
    you: "You",
    resetRequired: "Reset Required",
    deactivate: "Deactivate Account",
    reactivate: "Reactivate Account",
    edit: "Edit Account",
    clearPasswordReset: "Clear Password Reset",
    requirePasswordReset: "Require Password Reset",
    delete: "Delete Account",
  },
  deleteModal: {
    title: "Delete Admin Account",
    message: (email: string) => `Are you sure you want to delete account "${email}"? This action cannot be undone.`,
    confirmText: "Delete Account",
  },
  errors: {
    load: "Failed to load accounts.",
    toggleActive: (action: string) => `Failed to ${action} account.`,
    forceReset: "Failed to update password-reset requirement.",
    delete: "Failed to delete account.",
    bulkToggle: (action: string, failed: number, total: number) => `Failed to ${action} ${failed} of ${total} accounts.`,
    bulkDelete: (failed: number, total: number) => `Failed to delete ${failed} of ${total} accounts.`,
  },
  bulkDeleteConfirm: (count: number) => `Are you sure you want to delete ${count} account${count === 1 ? "" : "s"}? This action cannot be undone.`,
  bulkDeleteConfirmTitle: "Delete Accounts",
  confirm: {
    toggleActive: (action: string, name: string) => `Are you sure you want to ${action} account "${name}"?`,
    activateTitle: "Activate Account",
    deactivateTitle: "Deactivate Account",
    toggleMany: (action: string, count: number) => `Are you sure you want to ${action} ${count} selected account${count === 1 ? "" : "s"}?`,
    activateManyTitle: "Activate Accounts",
    deactivateManyTitle: "Deactivate Accounts",
  },
  pdf: {
    header: "IELTS LMS — Super Admin Accounts",
    columns: ["#", "Name", "Email", "Status", "Created"],
  },
  excel: {
    sheetName: "Admin Accounts",
    columns: ["#", "First Name", "Last Name", "Email", "Status", "Force Password Reset", "Created At"],
    yes: "Yes",
    no: "No",
  },
} as const;
