export const paymentsStrings = {
  title: "Payments",
  subtitle: "Record and manage financial transactions, invoices, and partial due balances.",
  recordPayment: "+ Record Payment",
  cancel: "Cancel",
  recordedBannerPrefix: "Payment recorded — invoice",
  viewInvoice: "View invoice",
  recordForm: {
    heading: "Record Manual Payment",
    description: "Records an offline payment (bank transfer, cash, etc.) and immediately grants the subscription.",
    instituteLabel: "Institute",
    selectInstitute: "Select institute...",
    searchInstitutes: "Search institutes...",
    planLabel: "Plan",
    selectPlan: "Select plan...",
    searchPlans: "Search plans...",
    couponLabel: "Coupon code (optional)",
    couponPlaceholder: "e.g. WELCOME10",
    amountReceivedLabel: "Amount received (optional)",
    fullPricePrefix: "Full price:",
    fullPrice: "Full price",
    methodLabel: "Payment mode",
    selectMode: "Select mode...",
    searchModes: "Search modes...",
    referenceLabel: "Reference note",
    referencePlaceholder: "Bank txn ID, cheque no...",
    recording: "Recording...",
    submit: "Record Payment",
  },
  searchPlaceholder: "Search invoice, institute, plan...",
  instituteFilter: {
    allInstitutes: "All institutes",
    search: "Search institute...",
  },
  statusFilter: {
    allStatuses: "All statuses",
    paid: "Paid",
    partial: "Partial",
    pending: "Pending",
    failed: "Failed",
    refunded: "Refunded",
  },
  dateFrom: "From Date",
  dateTo: "To Date",
  dateSeparator: "to",
  exportPdf: "Export PDF",
  exportExcel: "Export Excel",
  resultCount: {
    showing: "Showing",
    entry: "entry",
    entries: "entries",
  },
  loading: "Loading...",
  table: {
    invoice: "Invoice",
    source: "Source",
    instituteOrPlan: "Institute / Plan",
    paidOrDue: "Paid / Due",
    status: "Status",
    date: "Date",
    actions: "Actions",
    empty: "No payments match these filters.",
    directStudent: "Direct Student",
    planPrefix: "Plan:",
    duePrefix: "due",
    viewInvoiceTooltip: "View Invoice",
    recordDuePaymentTooltip: "Record Due Payment",
  },
  dueModal: {
    heading: "Record Due Payment",
    duePrefix: "due",
    amountLabel: "Amount",
    methodLabel: "Payment mode",
    selectMode: "Select mode...",
    searchModes: "Search modes...",
    referenceLabel: "Reference note",
    referencePlaceholder: "Bank txn ID...",
  },
  errors: {
    load: "Failed to load payments.",
    record: "Failed to record payment.",
    recordDue: "Failed to record due payment.",
  },
  pdf: {
    header: "IELTS LMS — Payment Transactions Report",
    generatedPrefix: "Generated:",
    columns: ["#", "Invoice", "Source", "Institute / Plan", "Amount Paid", "Due Amount", "Status", "Date"],
  },
  excel: {
    sheetName: "Payments",
    columns: ["#", "Invoice Number", "Source", "Institute Name", "Plan Name", "Currency", "Final Amount", "Amount Paid", "Due Amount", "Status", "Created At"],
  },
} as const;
