export const loginStrings = {
  defaultTitle: "IELTS LMS",
  defaultSubtitle: "Enter your credentials to access your dashboard",
  brandName: "Visa House",
  brandTag: "IELTS LMS",
  welcomeBack: "back.",
  emailLabel: "Email address",
  emailPlaceholder: "name@example.com",
  passwordLabel: "Password",
  passwordPlaceholder: "Enter password",
  forgotPasswordLink: "Forgot password?",
  rememberMeLabel: "Remember me on this device",
  signInBusy: "Signing in...",
  signInLabel: (role: string) => `Sign in as ${role} →`,
  noPortalError: "This role does not have a portal yet.",
  noPortalToast: "This role does not have an active portal yet.",
  loginFailedTitle: "Login Failed",
  roleMismatchError: (actualRole: string, attemptedRole: string) => `These credentials belong to a ${actualRole} account, not a ${attemptedRole} account.`,
  roleMismatchToast: (attemptedRole: string, actualRole: string) => `You tried to sign in as a ${attemptedRole}, but these credentials are for a ${actualRole}.`,
  roleMismatchTitle: "Role Mismatch",
  welcomeToast: (role: string) => `Welcome back, ${role}!`,
  signedInTitle: "Signed In",
  genericAuthError: "Unable to sign in. Please try again.",
  connectionError: "Unable to connect to the login service.",
  authErrorTitle: "Authentication Error",
  registerPrompt: "New student? ",
  registerLink: "Create a student account",
  institutePortalPrompt: "Institute Admin or Student? ",
  institutePortalLink: "Go to Portal Login",
  superAdminPrompt: "Platform Admin? ",
  superAdminLink: "Super Admin Login",
  forgotModal: {
    title: "Reset Password",
    description: "Enter your account email address. We'll send you an email with a secure link to reset your password.",
    sentMessage: "Reset link sent! Check your email inbox for instructions.",
    doneLabel: "Done",
    emailLabel: "Email Address",
    cancelLabel: "Cancel",
    sendBusy: "Sending...",
    sendLabel: "Send Reset Link",
    genericError: "Failed to send reset link.",
  },
};
