export const loginStrings = {
  defaultTitle: "Visa House",
  defaultSubtitle: "Enter your credentials to access your dashboard",
  brandName: "Visa House",
  brandTag: "Visa House",
  welcomeBack: "back.",
  emailLabel: "Email address",
  emailPlaceholder: "name@example.com",
  passwordLabel: "Password",
  passwordPlaceholder: "Enter password",
  forgotPasswordLink: "Forgot password?",
  rememberMeLabel: "Remember me on this device",
  signInBusy: "Signing in...",
  googleLoginLabel: "Continue with Google",
  googleLoginBusy: "Opening Google...",
  signInLabel: (role: string) => `Sign in as ${role} →`,
  otpSentTitle: "OTP Required",
  otpSentToast: "Enter the OTP sent to your registered email.",
  otpTitle: "Two-factor verification",
  otpDescription: "Enter the one-time password sent to your registered email to complete login.",
  otpLabel: "OTP code",
  otpPlaceholder: "Enter 6-digit code",
  otpVerifyBusy: "Verifying...",
  otpVerifyLabel: "Verify OTP",
  otpCancelLabel: "Cancel",
  otpInvalidResponse: "The login service did not return an OTP challenge.",
  otpInvalidToken: "The login service did not return a session token.",
  noPortalError: "This role does not have a portal yet.",
  noPortalToast: "This role does not have an active portal yet.",
  loginFailedTitle: "Login Failed",
  roleMismatchError: "Invalid email or password.",
  roleMismatchToast: "Invalid email or password.",
  roleMismatchTitle: "Login Failed",
  welcomeToast: (role: string) => `Welcome back, ${role}!`,
  signedInTitle: "Signed In",
  genericAuthError: "Unable to sign in. Please try again.",
  connectionError: "Unable to connect to the login service.",
  authErrorTitle: "Authentication Error",
  registerPrompt: "New student? ",
  registerLink: "Create a student account",
  institutePortalPrompt: "Institute Admin or Student? ",
  institutePortalLink: "Go to Portal Login",
  superAdminPrompt: "Platform Admin? ",
  superAdminLink: "Super Admin Login",
  forgotModal: {
    title: "Reset Password",
    description: "Enter your account email address. We'll send you an email with a secure link to reset your password.",
    sentMessage: "Reset link sent! Check your email inbox for instructions.",
    doneLabel: "Done",
    emailLabel: "Email Address",
    cancelLabel: "Cancel",
    sendBusy: "Sending...",
    sendLabel: "Send Reset Link",
    genericError: "Failed to send reset link.",
  },
};
