export const dashboardStrings = {
  loading: "Loading...",
  loadError: "Failed to load dashboard.",
  metricTitles: {
    institutes: "Total Institutes",
    subscriptions: "Active Subscriptions",
    revenue: "Total Revenue",
    dues: "Total Due",
    transactions: "Transactions",
    demos: "Active Demos",
    instructors: "SA Instructors",
    modules: "Published Modules",
  },
  badges: {
    pending: "Pending",
    settled: "Settled",
    demo: "Demo",
    verified: "Verified",
    published: "Published",
  },
  charts: {
    byInstituteTitle: "Revenue by Institute",
    byInstituteAriaLabel: "Revenue by institute",
    byMonthTitle: "Revenue by Month",
    byMonthAriaLabel: "Revenue by month",
    revenueEmpty: "No revenue recorded yet.",
    paymentStatusTitle: "Payment Status",
    paymentStatusCenterLabel: "payments",
    paymentStatusAriaLabel: "Payment status breakdown",
    paymentStatusEmpty: "No payments recorded yet.",
    instituteStateTitle: "Institutes by Subscription State",
    instituteStateAriaLabel: "Institutes by subscription state",
    instituteStateEmpty: "No institutes yet.",
  },
  subscriptionStateLabels: {
    active: "Active",
    grace: "In grace",
    expired: "Expired",
    none: "No plan",
  },
  detailModal: {
    eyebrow: "Dashboard Detail",
    closeLabel: "Close details",
    closeTitle: "Close",
    loadingDetails: "Loading details...",
    loadDetailsError: "Failed to load these details.",
    totalRecords: "Total Records",
  },
  growth: {
    "7D": { rev: "+18% growth", sub: "7D Live", inst: "Active" },
    "30D": { rev: "+34% growth", sub: "30D Live", inst: "Active" },
    "90D": { rev: "+72% growth", sub: "90D Live", inst: "Active" },
  },
} as const;
