export const dashboardStrings = {
  loading: "Loading...",
  loadError: "Failed to load dashboard.",
  eyebrow: "Super Admin Dashboard",
  welcome: (firstName: string | undefined) => `Welcome, ${firstName ?? "admin"}`,
  subtitle: "Monitor platform activity, subscriptions, student progress, and operating health.",
  noLivePlan: {
    title: "No live plan — your public pricing page is empty",
    body: "Visitors on the Plans page see nothing to buy until at least one plan is active and published.",
    cta: "Create a plan",
  },
  pendingSignups: {
    title: (count: number) =>
      count === 1
        ? "1 institute is waiting to be reviewed"
        : `${count} institutes are waiting to be reviewed`,
    body: "Applications from the public site sit here until someone approves or declines them. Nothing is created until you do.",
    cta: "Review applications",
  },
  metricTitles: {
    institutes: "Total Institutes",
    students: "Students Enrolled",
    online_students: "Students Online",
    active_tests: "Students Giving Tests",
    subscriptions: "Active Subscriptions",
    revenue: "Total Revenue",
    dues: "Total Due",
    transactions: "Transactions",
    demos: "Active Demos",
    instructors: "SA Instructors",
    modules: "Published Modules",
  },
  badges: {
    pending: "Pending",
    settled: "Settled",
    demo: "Demo",
    verified: "Verified",
    published: "Published",
    online: "Online",
    live: "Live",
    enrolled: "Enrolled",
  },
  charts: {
    byInstituteTitle: "Revenue by Institute",
    byInstituteAriaLabel: "Revenue by institute",
    byMonthTitle: "Revenue by Month",
    byMonthAriaLabel: "Revenue by month",
    revenueEmpty: "No revenue recorded yet.",
    paymentStatusTitle: "Payment Status",
    paymentStatusCenterLabel: "payments",
    paymentStatusAriaLabel: "Payment status breakdown",
    paymentStatusEmpty: "No payments recorded yet.",
    studentTypeTitle: "Students by Type",
    studentTypeCenterLabel: "students",
    studentTypeAriaLabel: "Student type breakdown",
    studentTypeEmpty: "No students enrolled yet.",
    instituteStateTitle: "Institutes by Subscription State",
    instituteStateAriaLabel: "Institutes by subscription state",
    instituteStateEmpty: "No institutes yet.",
  },
  subscriptionStateLabels: {
    active: "Active",
    grace: "In grace",
    expired: "Expired",
    none: "No plan",
  },
  detailModal: {
    eyebrow: "Dashboard Detail",
    closeLabel: "Close details",
    closeTitle: "Close",
    loadingDetails: "Loading details...",
    loadDetailsError: "Failed to load these details.",
    totalRecords: "Total Records",
    showingFor: (label: string) => `Showing ${label} only`,
  },
  breakdownPanel: {
    acrossMethods: (count: number) => `across ${count} payment ${count === 1 ? "method" : "methods"}`,
    transactions: (count: number) => `${count} ${count === 1 ? "txn" : "txns"}`,
    otherLabel: (count: number) => `Other (${count})`,
    allMethods: "All methods",
    shareOfTotal: (share: string, total: string) => `${share}% of ${total} collected`,
    barAria: (parts: string) => `Share of revenue by payment method: ${parts}`,
  },
} as const;
