export const attemptResultStrings = {
  eyebrow: "Result overview",
  allAttempts: "All attempts",
  loadError: "Failed to load this result.",
  loading: "Loading...",
  statusLabels: {
    submitted: "Auto-grading in progress",
    grading: "Awaiting instructor grading",
    graded: "Graded",
    expired: "Expired before submission",
  },
  aiEvaluation: {
    inProgress: "AI evaluation in progress...",
    stillRunning: "Still evaluating - this can take a few minutes on longer answers.",
    checkAgain: "Check now",
    checking: "Checking...",
    manualReview: "Manual instructor review required",
    retryAi: "Try AI marking again",
    retrying: "Sending...",
    retryFailed: "Could not send this for AI marking again.",
    progress: {
      heading: "Marking your answers",
      remainingLabel: "estimated time left",
      elapsedLabel: "time taken so far",
      phases: {
        collecting: "Collecting your answers...",
        reading: "Reading what you wrote...",
        listening: "Listening to your recording...",
        language: "Checking grammar, vocabulary and accuracy...",
        rubric: "Weighing it against the marking rubric...",
        band: "Working out your CEFR band...",
        feedback: "Writing your feedback...",
      },
      overtimePhases: [
        "Still working on it...",
        "Long answers take the examiner longer too...",
        "Almost there - your result appears here on its own...",
      ],
      /** Says why the wait is as long as it is, in the student's own numbers. */
      workload: (progress: { words: number; audio_seconds: number }) => {
        const pieces: string[] = [];
        if (progress.words > 0) pieces.push(`${progress.words.toLocaleString()} words`);
        if (progress.audio_seconds > 0) {
          const minutes = Math.floor(progress.audio_seconds / 60);
          const seconds = progress.audio_seconds % 60;
          pieces.push(minutes > 0 ? `${minutes}m ${seconds}s of audio` : `${seconds}s of audio`);
        }
        return pieces.length ? `Marking ${pieces.join(" and ")}` : "Marking your submission";
      },
      partsDone: (done: number, total: number) => `${done} of ${total} sections done`,
    },
  },
  metrics: {
    totalQuestions: "Total questions",
    attempted: "Attempted",
    correct: "Correct",
    incorrect: "Incorrect",
    awaitingReview: "Awaiting review",
    unanswered: "Unanswered",
    attemptedSuffix: "attempted",
  },
  overview: {
    performanceEyebrow: "Performance",
    heading: "Question overview",
    cefrLevel: "CEFR level",
    pending: "Pending",
    score: "Score",
    submitted: "Submitted",
    viewDetailedReview: "View detailed review",
    aiGradedBadge: "Evaluated by AI",
  },
  analysis: {
    eyebrow: "Personalised coaching",
    heading: "Performance analysis",
    aiEvaluated: "AI evaluated",
    cefrAnalysis: "CEFR analysis",
    aiSourceText:
      "This coaching summary was generated by the configured AI evaluator. You can request instructor review if you want a human to check the result.",
    cefrSourceText: "This coaching summary was generated from the CEFR analysis engine. Human examiner feedback remains the final reference for reviewed parts.",
    analysing: "Analysing your result...",
    aiPending:
      "AI is currently evaluating your Writing/Speaking answers. The coaching summary and CEFR level will update automatically once complete.",
    manualReview:
      "AI evaluation could not finish automatically for every enabled part. Your submission remains in the instructor grading queue for manual review.",
    unavailable: "The analysis is temporarily unavailable. Your detailed result is still ready to review.",
    progression: {
      heading: "Distance to your next level",
      currentPrefix: "Now",
      nextPrefix: "Next",
      atCeiling: "You are at the top band of this practice scale.",
      pointsAway: (points: string, level: string, target: string) =>
        `${points} practice points from ${level} - this attempt scored ${target}.`,
    },
    focusAreas: {
      heading: "Where to focus first",
      subheading: "Ordered by how much each one is costing you on this paper.",
      actionLabel: "Try this",
    },
    partBreakdown: {
      heading: "Where your marks went",
      subheading: "Every part of the paper, what it tests, and what you scored.",
      awaitingExaminer: "Awaiting examiner marking",
      unansweredSuffix: (count: number) => `${count} left blank`,
    },
    questionTypes: {
      heading: "By question format",
      testsPrefix: "Tests",
    },
    difficulty: {
      heading: "By item difficulty",
    },
    criteria: {
      heading: "Examiner criteria",
      subheading: "The rubric marks behind your Writing and Speaking scores.",
    },
    pacing: {
      heading: "Timing",
      used: (used: number, allowed: number) => `${used} of ${allowed} minutes used`,
    },
    statusLabels: {
      strong: "Strong",
      steady: "Steady",
      priority: "Priority",
      pending: "Pending",
    },
    whatWentWell: "What went well",
    whatToImprove: "What to improve",
    nextPracticeSteps: "Next practice steps",
    disclaimer: (framework: string) =>
      `Generated from your recorded answers and ${framework} profile. Use examiner feedback as the final reference for human-marked responses.`,
  },
  reevaluation: {
    eyebrow: "Instructor review",
    requestSentHeading: "Review request sent",
    reviewerPrefix: "Reviewer:",
    resolutionHeading: "Resolution",
  },
  reevaluationForm: {
    heading: "Request human review",
    description:
      "Your request stays with your institute staff. It is routed to the Super Admin instructor queue only when your institute has no active staff.",
    reasonLabel: "What should the instructor review?",
    reasonPlaceholder: "Explain the score, AI analysis, recording, or feedback you want checked.",
    sending: "Sending...",
    submit: "Send to instructor review",
    errors: {
      submit: "Failed to send this result for instructor review.",
    },
  },
  retake: {
    eyebrow: "Retake request",
    heading: "Retake request",
    reviewerPrefix: "Reviewed by:",
    resolutionHeading: "Admin note",
    errors: {
      submit: "Failed to submit your retake request.",
    },
  },
  retakeForm: {
    eyebrow: "Couldn't complete this test?",
    heading: "Raise a Retake Request",
    description:
      "Each test can only be attempted once. If something went wrong - a technical issue, an interruption, or anything that stopped you from completing it properly - explain what happened and the Super Admin will review your request.",
    reasonLabel: "Reason for the retake request",
    submitting: "Submitting...",
    submit: "Submit retake request",
  },
  supportStrip: {
    title: "Need help with this attempt?",
    subtitle: "Request an instructor review for manual scoring or submit a test retake appeal.",
    reviewBtn: "Request Human Review",
    retakeBtn: "Raise Retake Request",
  },
} as const;
