export const attemptResultStrings = {
  eyebrow: "Result overview",
  allAttempts: "All attempts",
  loadError: "Failed to load this result.",
  loading: "Loading...",
  statusLabels: {
    submitted: "Auto-grading in progress",
    grading: "Awaiting instructor grading",
    graded: "Graded",
    expired: "Expired before submission",
  },
  aiEvaluation: {
    inProgress: "AI evaluation in progress...",
    manualReview: "Manual instructor review required",
  },
  metrics: {
    totalQuestions: "Total questions",
    attempted: "Attempted",
    correct: "Correct",
    incorrect: "Incorrect",
    awaitingReview: "Awaiting review",
    unanswered: "Unanswered",
    attemptedSuffix: "attempted",
  },
  overview: {
    performanceEyebrow: "Performance",
    heading: "Question overview",
    cefrLevel: "CEFR level",
    pending: "Pending",
    score: "Score",
    submitted: "Submitted",
    viewDetailedReview: "View detailed review",
    aiGradedBadge: "Evaluated by AI",
  },
  analysis: {
    eyebrow: "Personalized coaching",
    heading: "Performance analysis",
    aiEvaluated: "AI evaluated",
    cefrAnalysis: "CEFR analysis",
    aiSourceText:
      "This coaching summary was generated by the configured AI evaluator. You can request instructor review if you want a human to check the result.",
    cefrSourceText: "This coaching summary was generated from the CEFR analysis engine. Human examiner feedback remains the final reference for reviewed parts.",
    analysing: "Analysing your result...",
    aiPending:
      "AI is currently evaluating your Writing/Speaking answers. The coaching summary and CEFR level will update automatically once complete.",
    manualReview:
      "AI evaluation could not finish automatically for every enabled part. Your submission remains in the instructor grading queue for manual review.",
    unavailable: "The analysis is temporarily unavailable. Your detailed result is still ready to review.",
    whatWentWell: "What went well",
    whatToImprove: "What to improve",
    nextPracticeSteps: "Next practice steps",
    disclaimer: (framework: string) =>
      `Generated from your recorded answers and ${framework} profile. Use examiner feedback as the final reference for human-marked responses.`,
  },
  reevaluation: {
    eyebrow: "Instructor review",
    requestSentHeading: "Review request sent",
    reviewerPrefix: "Reviewer:",
    resolutionHeading: "Resolution",
  },
  reevaluationForm: {
    heading: "Request human review",
    description:
      "Your request stays with your institute staff. It is routed to the Super Admin instructor queue only when your institute has no active staff.",
    reasonLabel: "What should the instructor review?",
    reasonPlaceholder: "Explain the score, AI analysis, recording, or feedback you want checked.",
    sending: "Sending...",
    submit: "Send to instructor review",
    errors: {
      submit: "Failed to send this result for instructor review.",
    },
  },
} as const;
