export const studentOverviewStrings = {
  eyebrow: "Student record",
  back: "Back",
  edit: "Edit",
  stats: {
    testsTaken: "Tests taken",
    devicesUsed: "Devices used",
    activeDevices: "Active devices",
    lastLogin: "Last login",
  },
  status: {
    deleted: "Deleted",
    active: "Active",
    inactive: "Inactive",
    noPhoneNumber: "No phone number",
  },
  actionTooltips: {
    resetPassword: "Reset password",
    signOutDevice: "Sign out device",
    deactivate: "Deactivate student",
    reactivate: "Reactivate student",
    delete: "Delete student",
  },
  deviceHistory: {
    eyebrow: "Security",
    heading: "Device history",
    device: "Device",
    firstLogin: "First login",
    lastLogin: "Last login",
    logins: "Logins",
    lastIp: "Last IP",
    status: "Status",
    unknownDevice: "Unknown device",
    signedOut: "Signed out",
    empty: "This student has not logged in yet.",
  },
  testHistory: {
    eyebrow: "Assessment",
    heading: "Test and grading history",
    test: "Test",
    started: "Started",
    status: "Status",
    score: "Score",
    checkedBy: "Checked by",
    pending: "Pending",
    autoGraded: "Auto-graded",
    awaitingGrading: "Awaiting grading",
    empty: "No tests taken.",
  },
  credentialModal: {
    title: "Temporary password",
    passwordLabel: "Password",
    copyPassword: "Copy password",
    done: "Done",
  },
  confirm: {
    revokeSessions: "Sign this student out from the active device?",
    resetPassword: "Reset this student's password and sign out the active device?",
    deleteStudent: "Are you sure you want to delete this student account? Test and device history will be retained.",
    deleteStudentTitle: "Delete Student Account",
  },
  errors: {
    load: "Failed to load the student record.",
  },
  backToStudents: "Back to students",
  loading: "Loading...",
} as const;
