export const testEditorStrings = {
  typeLabels: {
    practice: "Practice test",
    module_mock: "Module mock",
    full_mock: "Full IELTS mock",
    final: "Final test",
  },
  newTest: "New Test",
  allTestsLink: "All tests",
  loading: "Loading...",
  ownedByBanner: (name: string) => `This test is owned by ${name}. You can view it, but only its creator can change it.`,
  statusBar: {
    summary: (questions: number, points: string, minutes: number | null) =>
      `${questions} questions · ${points} points${minutes ? ` · ${minutes} minutes` : ""}`,
    moveToDraft: "Move to draft",
    publish: "Publish",
    archive: "Archive",
    statusChanged: (status: string) => `Test moved to ${status}.`,
    errors: {
      changeStatus: "Failed to change test status.",
    },
  },
  details: {
    heading: "Test details",
    description: "Configure course, type, title, instructions, and timing.",
    courseLabel: "Course",
    searchCoursesPlaceholder: "Search courses...",
    typeLabel: "Test type",
    titleLabel: "Title",
    descriptionLabel: "Description",
    instructionsLabel: "Student instructions",
    durationLabel: "Time limit in minutes",
    durationPlaceholder: "Leave empty for untimed",
    saving: "Saving...",
    createTest: "Create Test",
    saveDetails: "Save Details",
    deleteTest: "Delete test",
    errors: {
      load: "Failed to load the test.",
      loadCourses: "Failed to load courses.",
      loadQuestions: "Failed to load this course's questions.",
      save: "Failed to save test details.",
      delete: "Failed to delete the test.",
    },
    notices: {
      saved: "Test details saved.",
    },
    deleteConfirm: (title: string) => `Are you sure you want to delete test "${title}"?`,
    deleteConfirmTitle: "Delete Test",
  },
  questionPicker: {
    heading: "Course questions",
    description: "Select questions to add to this test.",
    shownCount: (count: number) => `${count} shown`,
    searchPlaceholder: "Search questions...",
    sectionLabels: {
      allSections: "All sections",
      listening: "Listening",
      reading: "Reading",
      writing: "Writing",
      speaking: "Speaking",
    },
    selectAll: "Select all",
    deselectAll: "Deselect all",
    emptyTitle: "No questions available",
    emptyDescription: (course: string) => `Create a question bank for ${course} first.`,
    newQuestionBank: "New Question Bank",
    pointsSuffix: "pt",
  },
  testOrder: {
    heading: "Test order",
    description: "Students receive questions in this order.",
    empty: "Select questions from the course bank.",
    moveUp: "Move up",
    moveDown: "Move down",
    remove: "Remove",
    saving: "Saving...",
    save: "Save Question Order",
    notices: {
      saved: "Question order saved.",
    },
    errors: {
      save: "Failed to save test questions.",
    },
    fallbackQuestion: (id: number) => `Question ${id}`,
  },
} as const;
