export const courseAssignmentsStrings = {
  subtitle: "Control website visibility, lifecycle, and institute access.",
  backToHierarchy: "Back to hierarchy",
  hideFromWebsite: "Hide from website",
  showOnWebsite: "Show on website",
  publish: "Publish",
  archive: "Archive",
  deleteCourse: "Delete course",
  noSummary: "No summary",
  noDescription: "No description provided.",
  facts: {
    instructor: "Instructor",
    created: "Created",
    published: "Published",
    notPublished: "Not published",
    modules: "Modules",
  },
  assignForm: {
    heading: "Assign to institute",
    publishFirst: "Publish the course before assigning it.",
    instituteLabel: "Institute",
    selectPlaceholder: "Select an active institute...",
    searchPlaceholder: "Type to search institute...",
    assigning: "Assigning...",
    grantAccess: "Grant access",
  },
  resources: {
    heading: "Course resources",
    empty: "No resources uploaded.",
  },
  history: {
    heading: "Institute access history",
    institute: "Institute",
    assigned: "Assigned",
    status: "Status",
    actions: "Actions",
    empty: "Not assigned to any institute.",
    active: "Active",
    revoked: "Revoked",
    revokeAccess: "Revoke access",
  },
  errors: {
    load: "Failed to load course assignments.",
    assign: "Failed to assign course.",
    revoke: "Failed to revoke course.",
    visibility: "Failed to update visibility.",
    status: "Failed to update status.",
    delete: "Failed to delete course.",
  },
  revokeConfirm: "Revoke this course from the institute?",
  revokeConfirmTitle: "Revoke Access",
  revokeConfirmButton: "Revoke access",
  deleteConfirm: (title: string) => `Are you sure you want to delete "${title}" and revoke all active access? Historical records will be retained.`,
  deleteConfirmTitle: "Delete Course",
  loading: "Loading...",
} as const;
