export const studentAttemptsStrings = {
  eyebrow: "History",
  title: "My Test History",
  subtitle: "Every attempt you've started, submitted, or completed.",
  loadError: "Failed to load your test history.",
  timeoutError: "The test history request is taking too long. Please try again.",
  loading: "Loading...",
  retry: "Try again",
  refreshing: "Refreshing...",
  empty: {
    title: "No attempts yet",
    description: "Start a test from My Courses.",
  },
  table: {
    module: "Module",
    status: "Status",
    started: "Started",
    score: "Score",
    band: "Band",
    actions: "Actions",
  },
  statusLabels: {
    ready: "Security check",
    in_progress: "In progress",
    submitted: "Submitted",
    grading: "Awaiting grading",
    graded: "Graded",
    expired: "Expired",
  },
  resumeTest: "Resume test",
  viewResult: "View result",
  gradingFilterLabels: {
    all: "All Grading Types",
    ai_graded: "Graded by AI",
    instructor_requested: "Requested for Instructor Grading",
    pending_grading: "Pending Grading",
    instructor_graded: "Graded by Instructor",
  },
  gradingBadges: {
    ai_graded: "AI Graded",
    instructor_requested: "Instructor Review Requested",
    pending_grading: "Pending Grading",
    instructor_graded: "Instructor Graded",
    auto_marked: "Auto Marked",
  },
  gradingPlaceholder: "Filter by grading",
  emptyFiltered: {
    title: "No attempts found",
    description: "Try adjusting your status or grading filters.",
  },
} as const;
