export const studentLayoutStrings = {
  defaultBrandTitle: "Visa House",
  defaultBrandSubtitle: "Student Portal",
  instituteStudent: "Institute Student",
  directStudent: "Direct Student",
  menu: {
    mainMenu: "MAIN MENU",
    settings: "SETTINGS",
    dashboard: "Dashboard",
    plansAndUpgrades: "Plans & Upgrades",
    myTests: "My Tests",
    myTestHistory: "My Test History",
    progress: "Progress",
    supportSection: "SUPPORT",
    support: "Raise a Query",
    myProfile: "My Profile",
    activeSessions: "Active Sessions",
    changePassword: "Change Password",
  },
  notificationEyebrow: "Student updates",
} as const;
