export const gstRatesStrings = {
  title: "GST Master",
  subtitle: "Manage GST tax rates, percentage, inclusive/exclusive calculation type, and default status",
  createBtn: "Add GST Rate",
  editBtn: "Edit",
  deleteBtn: "Delete",
  toggleActive: "Toggle Active",
  loading: "Loading GST rates...",
  loadError: "Failed to load GST rates. Please try again.",
  saveError: "Failed to save GST rate.",
  deleteConfirm: "Are you sure you want to delete this GST rate? Plans referencing this rate may be affected.",
  deleteConfirmDefault: "This is the default GST rate used across pricing. Deleting it may affect plans that reference it. Are you sure you want to delete it?",
  deleteError: "Failed to delete GST rate.",
  confirm: {
    toggle: (action: string, name: string, isDefault: boolean) =>
      `Are you sure you want to ${action} GST rate "${name}"?${isDefault ? " This is the default rate used across pricing - deactivating it may affect plans that rely on a default." : ""}`,
    activateTitle: "Activate GST Rate",
    deactivateTitle: "Deactivate GST Rate",
  },
  table: {
    name: "Rate Name",
    percentage: "Percentage (%)",
    taxType: "Tax Calculation Type",
    status: "Status",
    default: "Default",
    actions: "Actions",
    inclusive: "Inclusive (Included in Price)",
    exclusive: "Exclusive (Added on Top)",
    active: "Active",
    inactive: "Inactive",
  },
  modal: {
    addTitle: "Add New GST Rate",
    editTitle: "Edit GST Rate",
    nameLabel: "Rate Name",
    namePlaceholder: "e.g. Standard GST (18%)",
    percentageLabel: "Percentage (%)",
    percentagePlaceholder: "e.g. 18.00",
    taxTypeLabel: "Tax Calculation Type",
    isExclusive: "Exclusive (Tax added on top of base price)",
    isInclusive: "Inclusive (Tax included inside total price)",
    isActiveLabel: "Active (Available for plan selection)",
    isDefaultLabel: "Set as Default GST Rate",
    saveBtn: "Save GST Rate",
    savingBtn: "Saving...",
    cancelBtn: "Cancel",
  },
};
