export const demoAccountsStrings = {
  createdModal: {
    title: "Demo account created",
    hint: "Share these credentials with the prospect now — the password won't be shown again.",
    email: "Email",
    temporaryPassword: "Temporary password",
    copied: "Copied!",
    copyPassword: "Copy password",
    done: "Done",
  },
  form: {
    heading: "New Demo Account",
    description: "Set up a temporary trial environment.",
    instituteName: "Prospective institute name",
    instituteNamePlaceholder: "e.g. Acme IELTS Prep",
    demoAdminHeading: "Demo Administrator",
    adminEmail: "Admin email",
    adminEmailPlaceholder: "admin@prospect.com",
    firstName: "First name",
    lastName: "Last name",
    durationDays: "Duration (days)",
    courseLimit: "Course limit",
    testLimit: "Test limit",
    creating: "Creating...",
    create: "Create Demo Account",
  },
  searchPlaceholder: "Search demo institute...",
  stateFilter: {
    allStates: "All states",
    active: "Active",
    expired: "Expired",
    converted: "Converted",
  },
  exportPdf: "Export PDF",
  exportExcel: "Export Excel",
  cancel: "Cancel",
  newDemo: "New Demo",
  loading: "Loading...",
  table: {
    institute: "Institute",
    limits: "Limits (Courses / Tests)",
    expires: "Expires",
    daysRemaining: "Days Remaining",
    state: "State",
    empty: "No demo accounts found.",
    coursesTestsSuffix: (courses: number, tests: number) => `${courses} courses / ${tests} tests`,
  },
  errors: {
    load: "Failed to load demo accounts.",
    create: "Failed to create demo account.",
  },
  pdf: {
    header: "IELTS LMS — Institute Demo Accounts Report",
    generatedPrefix: "Generated:",
    columns: ["#", "Institute Name", "Limits (Courses/Tests)", "Expires", "Days Remaining", "State"],
  },
  excel: {
    sheetName: "Demo Accounts",
    columns: ["#", "Institute Name", "Course Limit", "Test Limit", "Duration (Days)", "Expires At", "Days Remaining", "State"],
  },
} as const;
