"""remove pricing and validity from voucher types

Revision ID: 46e5c817bb04
Revises: 0059
Create Date: 2026-08-03 00:16:17.091830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46e5c817bb04'
down_revision: Union[str, None] = '0059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voucher_types', 'default_price')
    op.drop_column('voucher_types', 'default_validity_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voucher_types', sa.Column('default_validity_days', mysql.INTEGER(), server_default=sa.text("'180'"), autoincrement=False, nullable=False))
    op.add_column('voucher_types', sa.Column('default_price', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False))
    # ### end Alembic commands ###
