export const revenueDashboardStrings = {
  title: "Revenue Analytics",
  subtitle: "Financial performance breakdown across B2B institutes and B2C direct students.",
  allInstitutes: "All institutes",
  searchInstitute: "Search institute...",
  dateFrom: "From Date",
  dateTo: "To Date",
  dateSeparator: "to",
  resetFilters: "Reset filters",
  exportPdf: "Export PDF",
  exportExcel: "Export Excel",
  resultCount: {
    showing: "Showing",
    transaction: "transaction",
    transactions: "transactions",
  },
  loading: "Loading...",
  kpi: {
    totalRevenue: "Total Revenue",
    b2b: "B2B (Institutes)",
    b2c: "B2C (Direct)",
    totalDue: "Total Due",
    transactions: "Transactions",
  },
  charts: {
    byInstituteAriaLabel: "Revenue by Institute",
    byInstituteEmpty: "No revenue recorded yet.",
    byMonthAriaLabel: "Revenue by Month",
    byMonthEmpty: "No monthly data.",
    txnsSuffix: "txns",
  },
  duesPanel: {
    title: "Outstanding Dues",
    description: "Invoices with remaining due amounts.",
    institute: "Institute",
    invoice: "Invoice",
    total: "Total",
    paid: "Paid",
    dueAmount: "Due Amount",
    action: "Action",
    empty: "No outstanding dues. All accounts clear!",
    directStudent: "Direct Student",
    notAvailable: "N/A",
    viewInvoice: "View Invoice",
  },
  errors: {
    load: "Failed to load revenue summary.",
  },
  pdf: {
    header: "IELTS LMS — Financial & Revenue Summary Report",
    generatedPrefix: "Generated:",
    kpiOverview: "KPI Overview:",
    kpiLine: (total: string, b2b: string, b2c: string, due: string, count: number) =>
      `Total Revenue: ${total}   |   B2B: ${b2b}   |   B2C: ${b2c}   |   Total Due: ${due}   |   Transactions: ${count}`,
    columns: ["#", "Institute Name", "Revenue Amount", "Transaction Count"],
  },
  excel: {
    sheetName: "Revenue Summary",
    metricSummary: "Metric Summary",
    totalRevenue: "Total Revenue",
    b2bInstitutes: "B2B (Institutes)",
    b2cDirect: "B2C (Direct)",
    totalDue: "Total Due",
    totalTransactions: "Total Transactions",
    revenueByInstitute: "Revenue By Institute",
    revenueByMonth: "Revenue By Month",
    columns: ["#", "Institute Name", "Revenue Total", "Transactions"],
    monthColumns: ["#", "Month", "Revenue Total", "Transactions"],
  },
} as const;
