export const registerStrings = {
  brandName: "Visa House",
  brandTag: "Language CERT",
  createAccount: "account.",
  subtitle: "Sign up as a student to browse and access Language CERT courses.",
  firstNameLabel: "First name",
  firstNamePlaceholder: "First name",
  lastNameLabel: "Last name",
  lastNamePlaceholder: "Last name",
  emailLabel: "Email address",
  emailPlaceholder: "name@example.com",
  passwordLabel: "Password",
  passwordPlaceholder: "Create a password",
  submitBusy: "Creating account...",
  submitLabel: "Create account →",
  googleSignupLabel: "Sign up with Google",
  googleSignupBusy: "Opening Google...",
  alreadyHaveAccount: "Already have an account? ",
  signInLink: "Sign in",
  welcomeToastMessage: "Your account is ready.",
  welcomeToastTitle: "Welcome",
  errorFallback: "Unable to create your account. Please try again.",
  errorTitle: "Sign Up Failed",
  otpTitle: "Verify Your Email",
  otpDescription: "We sent a 6-digit verification code to your email. Please enter it below to activate your account.",
  otpLabel: "Verification Code",
  otpPlaceholder: "Enter 6-digit code",
  otpVerifyBusy: "Verifying...",
  otpVerifyLabel: "Verify Email",
  otpCancelLabel: "Cancel",
  otpInvalidToken: "Invalid session token received.",
  otpInvalidResponse: "Server required OTP but did not provide a challenge ID.",
  otpSentToast: "Verification code sent to your email.",
  otpSentTitle: "Check Your Email",
  otpResendLabel: "Resend Code",
  otpResendingLabel: "Sending...",
  otpResendCooldown: (seconds: number) => `Resend in ${seconds}s`,
  otpResentToast: "A new verification code has been sent to your email.",
  otpExpiresIn: (time: string) => `Code expires in ${time}`,
  otpExpired: "Code expired. Please request a new code.",
  genericAuthError: "An unexpected error occurred during verification.",
};
