export const registerStrings = {
  brandName: "Visa House",
  brandTag: "IELTS LMS",
  createAccount: "account.",
  subtitle: "Sign up as a student to browse and access IELTS courses.",
  firstNameLabel: "First name",
  firstNamePlaceholder: "First name",
  lastNameLabel: "Last name",
  lastNamePlaceholder: "Last name",
  emailLabel: "Email address",
  emailPlaceholder: "name@example.com",
  passwordLabel: "Password",
  passwordPlaceholder: "Create a password",
  submitBusy: "Creating account...",
  submitLabel: "Create account →",
  googleSignupLabel: "Sign up with Google",
  googleSignupBusy: "Opening Google...",
  alreadyHaveAccount: "Already have an account? ",
  signInLink: "Sign in",
  welcomeToastMessage: "Your account is ready.",
  welcomeToastTitle: "Welcome",
  errorFallback: "Unable to create your account. Please try again.",
  errorTitle: "Sign Up Failed",
};
