export const studentPurchaseHistoryStrings = {
  eyebrow: "BILLING & TRANSACTIONS",
  title: "Purchase History",
  subtitle: "Track your plan subscriptions, download tax invoices, and monitor access validity.",
  loading: "Loading purchase history...",
  loadError: "Failed to load purchase history. Please try refreshing.",
  stats: {
    totalBilled: "Total Spent",
    totalPurchases: "Total Orders",
    activePlan: "Active Access",
    noActive: "No Active Plan",
  },
  filters: {
    searchPlaceholder: "Search by Invoice # or Plan name...",
    allStatuses: "All Payment Statuses",
    allSubStatuses: "All Access States",
  },
  empty: {
    title: "No Purchase Records Found",
    description: "No purchase records matched your selected filters or you have not purchased a plan yet.",
    exploreBtn: "Browse Plans & Upgrades",
    clearFilters: "Clear Filters",
  },
  table: {
    invoice: "Invoice #",
    plan: "Plan Details",
    amount: "Amount Billed",
    status: "Payment Status",
    validity: "Validity & Access Range",
    date: "Purchase Date",
    action: "Invoice",
    viewInvoice: "View Invoice",
  },
  status: {
    paid: "Paid",
    pending: "Pending",
    failed: "Failed",
    partial: "Partial",
    refunded: "Refunded",
  },
  subStatus: {
    active: "Active",
    expired: "Expired",
    grace: "Grace Period",
    scheduled: "Scheduled",
  },
  invoiceModal: {
    title: "Tax Invoice & Official Receipt",
    issuedBy: "Issued By",
    companyName: "Visa House Language CERT",
    companyTagline: "Official Direct Student Subscription Receipt",
    billedTo: "Billed To",
    invoiceNo: "Invoice Number",
    paymentDate: "Payment Date",
    paymentStatus: "Payment Status",
    paymentMethod: "Payment Method",
    gatewayRef: "Gateway Ref",
    itemDescription: "Item & Description",
    duration: "Validity",
    amount: "Price",
    subtotal: "Subtotal",
    discount: "Coupon Discount",
    totalPaid: "Total Paid",
    subscriptionValidity: "Subscription Access Period",
    from: "Valid From",
    to: "Valid Until",
    downloadPdf: "Download PDF",
    printInvoice: "Print Invoice",
    close: "Close",
  },
};
