export const instituteLayoutStrings = {
  brandTitle: "LanguageCert",
  brandSubtitle: "Institute Admin",
  roleLabel: "Institute Admin",
  notificationEyebrow: "Institute updates",
  menu: {
    institute: "INSTITUTE",
    dashboard: "Dashboard",
    students: "Students",
    announcements: "Announcements",
    notifications: "Notifications",
    instructors: "Instructors",
    branding: "Branding",
    subscription: "Subscription",
    supportSection: "SUPPORT",
    support: "Raise a Query",
    supportTickets: "Support Inbox",
    settings: "SETTINGS",
    myProfile: "My Profile",
    activeSessions: "Active Sessions",
    changePassword: "Change Password",
  },
} as const;
