export const gradingDetailStrings = {
  loading: "Loading...",
  errors: {
    load: "Failed to load this submission.",
    queueAction: (action: string) => `Failed to ${action} this submission.`,
    resolve: "Failed to resolve the reevaluation.",
  },
  claim: "Claim submission",
  release: "Release",
  backToQueue: "Back to queue",
  cefrNote: {
    title: "CEFR Companion Volume 2020",
    body: "Human examiner approval is required for every subjective result. AI suggestions are advisory and retained separately for audit.",
  },
  readOnly: {
    title: "Read only",
    claimedBy: (name: string) => `This submission is claimed by ${name}.`,
  },
  reevaluation: {
    badge: "Reevaluation",
    title: "Student review request",
    resolutionNoteLabel: "Resolution note",
    resolutionNotePlaceholder: "Explain what was reviewed and whether the result changed.",
    resolve: "Resolve after review",
    reject: "Reject request",
  },
  flags: {
    title: "Proctoring flags",
    description: "Informational signals recorded during this attempt.",
  },
  part: {
    aiDraft: "AI rubric draft",
    priorAiTitle: "This part was AI-graded earlier",
    priorAiSubtitle:
      "Values below are the model's evaluation. Review each mark against the rubric, override anything you disagree with, then confirm.",
    priorAiMarksHeading: "AI marks",
    priorAiCommentHeading: "AI comment",
    priorAiAccept: "Use these values",
    priorAiChip: "AI graded",
    rubricSticky: {
      title: "CEFR criteria",
      subtitle: "Follows the part you are grading.",
      close: "Hide rubric",
      show: "Show rubric",
    },
    rubricSideHint: "Score the rubric in the panel on the right, then Save.",
    generating: "Generating...",
    graded: "Graded",
    draftSaved: "Draft saved",
    draftHint: "Saved as a draft. Nothing is published to the student until you submit the full test below.",
    aiDisabledHint: "AI assistance is disabled. A Super Admin can configure the evaluator in Platform Settings.",
    speakingHint: "Speaking recordings require human listening and are not sent to the text evaluator.",
    noResponse: "No response submitted.",
    aiBannerTitle: "Advisory AI draft",
    aiBannerConfidence: (confidence: number) =>
      `Confidence ${confidence}%. Review every mark before saving; the model cannot publish this result.`,
    noRationale: "No rationale returned.",
    rubricSummary: (count: number) => `CEFR assessment criteria - ${count} criteria`,
    cefrAnchorAriaLabel: "CEFR scoring anchors",
    markLabel: (max: number) => `Mark from 0 to ${max}`,
    commentLabel: "Examiner comment (optional)",
    saving: "Saving...",
    saveDraft: "Save draft",
    confirmEvaluation: "Confirm human CEFR evaluation",
    aiSuccessMessage: "AI draft loaded for human review.",
    aiSuccessTitle: "Draft Ready",
    aiErrorMessage: "Failed to generate an assisted evaluation.",
    aiErrorTitle: "AI Assistance Failed",
    savedTitle: "Saved",
    gradedMessage: (title: string) => `${title} graded.`,
    draftSavedMessage: (title: string) => `${title} draft saved.`,
    saveErrorMessage: "Failed to save the grade.",
    saveErrorTitle: "Grading Failed",
  },
  submitFullTest: {
    title: "Submit full test",
    description: "Publishes every part's grade to the student at once. Nothing is released until every part below has a complete draft.",
    readyCount: (ready: number, total: number) => `${ready} of ${total} parts scored`,
    action: "Submit full test",
    submitting: "Submitting...",
    successTitle: "Submitted",
    successMessage: "The full test has been graded and released to the student.",
    errorTitle: "Submit Failed",
    errorMessage: "Failed to submit the full test.",
  },
  completion: {
    title: "Evaluation Completed!",
    subtitle: "You have successfully graded all subjective parts for this test submission.",
    nextReview: "Grade Next Submission",
    backToQueue: "Back to Grading Queue",
    goHome: "Go to Dashboard",
  },
  levels: {
    notScored: "Not scored",
    c2: "C2",
    c1: "C1",
    b2: "B2",
    b1: "B1",
    belowB1: "Below B1",
  },
} as const;
