export const testRunnerStrings = {
  sectionLabels: {
    listening: "Listening",
    reading: "Reading",
    writing: "Writing",
    speaking: "Speaking",
  },
  desktopRequired: {
    heading: "Computer Required",
    description: "To perform this Language CERT test, you must use a desktop or laptop computer. Mobile and tablet devices are not supported for timed exam attempts.",
    backToDashboard: "Back to Dashboard",
  },
  loadError: "Unable to load this test attempt.",
  loading: "Loading your test...",
  errors: {
    submit: "Failed to submit your test.",
    submitTitle: "Submit Failed",
    part: "Unable to load this test part.",
    partTitle: "Part Locked",
    save: "Failed to save your answer.",
    saveTitle: "Save Failed",
    attemptExpired: "This attempt has expired and can no longer be saved.",
    recordingUpload: "Failed to upload your recording.",
    emptyRecording: "No sound was captured. Check your microphone and record the answer again.",
    recordingUploadTitle: "Upload Failed",
    microphoneBlocked: "Microphone access is required to record a Speaking answer.",
    microphoneBlockedTitle: "Microphone Blocked",
    microphoneBlockedRecovery: "Microphone access was blocked. Click the lock/camera icon in your browser's address bar to allow it, then try again.",
    fullscreenRequired: "Allow full-screen access to continue this timed test.",
    fullscreenRequiredTitle: "Full Screen Required",
  },
  security: {
    eyebrow: "Secure Final Test",
    heading: "Complete the security check",
    description: "The timer starts only after the first successful check. Camera, microphone, screen share, and full screen must remain active.",
    cameraPreviewAlt: "Camera preview",
    cameraActive: "Camera active",
    cameraPreview: "Camera preview",
    checksAriaLabel: "Required security controls",
    camera: "Camera",
    microphone: "Microphone",
    fullScreen: "Full screen",
    screenShare: "Screen share",
    ready: "Ready",
    required: "Required",
    concurrentTabAlert: "Close the other Final Test tab before continuing.",
    privacyNote: "Media remains active for supervision during the attempt. Permission indicators stay visible in your browser.",
    activating: "Activating security controls...",
    enterFullscreenAndContinue: "Enter full screen and continue",
    enableAllAndStart: "Enable all and start Final Test",
    enableAllAndRestore: "Enable all and restore session",
    securityCheckContext: "Final Test security check",
    timeLeft: "Time left",
    rulesHeading: "Final Test rules",
    rules: [
      "Do not minimize the browser, switch tabs, switch apps, or leave the test window.",
      "Keep camera, microphone, screen share, and full screen active until submission.",
      "Do not copy, cut, paste, or use the browser context menu during reading or listening tests (copy-paste is allowed for writing tasks).",
      "Two warnings are allowed for leaving the secured browser state.",
      "On the third violation, the test is automatically submitted and marked for rule violations.",
    ],
    consentLabel: "I understand and agree to follow these Final Test security rules.",
    consentRequired: "Accept the Final Test security rules before starting.",
    violationWarningTitle: (count: number, limit: number) => `Security warning ${count} of ${limit}`,
    violationWarningBody: "You moved out of the secured test environment. Return to the test immediately and keep the browser in full screen.",
    violationFinalTitle: "Final Test auto submitted",
    violationFinalBody: "You have not followed the test instructions. The test was auto submitted and marked for violations of rules.",
    viewResult: "View result",
    continueTest: "Continue test",
    errors: {
      browserUnsupported: "This browser does not support the secure media check.",
      cameraMicRequired: "Both a working camera and microphone are required.",
      screenShareRequired: "Screen sharing is required. Share your entire screen before continuing.",
      mediaMustRemainActive: "Camera, microphone, and screen share must remain active.",
      fullscreenAfterCameraMic: "Camera and microphone are active. Enter full screen to continue the Speaking interview.",
      fullscreenAfterMedia: "Camera, microphone, and screen share are active. Click Enter full screen and continue to finish the security check.",
      generic: "The security check could not be completed.",
      sessionRestoreNeeded: "The secure attempt session needs to be restored.",
    },
  },
  header: {
    timeLeft: "Time Left",
    previous: "Previous",
    next: "Next",
    partNavigationAriaLabel: "Move between test parts",
    navigationLocked: "Navigation is locked until Listening is complete, while audio plays, or while Speaking is running",
    secureBadge: "Secure",
    secureBadgeTitle: "Final Test security controls are active",
    devExitFullscreen: "Exit full screen (dev)",
    devSkipPart: "Skip part (dev)",
  },
  nav: {
    testSectionsAriaLabel: "Test sections",
    progress: "Progress",
    navigationLocked: "Navigation is locked until Listening is complete, while audio plays, or while Speaking is running",
  },
  sourcePane: {
    sourceMaterial: "Source material",
    partInstructions: "Part instructions",
    passagePrefix: "Passage",
    taskSuffix: "task",
    defaultInstructions: "Read each prompt carefully and complete every item in this part. Your answers save automatically.",
  },
  questionPane: {
    questionsSuffix: "questions",
    instructions: "Choose or enter the best answer for each question.",
  },
  question: {
    label: (index: number) => `Question ${index}`,
    saving: "Saving...",
    wordsSuffix: "words",
    stopRecording: "Stop recording",
    reRecordAnswer: "Re-record answer",
    recordAnswer: "Record your answer",
  },
  speakingInterview: {
    testTime: "Test time remaining",
    partProgress: (current: number, total: number) => `Speaking part ${current} of ${total}`,
    questionProgress: (current: number, total: number) => `Prompt ${current} of ${total}`,
    prompt: "Examiner prompt",
    preparation: "Preparation time",
    recording: "Recording time left",
    responseLimit: "Response limit",
    playingQuestion: "Playing Question...",
    waitingForExaminerAudio: "Waiting for examiner audio…",
    recordingStartsAutomatically: "Preparation — recording starts automatically",
    preparingNow: (seconds: number) => `Preparation - recording starts in ${seconds}s`,
    startingRecording: "Starting your recording...",
    recordingNow: "Your answer is being recorded.",
    saving: "Saving response",
    saved: "Response saved",
    ready: (seconds: number) => `${seconds} seconds of preparation before recording begins.`,
    startResponse: "Start response",
    recordAnswer: "Record Answer",
    submitAnswer: "Submit Answer",
    submittingTest: "All speaking parts complete - submitting your test...",
    submitResponse: "Submit response",
    savingResponse: "Saving response...",
    /* Shown only while a prompt's preparation time is running: the candidate
       may start speaking before the clock is out. */
    continueToRecording: "Continue",
  },
  footer: {
    answeredOf: (answered: number, total: number) => `${answered} of ${total} answered`,
    endExam: "End exam",
    continueToSpeaking: "Continue to Speaking",
    submitting: "Submitting...",
    submitTest: "Submit test",
  },
  submitModal: {
    heading: "Submit this test?",
    speakingHeading: "Start Speaking now?",
    summary: (answered: number, total: number) => `You've answered ${answered} of ${total} questions.`,
    standardWarning: "You won't be able to change your answers after submitting.",
    speakingWarning: "The Listening, Reading and Writing paper will close now. Speaking will start immediately.",
    keepWorking: "Keep working",
    startSpeakingNow: "Start Speaking now",
    submitNow: "Submit now",
    continueToSpeaking: "Continue to Speaking",
  },
  fullscreenGate: {
    finalTest: "Final Test",
    fullMockTest: "Full Mock Test",
    heading: "Continue in full screen",
    description: "Your timed session is active. Enter full screen to view and complete the assessment.",
    restoreHeading: "Restore exam permissions",
    restoreDescription: "Camera, microphone, screen share, and full screen must be active before the test can continue.",
    enterFullscreen: "Enter full screen",
    restoreControls: "Restore permissions and continue",
  },
} as const;
