import type { Tab } from "./types";

// Routine, content-oriented settings first; higher-risk tabs (auth bypass,
// database migrations, bulk seed writes) are grouped at the end and flagged
// with a warning icon in DeveloperSettings/index.tsx - see `dangerousTabs`.
export const tabOrder: Tab[] = [
  "hero-socials",
  "smtp",
  "ai",
  "google-oauth",
  "payment-gateways",
  "otp",
  "maintenance",
];

/** Tabs that can bypass auth, mutate the database in bulk, or run migrations. */
export const dangerousTabs: Tab[] = ["otp", "maintenance"];

export const tabLabels: Record<Tab, string> = {
  "hero-socials": "Hero & Socials",
  smtp: "SMTP",
  ai: "AI Evaluation",
  "google-oauth": "Google Sign-In (OAuth)",
  "payment-gateways": "Payment Gateways",
  otp: "Static OTP (Testing)",
  maintenance: "Maintenance & Backups",
};


export const developerSettingsStrings = {
  pageTitle: "Platform Settings",
  otp: {
    title: "Static Testing OTP Controls",
    description: "Toggle static testing OTP for all accounts across the platform. When enabled (ON by default), registration, login, and password verification codes default to your static OTP (default: 123456) without requiring real SMTP email delivery.",
    enabledLabel: "Enable Static Testing OTP (ON by Default)",
    enabledHint: "Recommended for local testing, staging, and demoing features without needing real email inbox delivery.",
    codeLabel: "Static OTP Code",
    codePlaceholder: "123456",
    saveLabel: "Save Static OTP Settings",
    saveSuccess: "Static OTP settings updated successfully!",
    saveError: "Failed to update Static OTP settings.",
    statusActive: "⚡ Static Testing OTP Active",
    statusInactive: "📧 Real Email Delivery Active",
    dangerBannerTitle: "Platform-wide authentication bypass",
    dangerBannerBody: "When enabled, any account - Students, Instructors, Institute Admins, and Super Admins - can log in using a shared static testing code instead of a real one-time code. Do not enable this in production.",
    enableConfirmTitle: "Enable Global Testing Mode?",
    enableConfirmMessage: "This lets anyone log in to any account on the platform using a shared static code, bypassing real OTP verification. Only enable this on a testing or staging environment - never in production. Continue?",
  },
  smtp: {
    title: "SMTP Delivery",
    description: "Configure outbound mail delivery and send a test email.",
    hostLabel: "Host",
    hostPlaceholder: "smtp.example.com",
    portLabel: "Port",
    portPlaceholder: "587",
    usernameLabel: "Username",
    passwordLabel: "Password",
    passwordPlaceholder: "stored encrypted",
    encryptionLabel: "Encryption",
    encryptionOptions: [
      { value: "tls", label: "TLS (STARTTLS)" },
      { value: "ssl", label: "SSL" },
      { value: "none", label: "None" },
    ],
    fromAddressLabel: "From address",
    fromAddressPlaceholder: "noreply@example.com",
    saveLabel: "Save SMTP Settings",
    testToPlaceholder: "you@example.com",
    sendTestLabel: "Send test email",
    saveError: "Failed to save SMTP settings.",
    testError: "Test email failed.",
    savedNotice: "SMTP settings saved.",
    testSentNotice: (to: string) => `Test email sent to ${to}.`,
  },
  fcm: {
    title: "Firebase FCM",
    description: "Manage push notification credentials and device-token testing.",
    readyBadge: "Ready",
    missingBadge: "Missing",
    configuredHint: "Service account configured",
    notConfiguredHint: "No service account uploaded yet.",
    projectIdLabel: "Project ID (optional - detected from JSON if empty)",
    projectIdPlaceholder: "my-firebase-project",
    saJsonLabel: "Service account JSON",
    saJsonReplaceHint: "(paste to replace)",
    saJsonPlaceholder: '{"type": "service_account", "project_id": "...", ...}',
    webConfigTitle: "Web push config",
    webConfigHint: "Needed for browsers to register for push - find these under Project settings → General → Your apps (Web) and Cloud Messaging → Web Push certificates in the Firebase console.",
    webConfiguredHint: "Web push is fully configured - browsers can register for notifications.",
    webNotConfiguredHint: "Web push fields incomplete - browsers cannot register until all are filled in.",
    webApiKeyLabel: "Web API key",
    webAppIdLabel: "Web app ID",
    webMessagingSenderIdLabel: "Messaging sender ID",
    webVapidKeyLabel: "VAPID key (Web Push certificate)",
    saveLabel: "Save FCM Settings",
    deviceTokenPlaceholder: "Device token (optional - validates credentials if empty)",
    sendTestLabel: "Send test notification",
    validateLabel: "Validate credentials",
    saveError: "Failed to save FCM settings.",
    testError: "FCM test failed.",
    savedNotice: "FCM settings saved.",
    testSentNotice: "Test notification sent.",
    testValidNotice: (projectId: string) => `Credentials valid - token obtained for project ${projectId}.`,
  },
  ai: {
    title: "Human-reviewed AI evaluation",
    description: "Configure a JSON rubric evaluator for advisory Writing drafts.",
    readyBadge: "Ready",
    notConfiguredBadge: "Not configured",
    enableLabel: "Enable AI rubric suggestions",
    providerLabel: "Provider label",
    modelLabel: "Model",
    endpointLabel: "Evaluator endpoint",
    endpointPlaceholder: "https://evaluator.example.com/grade",
    apiKeyLabel: "API key",
    apiKeyPlaceholder: "stored encrypted",
    apiKeyActiveBadge: "Saved & Active (Encrypted at Rest)",
    saveBusy: "Saving...",
    saveLabel: "Save AI settings",
    saveError: "Failed to save AI evaluation settings.",
    savedNotice: "AI evaluation settings saved.",
  },
  maintenance: {
    title: "Maintenance Actions",
    description: "Run migrations, clear cache, and check storage links.",
    migrate: { busy: "Running...", idle: "Run data migration", label: "Data migration" },
    migrateConfirmTitle: "Run Data Migration",
    migrateConfirmMessage: "This runs a real database migration against the live platform database. It can alter schema or data and cannot be undone. Are you sure you want to continue?",
    clearCache: { busy: "Clearing...", idle: "Clear cache", label: "Clear cache" },
    storageLink: { busy: "Checking...", idle: "Storage link", label: "Storage link" },
    jobTimeoutMessage: (jobId: number) => `Job #${jobId} did not finish in time - check again later.`,
    jobEnqueuedMessage: (label: string, jobId: number) => `${label} enqueued as job #${jobId}...`,
    jobRunningMessage: (jobId: number, status: string) => `Job #${jobId} is ${status}...`,
    jobDoneMessage: (jobId: number, result: string) => `Job #${jobId} finished:\n${result}`,
    jobFailedMessage: (jobId: number, result: string) => `Job #${jobId} failed:\n${result}`,
    genericResultMessage: (label: string, data: string) => `${label}:\n${data}`,
    actionFailed: (label: string) => `${label} failed.`,
  },
  backups: {
    scheduleTitle: "Backup Schedule",
    scheduleDescription: "Set backup cadence, retention, and trigger an immediate backup.",
    scheduleLabel: "Schedule",
    scheduleOptions: [
      { value: "none", label: "Disabled" },
      { value: "daily", label: "Daily" },
      { value: "weekly", label: "Weekly" },
    ],
    retentionLabel: "Retention (backups kept)",
    saveSettingsLabel: "Save settings",
    backupNowLabel: "Backup now",
    saveError: "Failed to save backup settings.",
    savedNotice: "Backup settings saved.",
    backupStartFailedError: "Failed to start backup.",
    backupStartedNotice: (jobId: number) => `Backup job #${jobId} started - refresh the list shortly.`,
    downloadFailedError: "Download failed.",
    restorePromptPrefix: "This OVERWRITES the current database with",
    restorePromptSuffix: "Type RESTORE to confirm:",
    restoreFailedError: "Restore failed.",
    deleteConfirmMessage: (filename: string) => `Are you sure you want to delete backup file "${filename}"?`,
    deleteConfirmTitle: "Delete Backup",
    deleteFailedError: "Delete failed.",
    filesTitle: "Backup Files",
    filesDescription: "Download, restore, or delete generated backup artifacts.",
    tableHeaders: { file: "File", size: "Size", kind: "Kind", status: "Status", created: "Created", actions: "Actions" },
    emptyMessage: "No backups yet.",
  },
  slider: {
    title: "Home & Login Hero Sliders",
    description: "Manage the hero carousels shown to logged-out visitors: the public home page hero and the login/register side panel. Changes are stored on the server, so every visitor sees them.",
    loadError: "Failed to load hero slides.",
    homeHint: "These slides drive the carousel at the top of the public home page - background image, badge, heading, description, both buttons and the stat chips.",
    loginHint: "These slides drive the showcase panel beside the login and register forms - image, badge, title and subtitle.",
    resetLabel: "Reset to Defaults",
    resetToastMessage: "Hero slides reset to defaults.",
    resetToastTitle: "Reset Done",
    currentSlidesTitle: "Current slides",
    currentSlidesDescription: "Edit the copy and images, reorder, hide or remove slides.",
    badgePlaceholder: "Badge text",
    titlePlaceholder: "Slide Title",
    subtitlePlaceholder: "Subtitle",
    imageUrlPlaceholder: "Image URL",
    removeLabel: "Remove",
    addSectionTitle: "Add Login Hero Slide",
    addSectionDescription: "Create another slide for the login and register hero.",
    addHomeSectionTitle: "Add Home Page Hero Slide",
    addHomeSectionDescription: "Create another slide for the public home page hero carousel.",
    imageUrlLabel: "Image URL",
    imageUrlInputPlaceholder: "https://images.unsplash.com/...",
    titleLabel: "Title",
    headingLabel: "Heading",
    headingHint: "Line breaks are preserved - press Enter to split the heading across lines.",
    titleInputPlaceholder: "Slide Heading",
    highlightLabel: "Highlight (accent-coloured tail of the heading)",
    highlightPlaceholder: " & Instant Scoring.",
    subtitleLabel: "Subtitle",
    descLabel: "Description",
    subtitleInputPlaceholder: "Slide Subtitle",
    badgeLabel: "Badge Text",
    badgeInputPlaceholder: "e.g. ACADEMIC EXCELLENCE",
    ctaTextLabel: "Primary Button Text",
    ctaLinkLabel: "Primary Button Link",
    altTextLabel: "Secondary Button Text",
    altLinkLabel: "Secondary Button Link",
    statsLabel: "Stat Chips",
    addStatLabel: "Add Stat",
    statsAfterCreateHint: "Stat chips can be added to the slide once it has been created.",
    addLabel: "Add Slide",
    defaultSubtitle: "Educational Language CERT platform slide.",
    defaultBadge: "Language CERT",
    addedToastMessage: "New hero slide added and live.",
    addedToastTitle: "Slide Added",
  },
  contact: {
    title: "Contact Info & Social Links",
    description: "Configure the public /contact page's info cards and the site footer's social media icons.",
    infoTitle: "Contact Info Cards",
    infoDescription: "Shown as the Email Us / Call Sales / Support Portal / Head Office cards on the public Contact page.",
    emailLabel: "Support Email",
    emailNotePlaceholder: "e.g. Replies within 1 working day",
    phoneLabel: "Sales Phone",
    phoneNotePlaceholder: "e.g. Mon–Fri · 10am to 7pm IST",
    supportUrlLabel: "Support Portal URL",
    supportNotePlaceholder: "e.g. Existing partners only",
    officeNameLabel: "Office / Company Name",
    officeAddressLabel: "Office Address",
    officeAddressPlaceholder: "One address line per row",
    headOfficeTitle: "Amritsar Head Office",
    headOfficeNameLabel: "Head Office Display Name",
    headOfficeAddressLabel: "Head Office Full Address",
    headOfficeMapLinkLabel: "Head Office Google Maps Link",
    headOfficeMapEmbedLabel: "Head Office Google Maps Embed URL",
    branchOfficeTitle: "Tarn Taran Branch Office",
    branchOfficeNameLabel: "Branch Office Display Name",
    branchOfficeAddressLabel: "Branch Office Full Address",
    branchOfficeMapLinkLabel: "Branch Office Google Maps Link",
    branchOfficeMapEmbedLabel: "Branch Office Google Maps Embed URL",
    saveInfoLabel: "Save Contact Info",
    saveInfoError: "Failed to save contact info.",
    saveInfoSuccess: "Contact info saved.",
    socialTitle: "Social Links",
    socialDescription: "Shown as icons in the footer of every public page. Disabled links are hidden from the public site.",
    currentLinksTitle: "Current Links",
    noLinksMessage: "No social links yet.",
    urlPlaceholder: "https://...",
    removeLabel: "Remove",
    removeError: "Failed to remove social link.",
    updateError: "Failed to update social link.",
    addSectionTitle: "Add Social Link",
    addSectionDescription: "Pick a platform and paste its URL.",
    platformLabel: "Platform",
    addLabel: "Add Link",
    addError: "Failed to add social link.",
    loadError: "Failed to load contact settings.",
    platformLabels: {
      linkedin: "LinkedIn",
      github: "GitHub",
      instagram: "Instagram",
      youtube: "YouTube",
      facebook: "Facebook",
      twitter: "X (Twitter)",
      tiktok: "TikTok",
      website: "Website",
    },
  },
  googleOAuth: {
    title: "Google Sign-In (OAuth) Credentials",
    description: "Configure the Google OAuth Client ID and Secret used for \"Continue with Google\" sign-in and sign-up.",
    saveSuccess: "Google OAuth settings saved successfully!",
    saveError: "Failed to save Google OAuth settings.",
    clientIdLabel: "Client ID",
    clientIdPlaceholder: "xxxxxxxxxx.apps.googleusercontent.com",
    clientSecretLabel: "Client Secret",
    clientSecretPlaceholder: "Enter client secret or leave unchanged",
    redirectUriLabel: "Redirect URI",
    redirectUriPlaceholder: "https://yourdomain.com/api/auth/google/callback",
    redirectUriHint: "Must exactly match an Authorized redirect URI registered for this OAuth client in Google Cloud Console.",
    useSuggestedLabel: "Use this URL",
    callbackUrlBoxLabel: "Suggested Callback URL:",
    copyLabel: "Copy URL",
    copiedLabel: "Copied!",
    saveBtn: "Save Google OAuth Settings",
    configuredBadge: "Configured",
    notConfiguredBadge: "Not Configured",
  },
  paymentGateways: {
    title: "Payment Gateway Credentials & API Keys",
    description: "Configure Razorpay and Stripe API keys, webhook secrets, and enable/disable payment processing for student subscriptions.",
    saveSuccess: "Payment gateway settings saved successfully!",
    saveError: "Failed to save payment gateway settings.",
    razorpayTitle: "Razorpay Gateway (INR / India)",
    razorpayDesc: "Configure Razorpay Key ID and Key Secret for processing payments in India.",
    razorpayEnable: "Enable Razorpay Gateway",
    razorpayKeyIdLabel: "Razorpay Key ID",
    razorpayKeyIdPlaceholder: "rzp_live_...",
    razorpayKeySecretLabel: "Razorpay Key Secret",
    razorpayKeySecretPlaceholder: "Enter secret key or leave unchanged",
    razorpayWebhookSecretLabel: "Razorpay Webhook Secret",
    razorpayWebhookSecretPlaceholder: "Enter webhook secret or leave unchanged",
    stripeTitle: "Stripe Gateway (International / USD)",
    stripeDesc: "Configure Stripe Publishable Key and Secret Key for global payments.",
    stripeEnable: "Enable Stripe Gateway",
    stripePublishableKeyLabel: "Stripe Publishable Key",
    stripePublishableKeyPlaceholder: "pk_live_...",
    stripeSecretKeyLabel: "Stripe Secret Key",
    stripeSecretKeyPlaceholder: "sk_live_...",
    stripeWebhookSecretLabel: "Stripe Webhook Secret",
    stripeWebhookSecretPlaceholder: "whsec_...",
    saveBtn: "Save Gateway Settings",
  },
};
