import type { Tab } from "./types";

export const tabOrder: Tab[] = [
  "typography",
  "otp",
  "slider",
  "contact",
  "smtp",
  "fcm",
  "ai",
  "payment-gateways",
  "maintenance",
  "backups",
  "seed",
];

export const tabLabels: Record<Tab, string> = {
  typography: "Typography & Weights",
  otp: "Static OTP (Testing)",
  slider: "Login Hero Slider",
  contact: "Contact & Social",
  smtp: "SMTP",
  fcm: "Firebase FCM",
  ai: "AI Evaluation",
  "payment-gateways": "Payment Gateways",
  maintenance: "Maintenance",
  backups: "Backups",
  seed: "Seed Data",
};


export const developerSettingsStrings = {
  pageTitle: "Platform Settings",
  otp: {
    title: "Static Testing OTP Controls",
    description: "Toggle static testing OTP for all accounts across the platform. When enabled (ON by default), registration, login, and password verification codes default to your static OTP (default: 123456) without requiring real SMTP email delivery.",
    enabledLabel: "Enable Static Testing OTP (ON by Default)",
    enabledHint: "Recommended for local testing, staging, and demoing features without needing real email inbox delivery.",
    codeLabel: "Static OTP Code",
    codePlaceholder: "123456",
    saveLabel: "Save Static OTP Settings",
    saveSuccess: "Static OTP settings updated successfully!",
    saveError: "Failed to update Static OTP settings.",
    statusActive: "⚡ Static Testing OTP Active",
    statusInactive: "📧 Real Email Delivery Active",
  },
  typography: {
    title: "App Typography & Tag Font Weights",
    description: "Customize the global font family and tag-specific font weights across the platform in real time.",
    fontFamilyLabel: "Global Font Family",
    fontFamilySearchPlaceholder: "Search font family...",
    resetLabel: "Reset to Sleek Defaults",
    sliders: {
      headings: { label: "Headings Weight", helper: "Applies to h1, h2, h3, and section titles." },
      stat: { label: "Dashboard Metric Numbers", helper: "Applies to dashboard KPI and stat values." },
      body: { label: "Body Text & Labels", helper: "Applies to body copy, labels, and compact supporting text." },
    },
    preview: {
      eyebrow: "Live Typography Preview",
      heading: "Good Evening, Super Admin",
      subtitle: "Real-time overview of institutes, subscriptions, and revenue.",
      revenue: "Revenue",
      institutes: "Institutes",
      due: "Due",
    },
  },
  seed: {
    title: "Populate Sample & Demo Seed Data",
    description: "Generate sample Listening, Reading, Writing, Speaking, Full Mock, and Final Test courses for local testing and demos.",
    seedError: "Failed to seed sample data.",
    populateBusy: "Seeding Data...",
    populateIdle: "Populate Seed Data",
    testLoaderLabel: "⚡ Test Global Loader (3.5s)",
    loaderInitMessage: "Initializing 3D glassmorphic loader...",
    loaderTestingOutput: "⚡ Testing 3D Glassmorphic Loader & Dynamic Changing Text...",
    loaderStep1: "Uploading profile assets to storage...",
    loaderStep2: "Syncing database records...",
    loaderDoneOutput: "✓ 3D Glassmorphic Loader test finished successfully!",
    toastSectionTitle: "Floating Global Snackbars (Toast Notifications)",
    toastSectionHint: "Trigger floating snackbars in the top-right corner for quick non-blocking feedback (Success, Failed, Warning, Info).",
    toastButtons: {
      success: "🟢 Success Snackbar",
      error: "🔴 Failed Snackbar",
      warning: "🟡 Warning Snackbar",
      info: "🔵 Info Snackbar",
    },
    toastMessages: {
      success: { message: "Password updated successfully!", title: "Success" },
      error: { message: "Failed to update profile. Please try again.", title: "Action Failed" },
      warning: { message: "Your trial subscription expires in 2 days.", title: "Warning" },
      info: { message: "New platform version v2.4 is available.", title: "Notice" },
    },
  },
  smtp: {
    title: "SMTP Delivery",
    description: "Configure outbound mail delivery and send a test email.",
    hostLabel: "Host",
    hostPlaceholder: "smtp.example.com",
    portLabel: "Port",
    portPlaceholder: "587",
    usernameLabel: "Username",
    passwordLabel: "Password",
    passwordPlaceholder: "stored encrypted",
    encryptionLabel: "Encryption",
    encryptionOptions: [
      { value: "tls", label: "TLS (STARTTLS)" },
      { value: "ssl", label: "SSL" },
      { value: "none", label: "None" },
    ],
    fromAddressLabel: "From address",
    fromAddressPlaceholder: "noreply@example.com",
    saveLabel: "Save SMTP Settings",
    testToPlaceholder: "you@example.com",
    sendTestLabel: "Send test email",
    saveError: "Failed to save SMTP settings.",
    testError: "Test email failed.",
    savedNotice: "SMTP settings saved.",
    testSentNotice: (to: string) => `Test email sent to ${to}.`,
  },
  fcm: {
    title: "Firebase FCM",
    description: "Manage push notification credentials and device-token testing.",
    readyBadge: "Ready",
    missingBadge: "Missing",
    configuredHint: "Service account configured",
    notConfiguredHint: "No service account uploaded yet.",
    projectIdLabel: "Project ID (optional - detected from JSON if empty)",
    projectIdPlaceholder: "my-firebase-project",
    saJsonLabel: "Service account JSON",
    saJsonReplaceHint: "(paste to replace)",
    saJsonPlaceholder: '{"type": "service_account", "project_id": "...", ...}',
    webConfigTitle: "Web push config",
    webConfigHint: "Needed for browsers to register for push - find these under Project settings → General → Your apps (Web) and Cloud Messaging → Web Push certificates in the Firebase console.",
    webConfiguredHint: "Web push is fully configured - browsers can register for notifications.",
    webNotConfiguredHint: "Web push fields incomplete - browsers cannot register until all are filled in.",
    webApiKeyLabel: "Web API key",
    webAppIdLabel: "Web app ID",
    webMessagingSenderIdLabel: "Messaging sender ID",
    webVapidKeyLabel: "VAPID key (Web Push certificate)",
    saveLabel: "Save FCM Settings",
    deviceTokenPlaceholder: "Device token (optional - validates credentials if empty)",
    sendTestLabel: "Send test notification",
    validateLabel: "Validate credentials",
    saveError: "Failed to save FCM settings.",
    testError: "FCM test failed.",
    savedNotice: "FCM settings saved.",
    testSentNotice: "Test notification sent.",
    testValidNotice: (projectId: string) => `Credentials valid - token obtained for project ${projectId}.`,
  },
  ai: {
    title: "Human-reviewed AI evaluation",
    description: "Configure a JSON rubric evaluator for advisory Writing drafts.",
    readyBadge: "Ready",
    notConfiguredBadge: "Not configured",
    enableLabel: "Enable AI rubric suggestions",
    providerLabel: "Provider label",
    modelLabel: "Model",
    endpointLabel: "Evaluator endpoint",
    endpointPlaceholder: "https://evaluator.example.com/grade",
    apiKeyLabel: "API key",
    apiKeyPlaceholder: "stored encrypted",
    apiKeyActiveBadge: "Saved & Active (Encrypted at Rest)",
    saveBusy: "Saving...",
    saveLabel: "Save AI settings",
    saveError: "Failed to save AI evaluation settings.",
    savedNotice: "AI evaluation settings saved.",
  },
  maintenance: {
    title: "Maintenance Actions",
    description: "Run migrations, clear cache, and check storage links.",
    migrate: { busy: "Running...", idle: "Run data migration", label: "Data migration" },
    clearCache: { busy: "Clearing...", idle: "Clear cache", label: "Clear cache" },
    storageLink: { busy: "Checking...", idle: "Storage link", label: "Storage link" },
    jobTimeoutMessage: (jobId: number) => `Job #${jobId} did not finish in time - check again later.`,
    jobEnqueuedMessage: (label: string, jobId: number) => `${label} enqueued as job #${jobId}...`,
    jobRunningMessage: (jobId: number, status: string) => `Job #${jobId} is ${status}...`,
    jobDoneMessage: (jobId: number, result: string) => `Job #${jobId} finished:\n${result}`,
    jobFailedMessage: (jobId: number, result: string) => `Job #${jobId} failed:\n${result}`,
    genericResultMessage: (label: string, data: string) => `${label}:\n${data}`,
    actionFailed: (label: string) => `${label} failed.`,
  },
  backups: {
    scheduleTitle: "Backup Schedule",
    scheduleDescription: "Set backup cadence, retention, and trigger an immediate backup.",
    scheduleLabel: "Schedule",
    scheduleOptions: [
      { value: "none", label: "Disabled" },
      { value: "daily", label: "Daily" },
      { value: "weekly", label: "Weekly" },
    ],
    retentionLabel: "Retention (backups kept)",
    saveSettingsLabel: "Save settings",
    backupNowLabel: "Backup now",
    saveError: "Failed to save backup settings.",
    savedNotice: "Backup settings saved.",
    backupStartFailedError: "Failed to start backup.",
    backupStartedNotice: (jobId: number) => `Backup job #${jobId} started - refresh the list shortly.`,
    downloadFailedError: "Download failed.",
    restorePromptPrefix: "This OVERWRITES the current database with",
    restorePromptSuffix: "Type RESTORE to confirm:",
    restoreFailedError: "Restore failed.",
    deleteConfirmMessage: (filename: string) => `Are you sure you want to delete backup file "${filename}"?`,
    deleteConfirmTitle: "Delete Backup",
    deleteFailedError: "Delete failed.",
    filesTitle: "Backup Files",
    filesDescription: "Download, restore, or delete generated backup artifacts.",
    tableHeaders: { file: "File", size: "Size", kind: "Kind", status: "Status", created: "Created", actions: "Actions" },
    emptyMessage: "No backups yet.",
  },
  slider: {
    title: "Login Page Educational Hero Slider Settings",
    description: "Manage the educational showcase images, titles, and subtitles displayed on the login page hero carousel.",
    resetLabel: "Reset to Default Educational Slides",
    resetToastMessage: "Hero slides reset to defaults.",
    resetToastTitle: "Reset Done",
    currentSlidesTitle: "Current slides",
    currentSlidesDescription: "Edit existing hero images and copy.",
    badgePlaceholder: "Badge text",
    titlePlaceholder: "Slide Title",
    subtitlePlaceholder: "Subtitle",
    imageUrlPlaceholder: "Image URL",
    removeLabel: "Remove",
    addSectionTitle: "Add Custom Educational Slide",
    addSectionDescription: "Create another slide for the public login hero.",
    imageUrlLabel: "Image URL",
    imageUrlInputPlaceholder: "https://images.unsplash.com/...",
    titleLabel: "Title",
    titleInputPlaceholder: "Slide Heading",
    subtitleLabel: "Subtitle",
    subtitleInputPlaceholder: "Slide Subtitle",
    badgeLabel: "Badge Text",
    badgeInputPlaceholder: "e.g. ACADEMIC EXCELLENCE",
    addLabel: "Add Educational Slide",
    defaultSubtitle: "Educational IELTS LMS platform slide.",
    defaultBadge: "IELTS LMS",
    addedToastMessage: "New login hero slide added successfully!",
    addedToastTitle: "Slide Added",
  },
  contact: {
    title: "Contact Info & Social Links",
    description: "Configure the public /contact page's info cards and the site footer's social media icons.",
    infoTitle: "Contact Info Cards",
    infoDescription: "Shown as the Email Us / Call Sales / Support Portal / Head Office cards on the public Contact page.",
    emailLabel: "Support Email",
    emailNotePlaceholder: "e.g. Replies within 1 working day",
    phoneLabel: "Sales Phone",
    phoneNotePlaceholder: "e.g. Mon–Fri · 10am to 7pm IST",
    supportUrlLabel: "Support Portal URL",
    supportNotePlaceholder: "e.g. Existing partners only",
    officeNameLabel: "Office / Company Name",
    officeAddressLabel: "Office Address",
    officeAddressPlaceholder: "One address line per row",
    saveInfoLabel: "Save Contact Info",
    saveInfoError: "Failed to save contact info.",
    saveInfoSuccess: "Contact info saved.",
    socialTitle: "Social Links",
    socialDescription: "Shown as icons in the footer of every public page. Disabled links are hidden from the public site.",
    currentLinksTitle: "Current Links",
    noLinksMessage: "No social links yet.",
    urlPlaceholder: "https://...",
    removeLabel: "Remove",
    removeError: "Failed to remove social link.",
    updateError: "Failed to update social link.",
    addSectionTitle: "Add Social Link",
    addSectionDescription: "Pick a platform and paste its URL.",
    platformLabel: "Platform",
    addLabel: "Add Link",
    addError: "Failed to add social link.",
    loadError: "Failed to load contact settings.",
    platformLabels: {
      linkedin: "LinkedIn",
      github: "GitHub",
      instagram: "Instagram",
      youtube: "YouTube",
      facebook: "Facebook",
      twitter: "X (Twitter)",
      tiktok: "TikTok",
      website: "Website",
    },
  },
  paymentGateways: {
    title: "Payment Gateway Credentials & API Keys",
    description: "Configure Razorpay and Stripe API keys, webhook secrets, and enable/disable payment processing for student subscriptions.",
    saveSuccess: "Payment gateway settings saved successfully!",
    saveError: "Failed to save payment gateway settings.",
    razorpayTitle: "Razorpay Gateway (INR / India)",
    razorpayDesc: "Configure Razorpay Key ID and Key Secret for processing payments in India.",
    razorpayEnable: "Enable Razorpay Gateway",
    razorpayKeyIdLabel: "Razorpay Key ID",
    razorpayKeyIdPlaceholder: "rzp_live_...",
    razorpayKeySecretLabel: "Razorpay Key Secret",
    razorpayKeySecretPlaceholder: "Enter secret key or leave unchanged",
    razorpayWebhookSecretLabel: "Razorpay Webhook Secret",
    razorpayWebhookSecretPlaceholder: "Enter webhook secret or leave unchanged",
    stripeTitle: "Stripe Gateway (International / USD)",
    stripeDesc: "Configure Stripe Publishable Key and Secret Key for global payments.",
    stripeEnable: "Enable Stripe Gateway",
    stripePublishableKeyLabel: "Stripe Publishable Key",
    stripePublishableKeyPlaceholder: "pk_live_...",
    stripeSecretKeyLabel: "Stripe Secret Key",
    stripeSecretKeyPlaceholder: "sk_live_...",
    stripeWebhookSecretLabel: "Stripe Webhook Secret",
    stripeWebhookSecretPlaceholder: "whsec_...",
    saveBtn: "Save Gateway Settings",
  },
};
