export const instituteOnboardingStrings = {
  defaultTitle: "Onboard Institute",
  subtitle: "Record the agreement, configure access and branding, then publish the institute.",
  allOnboardings: "← All onboardings",
  steps: ["Agreement", "Branding", "Publish"],
  errors: {
    load: "Failed to load onboarding.",
    createDraft: "Failed to create onboarding draft.",
    saveBranding: "Failed to save branding.",
    publish: "Failed to publish institute.",
  },
  publishConfirm: "Publish this institute and activate its administrator account?",
  step1: {
    instituteAdminDetails: {
      title: "Institute & Admin Details",
      description: "Basic institute credentials and initial admin profile.",
      instituteName: "Institute name",
      instituteNamePlaceholder: "e.g. Cambridge Academy",
      contactEmail: "Contact email",
      contactEmailPlaceholder: "contact@institute.com",
      firstAdminHeading: "First Institute Administrator",
      adminEmail: "Admin email",
      adminEmailPlaceholder: "admin@institute.com",
      firstName: "First name",
      firstNamePlaceholder: "John",
      lastName: "Last name",
      lastNamePlaceholder: "Doe",
    },
    permissions: {
      title: "Administrator Permissions",
      description: "Select features enabled for this institute's admin role.",
      selectAll: "Select all",
    },
    agreementPayment: {
      title: "Agreement & Payment Terms",
      description: "Commercial terms, payment record, and access allocation.",
      agreedAmount: "Agreed amount",
      amountPlaceholder: "10000",
      amountReceived: "Amount received",
      currency: "Currency",
      paymentMethod: "Payment method",
      manualUnspecified: "Manual / unspecified",
      searchPaymentMethods: "Search payment methods...",
      receiptReference: "Receipt/reference",
      receiptPlaceholder: "REC-1002",
      agreementReference: "Agreement reference",
      agreementReferencePlaceholder: "AGR-2026-01",
      agreementNotes: "Agreement notes",
      agreementNotesPlaceholder: "Additional notes...",
      allocationHeading: "Allocation Limits",
      studentLimit: "Student limit",
      instructorLimit: "Instructor limit",
      durationDays: "Duration (days)",
    },
    includedCourses: {
      title: "Included Courses",
      description: "Select courses included in this onboarding agreement.",
      selectAll: "Select all",
      minsSuffix: "mins",
    },
    creatingDraft: "Creating draft...",
    createDraftAndContinue: "Create draft and continue →",
  },
  step2: {
    title: "Institute branding",
    description: "The portal stays offline while you prepare its identity.",
    credentialsHeading: "Institute admin credentials",
    credentialsHint: "Share these securely. The temporary password is shown only in this session.",
    primaryColor: "Primary color",
    secondaryColor: "Secondary color",
    logo: "Institute logo",
    portalLabel: "Institute Portal",
    saving: "Saving...",
    saveBrandingAndReview: "Save branding and review",
  },
  step3: {
    live: "Institute is live",
    readyToPublish: "Ready to publish",
    publishedAndLive: "Published & Live",
    draftReady: "Draft Ready",
    agreementSuffix: "agreement",
    paymentSuffix: "payment",
    validitySuffix: "validity",
    stats: {
      studentAllocation: "Student Allocation",
      instructorAllocation: "Instructor Allocation",
      assignedTests: "Assigned Tests",
      unlimited: "Unlimited",
      includedCourses: "Included Courses",
      adminPermissions: "Admin Permissions",
      enabledSuffix: "enabled",
      paymentReceived: "Payment Received",
    },
    publishing: "Publishing...",
    publishInstitute: "Publish Institute",
    manageInstitute: "Manage institute",
    done: "Done",
  },
} as const;
