export const subscriptionsStrings = {
  title: "Subscriptions",
  subtitle: "Manage plan allocation, renewals, and resource quotas for institutes.",
  instituteLabel: "Institute:",
  selectInstitute: "Select institute...",
  searchInstitutePlaceholder: "Search institute name...",
  noInstitutes: "No institutes available.",
  state: {
    active: "Active",
    grace: "In grace period",
    expired: "Expired",
    cancelled: "Cancelled",
    scheduled: "Scheduled",
    none: "No subscription",
  },
  noActivePlan: "No Active Plan",
  starts: "Starts:",
  expires: "Expires:",
  graceDaysLeft: "Grace days left:",
  daysLeft: "Days left:",
  startsInDays: "Starts in (days):",
  noAllocation: "Nothing allocated to this institute yet — set its provisions on the institute form.",
  assigning: "Assigning...",
  assignPlan: "Assign plan",
  renewing: "Renewing...",
  renew: "Renew",
  cancelSubscription: "Cancel subscription",
  cancelConfirm: "Are you sure you want to cancel this subscription? The institute will lose access upon expiration.",
  cancelConfirmTitle: "Cancel Subscription",
  cancelConfirmButton: "Cancel Subscription",
  cancel: "Cancel",
  cancelTooltip: "Cancel Subscription",
  quotaChart: {
    title: "Quota Utilization",
    chartViewTitle: "Chart View",
    tableViewTitle: "Data Table View",
    resource: "Resource",
    used: "Used",
    limit: "Limit",
    share: "Share",
    students: "Students",
    instructors: "Instructors",
    courses: "Courses",
  },
  validityGauge: {
    title: "Subscription Health",
    days: "days",
    activeDescription: "Plan active with full portal access.",
    graceDescription: "Grace period active. Please renew.",
    expiredDescription: "Subscription expired.",
    scheduledDescription: "Renewed ahead of time - this term starts when the current one ends.",
  },
  history: {
    heading: "Subscription History",
    plan: "Plan",
    starts: "Starts",
    expires: "Expires",
    state: "State",
    actions: "Actions",
    defaultPlanName: "Subscription Plan",
  },
  errors: {
    load: "Failed to load subscription details.",
    assign: "Failed to assign plan.",
    renew: "Failed to renew.",
    cancel: "Failed to cancel.",
  },
  notices: {
    assigned: "Plan assigned successfully.",
    renewed: "Subscription renewed successfully.",
    cancelled: "Subscription cancelled.",
  },
} as const;
