export const subscriptionsStrings = {
  title: "Subscriptions",
  subtitle: "Manage plan allocation, renewals, and resource quotas for institutes.",
  instituteLabel: "Institute:",
  selectInstitute: "Select institute...",
  searchInstitutePlaceholder: "Search institute name...",
  noInstitutes: "No institutes available.",
  state: {
    active: "Active",
    grace: "In grace period",
    expired: "Expired",
    cancelled: "Cancelled",
    scheduled: "Scheduled",
    none: "No subscription",
  },
  noActivePlan: "No Active Plan",
  starts: "Starts:",
  expires: "Expires:",
  graceDaysLeft: "Grace days left:",
  daysLeft: "Days left:",
  startsInDays: "Starts in (days):",
  noAllocation: "Nothing allocated to this institute yet — set its provisions on the institute form.",
  assigning: "Assigning...",
  assignPlan: "Assign plan",
  renewing: "Renewing...",
  renew: "Renew",
  reviewRenewal: "Review renewal",
  restartPlan: "Restart plan",
  manageOngoingPlan: "Manage ongoing plan",
  cancelSubscription: "Cancel subscription",
  cancelConfirm: "Are you sure you want to cancel this subscription? The institute will lose access upon expiration.",
  cancelConfirmTitle: "Cancel Subscription",
  cancelConfirmButton: "Cancel Subscription",
  cancel: "Cancel",
  cancelTooltip: "Cancel Subscription",
  ongoingPlanDialog: {
    title: "This institute has an ongoing plan",
    summary: (planName: string, expiryDate: string) => `${planName} is currently active and runs until ${expiryDate}. What would you like to do?`,
    editTitle: "Edit current plan",
    editDescription: "Change allocation, duration, courses, or agreement details.",
    renewTitle: "Renew in advance",
    renewDescription: (expiryDate: string) => `Review this plan before queuing its next term after ${expiryDate}.`,
    cancelTitle: "Cancel subscription",
    cancelDescription: "Stop this subscription and remove its ongoing access.",
  },
  editDialog: {
    title: "Edit current plan",
    description: (instituteName: string) => `Update only the agreement and access provisions for ${instituteName}. The current term keeps its original start date.`,
    agreementHeading: "Agreement",
    agreementHint: "Commercial details attached to this institute plan.",
    reference: "Agreement reference",
    amount: "Agreed amount",
    currency: "Currency",
    notes: "Agreement notes",
    allocationHeading: "Access provisions",
    allocationHint: "Changes apply to the active plan without restarting its access period.",
    students: "Student limit",
    instructors: "Instructor limit",
    duration: "Access duration (days)",
    grace: "Grace period (days)",
    coursesHeading: "Included courses",
    coursesHint: "Choose the modules available through this plan.",
    loadingCourses: "Loading available courses...",
    cancel: "Keep current plan",
    save: "Save plan changes",
    errors: {
      loadCourses: "Failed to load available courses.",
      save: "Failed to update this plan.",
    },
  },
  renewalDialog: {
    renewTitle: "Review plan renewal",
    restartTitle: "Review plan restart",
    renewDescription: "Confirm the same plan details below, or edit the agreement before renewing.",
    restartDescription: "This plan was cancelled. Confirm its details below to start a fresh term today.",
    plan: "Plan",
    starts: "Next term starts",
    duration: "Validity",
    grace: "Grace period",
    students: "Students",
    instructors: "Instructors",
    courses: "Courses",
    tests: "Tests",
    unlimited: "Unlimited",
    today: "Today",
    notAvailable: "Not available",
    days: (value: number) => `${value} ${value === 1 ? "day" : "days"}`,
    editBefore: "Edit before renewing",
    renewSamePlan: "Renew same plan",
    restartSamePlan: "Restart same plan",
    renewNote: "Renewing keeps the current plan unchanged and queues it after the present term ends.",
    restartNote: "Restarting creates a new term immediately using this same agreement.",
  },
  quotaChart: {
    title: "Quota Utilization",
    chartViewTitle: "Chart View",
    tableViewTitle: "Data Table View",
    resource: "Resource",
    used: "Used",
    limit: "Limit",
    share: "Share",
    students: "Students",
    instructors: "Instructors",
    courses: "Courses",
  },
  validityGauge: {
    title: "Subscription Health",
    days: "days",
    activeDescription: "Plan active with full portal access.",
    graceDescription: "Grace period active. Please renew.",
    expiredDescription: "Subscription expired.",
    scheduledDescription: "Renewed ahead of time - this term starts when the current one ends.",
  },
  history: {
    heading: "Subscription History",
    plan: "Plan",
    starts: "Starts",
    expires: "Expires",
    state: "State",
    actions: "Actions",
    defaultPlanName: "Subscription Plan",
  },
  errors: {
    load: "Failed to load subscription details.",
    assign: "Failed to assign plan.",
    renew: "Failed to renew.",
    restart: "Failed to restart plan.",
    edit: "Failed to update plan.",
    cancel: "Failed to cancel.",
  },
  notices: {
    assigned: "Plan assigned successfully.",
    renewed: "Subscription renewed successfully.",
    restarted: "Subscription restarted successfully.",
    edited: "Plan updated successfully.",
    cancelled: "Subscription cancelled.",
  },
} as const;
