export const studentDashboardStrings = {
  loadError: "Failed to load your dashboard.",
  loading: "Loading...",
  eyebrow: "Student Dashboard",
  welcome: (firstName: string | undefined) => `Welcome, ${firstName ?? "student"}`,
  subtitle: "Track your assigned tests, progress, and recent activity.",
  dailyEnglish: {
    eyebrow: "Daily English",
    heading: "Five questions. One daily streak.",
    subtitle: (date: string) => `Practice for ${date}`,
    loading: "Loading today's English challenge...",
    loadError: "Unable to load today's English challenge.",
    answerError: "Unable to submit that answer.",
    currentStreak: "Current streak",
    longestStreak: "Longest streak",
    questionProgress: (current: number, total: number) => `Question ${current} of ${total}`,
    correct: "Correct",
    incorrect: "Not quite",
    previous: "Previous",
    next: "Next question",
    complete: (score: number, total: number) => `Complete: ${score}/${total} correct`,
    completedHeading: "You have completed your quiz today",
    completedMessage: "Come back tomorrow for five new English questions.",
    fireLabel: (score: number) => `Animated quiz flame for a score of ${score} out of 5`,
    reviewAnswers: "Review answers",
    backToResult: "Back to result",
    day: "day",
    days: "days",
    activityHeading: "Practice activity",
    weeks: "Last 12 weeks",
    less: "Less",
    more: "More",
    activityTooltip: (date: string, answered: number, score: number) => (
      `${date}: ${answered}/5 answered${answered ? `, ${score} correct` : ""}`
    ),
    discovery: {
      eyebrow: "English discovery",
      heading: "A fact while you keep learning",
      loading: "Finding an English fact...",
      loadError: "English discovery is temporarily unavailable.",
      retry: "Try again",
      previous: "Previous fact",
      next: "Next fact",
      refreshTime: "Next in 3 min",
      source: (name: string) => `Read on ${name}`,
    },
  },
  statusLabels: {
    ready: "Security check required",
    in_progress: "In progress",
    submitted: "Submitted",
    grading: "Awaiting grading",
    graded: "Graded",
    speaking_remaining: "Speaking remaining",
    expired: "Expired",
  },
  notStarted: "Not started",
  stats: {
    available: "Available tests",
    completed: "Completed",
    pending: "Pending",
    inProgress: "In progress",
    awaitingGrading: "Awaiting grading",
    graded: "Graded",
  },
  learningPlan: {
    instituteHeading: "Institute assigned tests",
    directHeading: "Your learning plan",
    instituteDescription: "Only tests allotted to your institute are available here.",
    directDescription: "Tests included in your current plan.",
    completedSuffix: "completed",
    pendingSuffix: "pending",
    instituteEmpty: "No tests are currently assigned. Contact your institute administrator.",
    directEmpty: "No active plan. Choose a plan to begin.",
    minutesSuffix: (minutes: number) => `${minutes} min`,
    goToMyTests: "Go to My Tests",
  },
  recentActivity: {
    heading: "Recent test activity",
    description: "Your most recent attempts across all courses.",
    empty: "No test attempts yet.",
    viewFullHistory: "View full history",
  },
  speakingRemaining: {
    heading: "Speaking remaining",
    description: "These full mock or final tests are waiting only for the Speaking paper.",
    empty: "No deferred Speaking tests.",
    action: "Finish Speaking",
    pending: "Security check will run again before Speaking starts.",
    active: "Speaking phase is active.",
  },
  validity: {
    directActiveEyebrow: "Active Plan Subscription",
    directGraceEyebrow: "Plan in Grace Period",
    instituteEyebrow: "Institutional Academic Access",
    trialEyebrow: "Free Trial & Practice Access",
    expiredEyebrow: "Access Expired",
    validFrom: "Valid From",
    validUntil: "Valid Until",
    accessUntil: (date: string) => `Valid until ${date}`,
    ongoingAccess: "Ongoing Academic License",
    daysRemaining: (days: number) => `${days} ${days === 1 ? "day" : "days"} remaining`,
    expiringSoon: (days: number) => `Expiring in ${days} ${days === 1 ? "day" : "days"}`,
    graceNotice: "Your subscription is in a grace period. Renew now to avoid test interruptions.",
    expiredNotice: "Your access has expired. Renew your plan to resume tests and AI evaluations.",
    trialNotice: (testsUsed: number, totalTests: number) => `${testsUsed} of ${totalTests} demo practice tests used.`,
    renewBtn: "Renew / Upgrade Plan",
    exploreBtn: "Explore Test Plans",
    viewTestsBtn: "View Assigned Tests",
    managedBy: (instituteName: string) => `Academic licensing managed by ${instituteName}`,
  },
} as const;
