export const studentDashboardStrings = {
  loadError: "Failed to load your dashboard.",
  loading: "Loading...",
  eyebrow: "Student Dashboard",
  welcome: (firstName: string | undefined) => `Welcome, ${firstName ?? "student"}`,
  subtitle: "Track your assigned tests, progress, and recent activity.",
  statusLabels: {
    ready: "Security check required",
    in_progress: "In progress",
    submitted: "Submitted",
    grading: "Awaiting grading",
    graded: "Graded",
    expired: "Expired",
  },
  notStarted: "Not started",
  stats: {
    available: "Available tests",
    completed: "Completed",
    pending: "Pending",
    inProgress: "In progress",
    awaitingGrading: "Awaiting grading",
    graded: "Graded",
  },
  learningPlan: {
    instituteHeading: "Institute assigned tests",
    directHeading: "Your learning plan",
    instituteDescription: "Only tests allotted to your institute are available here.",
    directDescription: "Tests included in your current plan.",
    completedSuffix: "completed",
    pendingSuffix: "pending",
    instituteEmpty: "No tests are currently assigned. Contact your institute administrator.",
    directEmpty: "No active plan. Choose a plan to begin.",
    minutesSuffix: (minutes: number) => `${minutes} min`,
    goToMyTests: "Go to My Tests",
  },
  recentActivity: {
    heading: "Recent test activity",
    description: "Your most recent attempts across all courses.",
    empty: "No test attempts yet.",
    viewFullHistory: "View full history",
  },
} as const;
