import { type FormEvent, useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { API_BASE_URL, apiClient } from "../../api/client";
import { extractErrorMessage } from "../../api/errors";
import type { Course, CourseAsset } from "../../api/types";

const EMPTY = { title: "", summary: "", description: "", level: "all_levels", estimated_duration_minutes: "", price: "0", currency: "INR", is_featured: false };

function fileSize(bytes: number): string { return bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${Math.ceil(bytes / 1024)} KB`; }

export function CourseEditor() {
  const { id } = useParams(); const isNew = !id; const navigate = useNavigate();
  const [form, setForm] = useState(EMPTY); const [course, setCourse] = useState<Course | null>(null);
  const [loading, setLoading] = useState(!isNew); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [assetTitle, setAssetTitle] = useState(""); const [assetFile, setAssetFile] = useState<File | null>(null); const [uploading, setUploading] = useState(false);

  async function load() { if (isNew) return; setLoading(true); try { const { data } = await apiClient.get<Course>(`/instructor/courses/${id}`); setCourse(data); setForm({ title: data.title, summary: data.summary ?? "", description: data.description ?? "", level: data.level, estimated_duration_minutes: data.estimated_duration_minutes ? String(data.estimated_duration_minutes) : "", price: data.price, currency: data.currency, is_featured: data.is_featured }); } catch { setError("Failed to load course."); } finally { setLoading(false); } }
  useEffect(() => { load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [id]);
  function setField(field: keyof typeof EMPTY, value: string | boolean) { setForm((current) => ({ ...current, [field]: value as never })); }
  function payload() { return { title: form.title, summary: form.summary || null, description: form.description || null, level: form.level, estimated_duration_minutes: form.estimated_duration_minutes ? Number(form.estimated_duration_minutes) : null, price: Number(form.price), currency: form.currency, is_featured: form.is_featured }; }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(null); setNotice(null); try { if (isNew) { const { data } = await apiClient.post<Course>("/instructor/courses", payload()); navigate(`/instructor/courses/${data.id}`, { replace: true }); } else { const { data } = await apiClient.patch<Course>(`/instructor/courses/${id}`, payload()); setCourse(data); setNotice("Course details saved."); } } catch (err: unknown) { setError(extractErrorMessage(err, "Failed to save course.")); } finally { setSaving(false); } }
  async function changeStatus(status: Course["status"]) { setError(null); setNotice(null); try { const { data } = await apiClient.post<Course>(`/instructor/courses/${id}/status`, { status }); setCourse(data); setNotice(`Course moved to ${status}.`); } catch (err: unknown) { setError(extractErrorMessage(err, "Failed to change course status.")); } }
  async function upload(event: FormEvent) { event.preventDefault(); if (!assetFile) return; setUploading(true); setError(null); try { const data = new FormData(); data.append("file", assetFile); if (assetTitle.trim()) data.append("title", assetTitle.trim()); await apiClient.post(`/instructor/courses/${id}/assets`, data); setAssetFile(null); setAssetTitle(""); const input = document.getElementById("asset-file") as HTMLInputElement | null; if (input) input.value = ""; await load(); setNotice("Resource uploaded."); } catch (err: unknown) { setError(extractErrorMessage(err, "Failed to upload resource.")); } finally { setUploading(false); } }
  async function removeAsset(asset: CourseAsset) { if (!window.confirm(`Remove “${asset.title}”?`)) return; try { await apiClient.delete(`/instructor/courses/${id}/assets/${asset.id}`); await load(); } catch (err: unknown) { setError(extractErrorMessage(err, "Failed to remove resource.")); } }
  async function moveAsset(index: number, direction: -1 | 1) { if (!course) return; const next = [...course.assets]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; try { await apiClient.put(`/instructor/courses/${id}/assets/reorder`, { asset_ids: next.map((item) => item.id) }); await load(); } catch (err: unknown) { setError(extractErrorMessage(err, "Failed to reorder resources.")); } }
  async function deleteCourse() { if (!course || !window.confirm(`Delete “${course.title}”? This cannot be undone.`)) return; try { await apiClient.delete(`/instructor/courses/${course.id}`); navigate("/super-admin/instructor/courses"); } catch (err: unknown) { setError(extractErrorMessage(err, "Failed to delete course.")); } }
  if (loading) return <p>Loading...</p>;
  return <div><div className="page-header"><div><h1>{isNew ? "New Course" : form.title}</h1>{course && <p className="page-subtitle">/{course.slug} · Created by {course.created_by_name}</p>}</div><Link to="/super-admin/instructor/courses" className="text-link">← All courses</Link></div>
    {course && <div className="course-status-bar"><div><span className={`badge badge-${course.status === "published" ? "green" : course.status === "draft" ? "amber" : "gray"}`}>{course.status}</span><span>{course.asset_count} resources · {course.assignment_count} active assignments</span></div><div className="status-actions">{course.status !== "draft" && <button className="secondary-button" onClick={() => changeStatus("draft")}>Move to draft</button>}{course.status !== "published" && <button onClick={() => changeStatus("published")}>Publish</button>}{course.status !== "archived" && <button className="secondary-button" onClick={() => changeStatus("archived")}>Archive</button>}</div></div>}
    {error && <p className="error-text">{error}</p>}{notice && <p className="success-text">{notice}</p>}
    <div className="course-editor-grid"><form className="form-card wide" onSubmit={save}><h2>Course details</h2><label htmlFor="title">Title</label><input id="title" maxLength={200} value={form.title} onChange={(e) => setField("title", e.target.value)} required /><label htmlFor="summary">Summary</label><textarea id="summary" maxLength={500} rows={3} value={form.summary} onChange={(e) => setField("summary", e.target.value)} /><label htmlFor="description">Description</label><textarea id="description" maxLength={10000} rows={7} value={form.description} onChange={(e) => setField("description", e.target.value)} /><div className="form-grid"><div><label htmlFor="level">Level</label><select id="level" value={form.level} onChange={(e) => setField("level", e.target.value)}><option value="all_levels">All levels</option><option value="foundation">Foundation</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></div><div><label htmlFor="duration">Estimated minutes</label><input id="duration" type="number" min="1" value={form.estimated_duration_minutes} onChange={(e) => setField("estimated_duration_minutes", e.target.value)} /></div><div><label htmlFor="price">B2C price</label><input id="price" type="number" min="0" step="0.01" value={form.price} onChange={(e) => setField("price", e.target.value)} required /></div><div><label htmlFor="currency">Currency</label><input id="currency" maxLength={8} value={form.currency} onChange={(e) => setField("currency", e.target.value.toUpperCase())} required /></div></div><label className="inline-check featured-check"><input type="checkbox" checked={form.is_featured} onChange={(e) => setField("is_featured", e.target.checked)} /> Feature this course in future student catalogs</label><div className="form-actions"><button type="submit" disabled={saving || course?.status === "archived"}>{saving ? "Saving..." : isNew ? "Create Course" : "Save Details"}</button>{course && <button type="button" className="danger-text" onClick={deleteCourse}>Delete course</button>}</div></form>
      {!isNew && <section className="resource-panel"><h2>PDF & MP3 resources</h2><p className="hint">PDF up to 25 MB or MP3 up to 50 MB. Use arrows to set learner order.</p><form className="asset-upload" onSubmit={upload}><label htmlFor="asset-title">Display title</label><input id="asset-title" value={assetTitle} onChange={(e) => setAssetTitle(e.target.value)} placeholder="Optional — filename used by default" /><label htmlFor="asset-file">File</label><input id="asset-file" type="file" accept="application/pdf,audio/mpeg,.pdf,.mp3" onChange={(e) => setAssetFile(e.target.files?.[0] ?? null)} required /><button type="submit" disabled={uploading || !assetFile || course?.status === "archived"}>{uploading ? "Uploading..." : "Upload Resource"}</button></form><div className="asset-list">{course?.assets.length ? course.assets.map((asset, index) => <div className="asset-row" key={asset.id}><span className={`asset-icon ${asset.asset_type}`}>{asset.asset_type === "pdf" ? "PDF" : "MP3"}</span><div><a href={`${API_BASE_URL}${asset.file_url}`} target="_blank" rel="noreferrer">{asset.title}</a><p>{asset.original_filename} · {fileSize(asset.file_size)}</p></div><div className="asset-actions"><button aria-label="Move up" disabled={index === 0} onClick={() => moveAsset(index, -1)}>↑</button><button aria-label="Move down" disabled={index === course.assets.length - 1} onClick={() => moveAsset(index, 1)}>↓</button><button className="danger" onClick={() => removeAsset(asset)}>Remove</button></div></div>) : <p className="empty-message">No resources uploaded yet.</p>}</div></section>}
    </div></div>;
}
