export const instructorFormStrings = {
  loading: "Loading...",
  newTitle: "New SA Instructor",
  editTitle: "Edit SA Instructor",
  avatar: {
    label: "Profile Image (Upload from system)",
    uploading: "Uploading image...",
  },
  firstName: "First name",
  lastName: "Last name",
  email: "Email address",
  title: "Professional title",
  phone: "Phone Number",
  phonePlaceholder: "+1 (555) 000-0000",
  dob: "Date of Birth (DOB)",
  address: "Residential / Office Address",
  addressPlaceholder: "123 Campus Way, Suite 400",
  bio: "Bio",
  bioPlaceholder: "Teaching experience, credentials, and focus areas",
  passwordHint: "A temporary password will be generated for testing. The instructor must change it after login.",
  saving: "Saving...",
  createInstructor: "Create Instructor",
  saveChanges: "Save Changes",
  cancel: "Cancel",
  created: {
    heading: "Instructor Created",
    credentialsLabel: "Temporary Login Credentials",
    shareHint: "Share this password with the instructor for testing. They will be asked to change it after login.",
    missingPassword: "Temporary password was not returned. Restart the backend, then use Reset Password from the instructor list.",
    missingPasswordError: "Temporary password was not returned by the server. Restart the backend and reset the instructor password.",
    copyPassword: "Copy Password",
    copied: "Copied",
    done: "Done",
  },
  errors: {
    load: "Failed to load instructor.",
    uploadImage: "Failed to upload image.",
    save: "Failed to save instructor.",
  },
} as const;
