/* =========================================================================
 * talking-avatar.js  —  lightweight image-swap talking avatar
 * =========================================================================
 * No ML. No GPU. No lip-sync model. Just:
 *   - 4 photos of the same person with different mouth openings
 *   - the Web Audio API measuring how loud the speech is right now
 *   - CSS opacity cross-fades between the two nearest photos
 *   - a synthetic eyelid that blinks on its own
 *   - a touch of idle head motion so it never looks like a frozen JPEG
 *
 * Everything below is plain DOM + rAF. It runs fine on a phone.
 *
 * Usage:
 *   import { TalkingAvatar } from './talking-avatar.js';
 *   const avatar = new TalkingAvatar(document.getElementById('avatar'), {...});
 *   await avatar.load();
 *   await avatar.playUrl('assets/speech.wav');
 * ========================================================================= */

/* ---------- small helpers ------------------------------------------------ */
const clamp = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);
const lerp = (a, b, t) => a + (b - a) * t;
const rand = (a, b) => a + Math.random() * (b - a);

/* Order matters: index 0 = most closed, last = most open. */
export const FRAME_ORDER = ['closed', 'small', 'medium', 'wide'];

export const DEFAULTS = {
  /* ---- artwork ---------------------------------------------------------- */
  frames: {
    closed: 'assets/avatar_closed.png',
    small: 'assets/avatar_small_open.png',
    medium: 'assets/avatar_medium_open.png',
    wide: 'assets/avatar_wide_open.png',
    // Optional. If you supply a real eyes-closed photo it is used instead of
    // the synthetic eyelid: blink: 'assets/avatar_blink.png'
    blink: null,
  },

  /* BEST blink: an ordered sequence of transparent eyelid overlays, closure
     0 -> 1, generated by tools/build_blink_frames.py. When present these are
     used and the CSS eyelid below is ignored entirely. */
  blinkFrames: [],

  /* Which "openness" value each frame represents, 0..1.
     Tweak if one of your frames is much more open than the others. */
  levels: [0.0, 0.28, 0.60, 1.0],

  /* ---- audio -> mouth --------------------------------------------------- */
  sensitivity: 0.85,  // overall gain on the mouth. >1 = bigger mouth movement
  gate: 0.055,        // below this normalised loudness the mouth is CLOSED
  gamma: 0.80,        // <1 opens the mouth earlier (more lively), >1 = calmer
  autoGain: true,     // adapt to quiet or loud recordings automatically
  fftSize: 1024,

  /* ---- smoothing: this is what stops the mouth flapping ------------------
     A jaw has mass. Driving the mouth straight from the loudness makes it
     chatter at the syllable rate; driving a critically damped spring TOWARD
     the loudness makes it move the way a jaw does.                          */
  smoothing: 'spring',   // 'spring' (recommended) | 'lerp' (the old behaviour)
  openHz: 6.0,           // spring speed while OPENING. Lower = softer
  closeHz: 3.6,          // spring speed while CLOSING. Lower = lazier, smoother
  damping: 1.0,          // 1 = critically damped (no wobble). 0.7 adds a little
  rmsTau: 70,            // ms of pre-smoothing on the raw loudness

  /* Between syllables inside a word the mouth does not slam shut. `sustain`
     holds it partly open for as long as speech is happening, which removes
     most of the "snapping" look on its own. 0 disables. */
  sustain: 0.38,
  sustainTau: 150,       // ms it takes the "speech is happening" flag to fall

  attack: 0.62,          // only used when smoothing: 'lerp'
  release: 0.20,

  /* ---- blinking --------------------------------------------------------- */
  blink: {
    enabled: true,
    minGap: 3000,     // ms  ) random wait between blinks
    maxGap: 6000,     // ms  )
    closeMs: 70,      // lid travelling down
    holdMs: 45,       // fully closed
    openMs: 110,      // lid travelling back up
    doubleChance: 0.18, // people often blink twice in a row
  },

  /* Eye rectangles in the ORIGINAL image's pixel coordinates.
     Use the calibration panel in the demo to find these for your photos. */
  eyes: {
    left: { x: 272, y: 234, w: 90, h: 40 },
    right: { x: 376, y: 232, w: 90, h: 40 },

    /* Where the lid's skin comes from, relative to the eye rect's top.
       POSITIVE = borrow from above the eye (upper lid / brow gap).
       NEGATIVE = borrow from below the eye (under-eye / cheek) — use this when
       the brow sits close to the lash line and there is no clean strip above. */
    donorOffsetY: -44,
    donorScaleY: 1,    // stretch the donor strip vertically if it is thin

    /* The lid is feathered with an elliptical CSS mask rather than a hard
       border-radius, so its edges dissolve into the surrounding skin instead
       of showing a rectangle. */
    maskInner: 0.72,   // fully opaque out to this normalised radius
    maskOuter: 1.10,   // fully transparent beyond this
    maskCy: 0.50,      // vertical centre of the ellipse within the rect

    lash: 'rgba(56,36,31,0.78)',
    lashPx: 2,
    lashAt: 0.84,      // where the lash line sits within the rect, 0..1
  },

  /* Where the mouth is, in the original image's pixels. Only used to pivot the
     small width/round shaping below — set it and the mouth stretches about its
     own centre instead of the middle of the picture. */
  mouth: {
    cx: null, cy: null,      // null = centre of the image
    widthDrive: 0.05,        // how much bright/sibilant sounds widen the mouth
    roundDrive: 0.04,        // how much dark/vowel sounds round it
  },

  /* ---- life signs ------------------------------------------------------- */
  idle: {
    enabled: true,
    amount: 1.0,      // 0 = perfectly still, 1 = natural, 2 = fidgety
    breathe: true,
  },
  jaw: {
    drop: 2.2,        // px the head sinks at full mouth opening
    squash: 0.007,    // vertical stretch at full opening
    nod: 1.6,         // px of extra nod on a sharp rise in loudness (stress)
  },

  /* ---- misc -------------------------------------------------------------- */
  crossfade: true,    // false = hard image swaps (the classic cheap look)
  onFrame: null,      // callback({ level, raw, frameIndex, blinking }) for debugging
};

/* deep-ish merge so callers can override just one nested key */
function merge(base, over) {
  const out = Array.isArray(base) ? base.slice() : { ...base };
  for (const k of Object.keys(over || {})) {
    const v = over[k];
    if (v && typeof v === 'object' && !Array.isArray(v) && typeof base[k] === 'object' && base[k] !== null) {
      out[k] = merge(base[k], v);
    } else if (v !== undefined) {
      out[k] = v;
    }
  }
  return out;
}

/* An <audio> element may only ever be connected to ONE MediaElementSource, for
   the lifetime of the page — calling createMediaElementSource on it a second
   time throws. So we remember the ones we made.

   That is also why the AudioContext is shared across every TalkingAvatar rather
   than owned per instance: a cached source stays bound to the context it was
   created in, so if an instance closed its context on unmount, remounting would
   find a source pointing at a dead context and the audio would go silent.
   Browsers also cap how many contexts a page may open. */
const elementSources = new WeakMap();
let sharedCtx = null;

/** Create (if needed) and resume the shared AudioContext.
 *
 * `attachMediaElement` reroutes the prompt's <audio> element through this
 * context via `createMediaElementSource` - once that happens, whether
 * anything is heard (and whether the analyser has anything to drive the
 * mouth from) depends entirely on `ctx.state === 'running'`. A context is
 * born suspended unless it is created or resumed during a real user gesture,
 * and `attachMediaElement` itself never runs inside one - it fires from a
 * React effect or the audio element's own `playing` event, both after the
 * fact. Call this directly from an onClick (or similar) handler, before the
 * avatar's audio would start, so the resume happens while the browser still
 * considers the call "user-initiated". Safari in particular ignores
 * `resume()` calls made outside that window. */
export function unlockSharedAudioContext() {
  const AC = window.AudioContext || window.webkitAudioContext;
  if (!AC) return null;
  if (!sharedCtx) sharedCtx = new AC();
  if (sharedCtx.state === 'suspended') sharedCtx.resume().catch(() => {});
  return sharedCtx;
}

/* ========================================================================= */
export class TalkingAvatar {
  constructor(mount, options = {}) {
    if (!mount) throw new Error('TalkingAvatar: mount element is required');
    this.mount = mount;
    this.opt = merge(DEFAULTS, options);

    this.natural = { w: 512, h: 512 };  // filled in by load()
    this.images = {};                   // key -> HTMLImageElement
    this.layers = {};                   // key -> <img> in the DOM
    this.lids = [];                     // synthetic eyelid divs (fallback)
    this.blinkImgs = [];                // pre-rendered eyelid sequence
    this.blinkLayers = null;
    this._lastBlinkIdx = -1;

    this.level = 0;                     // smoothed mouth openness 0..1
    this.raw = 0;                       // pre-smoothing loudness 0..1
    this.peak = 0.12;                   // rolling peak for auto-gain
    this.running = false;
    this.audioDriven = false;

    this._blink = { t: 0, phase: 'idle', next: performance.now() + rand(1200, 2600), queued: 0, amount: 0 };
    this._t0 = performance.now();
    this._raf = null;
    this._buf = null;
  }

  /* ---------------------------------------------------------------------
   * 1. PRELOAD + BUILD DOM
   * ------------------------------------------------------------------- */
  async load() {
    await this.setFrames(this.opt.frames);
    this._render(0, performance.now());   // paint the closed frame immediately
    this.start();
    return this;
  }

  /**
   * Swap in a different set of photos at runtime (e.g. the user uploaded their
   * own, or you have several avatars). Preloads everything before rebuilding,
   * so the avatar never shows a half-loaded state.
   */
  async setFrames(frames) {
    this.opt.frames = { ...this.opt.frames, ...frames };
    const entries = Object.entries(this.opt.frames).filter(([, url]) => !!url);

    // Preload every frame BEFORE anything animates, otherwise the first
    // mouth-open would pop in late and look broken.
    const seq = this.opt.blinkFrames || [];
    const loaded = await Promise.all([
      ...entries.map(([key, url]) => this._loadImage(key, url)),
      ...seq.map((url, i) => this._loadImage(`__blink${i}`, url)),
    ]);
    this.images = {};
    this.blinkImgs = [];
    loaded.forEach(({ key, img }) => {
      if (key.startsWith('__blink')) this.blinkImgs[+key.slice(7)] = img;
      else this.images[key] = img;
    });

    const base = this.images.closed;
    this.natural = { w: base.naturalWidth || 512, h: base.naturalHeight || 512 };

    this.layers = {};
    this.lids = [];
    this.blinkLayer = null;
    this.blinkLayers = null;
    this._lastBlinkIdx = -1;
    this._buildDom();
    return this;
  }

  _loadImage(key, url) {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.decoding = 'async';
      img.crossOrigin = 'anonymous';
      img.onload = () => resolve({ key, img });
      img.onerror = () => reject(new Error(`TalkingAvatar: could not load ${url}`));
      img.src = url;
    });
  }

  _buildDom() {
    const { natural } = this;
    this.mount.classList.add('ta-root');
    this.mount.innerHTML = '';
    this.mount.style.position = this.mount.style.position || 'relative';
    this.mount.style.overflow = 'hidden';

    // aspect-ratio box so the avatar scales with its container
    const stage = document.createElement('div');
    stage.className = 'ta-stage';
    Object.assign(stage.style, {
      position: 'relative',
      width: '100%',
      aspectRatio: `${natural.w} / ${natural.h}`,
      transformOrigin: '50% 92%',        // pivot near the neck, like a real head
      willChange: 'transform',
    });
    this.stage = stage;
    this.mount.appendChild(stage);

    // ---- mouth frames, stacked ----
    FRAME_ORDER.forEach((key, i) => {
      if (!this.images[key]) return;
      const el = document.createElement('img');
      el.src = this.images[key].src;
      el.alt = '';
      el.draggable = false;
      Object.assign(el.style, {
        position: 'absolute',
        inset: '0',
        width: '100%',
        height: '100%',
        objectFit: 'cover',
        zIndex: String(10 + i),
        opacity: i === 0 ? '1' : '0',
        userSelect: 'none',
        pointerEvents: 'none',
        backfaceVisibility: 'hidden',
      });
      this.layers[key] = el;
      stage.appendChild(el);
    });

    // ---- blink ----
    if (this.opt.blink.enabled) {
      if (this.blinkImgs && this.blinkImgs.length) {
        // Pre-rendered eyelid sequence: one transparent overlay per closure
        // step. Exactly one is visible at a time — blending two would show two
        // lids at once, which is why these are switched, not cross-faded.
        this.blinkLayers = this.blinkImgs.map((img) => {
          const el = document.createElement('img');
          el.src = img.src;
          el.alt = '';
          Object.assign(el.style, {
            position: 'absolute', inset: '0', width: '100%', height: '100%',
            objectFit: 'cover', zIndex: '40', opacity: '0',
            pointerEvents: 'none', userSelect: 'none',
          });
          stage.appendChild(el);
          return el;
        });
      } else if (this.images.blink) {
        // Real eyes-closed photo supplied: it is just another stacked layer.
        const el = document.createElement('img');
        el.src = this.images.blink.src;
        el.alt = '';
        Object.assign(el.style, {
          position: 'absolute', inset: '0', width: '100%', height: '100%',
          objectFit: 'cover', zIndex: '40', opacity: '0', pointerEvents: 'none',
        });
        this.blinkLayer = el;
        stage.appendChild(el);
      } else {
        // Synthetic eyelid: a small box over each eye whose background is skin
        // borrowed from just above the eye, so it matches tone and texture.
        ['left', 'right'].forEach(() => {
          // The lid keeps a CONSTANT size (so its background never shifts) and
          // is revealed top-down with clip-path. The lash is a separate hairline
          // that rides the lid's leading edge.
          const lid = document.createElement('div');
          Object.assign(lid.style, {
            position: 'absolute',
            zIndex: '40',
            pointerEvents: 'none',
            backgroundImage: `url("${this.images.closed.src}")`,
            backgroundRepeat: 'no-repeat',
            clipPath: 'inset(0 0 100% 0)',
            willChange: 'clip-path',
          });
          const lash = document.createElement('div');
          Object.assign(lash.style, {
            position: 'absolute',
            zIndex: '41',
            pointerEvents: 'none',
            opacity: '0',
            borderRadius: '2px',
            willChange: 'transform, opacity',
          });
          this.lids.push({ lid, lash });
          stage.appendChild(lid);
          stage.appendChild(lash);
        });
        this._applyEyes();
      }
    }
  }

  /* ---------------------------------------------------------------------
   * 2. AUDIO
   * ------------------------------------------------------------------- */
  _ensureContext() {
    if (!this.ctx) {
      if (!sharedCtx) {
        const AC = window.AudioContext || window.webkitAudioContext;
        sharedCtx = new AC();
      }
      this.ctx = sharedCtx;
      this.analyser = this.ctx.createAnalyser();
      this.analyser.fftSize = this.opt.fftSize;
      this.analyser.smoothingTimeConstant = 0;   // we do our own smoothing
      this._buf = new Uint8Array(this.analyser.fftSize);
      this._spec = new Uint8Array(this.analyser.frequencyBinCount);
    }
    if (this.ctx.state === 'suspended') this.ctx.resume();
    return this.ctx;
  }

  /** Drive the mouth from any <audio>/<video> element. */
  attachMediaElement(el) {
    const ctx = this._ensureContext();
    let src = elementSources.get(el);
    if (!src) {
      src = ctx.createMediaElementSource(el);
      elementSources.set(el, src);
    }
    try { src.disconnect(); } catch {}
    src.connect(this.analyser);
    src.connect(ctx.destination);   // so you can actually hear it
    this.media = el;
    this.audioDriven = true;

    el.addEventListener('ended', () => { this.audioDriven = false; }, { once: true });
    return this;
  }

  /** Drive the mouth from a MediaStream (microphone, WebRTC, ...). */
  attachStream(stream) {
    const ctx = this._ensureContext();
    if (this.streamSrc) { try { this.streamSrc.disconnect(); } catch {} }
    this.streamSrc = ctx.createMediaStreamSource(stream);
    this.streamSrc.connect(this.analyser);   // deliberately NOT to destination (feedback)
    this.audioDriven = true;
    return this;
  }

  /** Play an audio URL (file, blob URL, or a streaming TTS endpoint). */
  async playUrl(url, { volume = 1 } = {}) {
    this.stopAudio();
    const el = new Audio();
    el.crossOrigin = 'anonymous';
    el.preload = 'auto';
    el.volume = volume;
    el.src = url;
    this.attachMediaElement(el);
    this._ownedMedia = el;
    await el.play();
    return el;
  }

  /** Play an already-decoded AudioBuffer (useful for TTS chunks you decoded
   *  yourself, or for locally generated audio). */
  playBuffer(buffer) {
    const ctx = this._ensureContext();
    this.stopAudio();
    const src = ctx.createBufferSource();
    src.buffer = buffer;
    src.connect(this.analyser);
    src.connect(ctx.destination);
    src.onended = () => { this.audioDriven = false; };
    this._bufferSrc = src;
    this.audioDriven = true;
    src.start();
    return src;
  }

  /** Play an audio Blob (e.g. the bytes your Python TTS endpoint returned). */
  async playBlob(blob) {
    const url = URL.createObjectURL(blob);
    const el = await this.playUrl(url);
    el.addEventListener('ended', () => URL.revokeObjectURL(url), { once: true });
    return el;
  }

  /**
   * Ask your backend to synthesise speech and lip-sync it.
   *   avatar.speak('Welcome to Visa House', { endpoint: '/api/tts' })
   */
  async speak(text, { endpoint = '/api/tts', voice, body = {}, headers = {} } = {}) {
    const res = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      body: JSON.stringify({ text, voice, ...body }),
    });
    if (!res.ok) throw new Error(`TTS failed: ${res.status} ${await res.text()}`);
    return this.playBlob(await res.blob());
  }

  /** Stop audio; the mouth eases shut, idle motion and blinking continue. */
  stopAudio() {
    this.audioDriven = false;
    if (this._ownedMedia) {
      try { this._ownedMedia.pause(); this._ownedMedia.currentTime = 0; } catch {}
      this._ownedMedia = null;
    }
    if (this.streamSrc) { try { this.streamSrc.disconnect(); } catch {} this.streamSrc = null; }
    if (this._bufferSrc) { try { this._bufferSrc.onended = null; this._bufferSrc.stop(); } catch {} this._bufferSrc = null; }
    return this;
  }

  /* ---------------------------------------------------------------------
   * 3. THE LOOP
   * ------------------------------------------------------------------- */
  start() {
    if (this.running) return this;
    this.running = true;
    const tick = (now) => {
      if (!this.running) return;
      this._update(now);
      this._raf = requestAnimationFrame(tick);
    };
    this._raf = requestAnimationFrame(tick);
    return this;
  }

  stop() {
    this.running = false;
    if (this._raf) cancelAnimationFrame(this._raf);
    return this;
  }

  /** Tear down this instance. The shared AudioContext is deliberately left
   *  open — see the note above `elementSources`. */
  destroy() {
    this.stop();
    this.stopAudio();
    if (this.analyser) { try { this.analyser.disconnect(); } catch {} }
    this.ctx = null;
    this.analyser = null;
    this.mount.innerHTML = '';
  }

  _update(now) {
    const o = this.opt;

    // real elapsed time, so the motion is identical on 60Hz and 120Hz displays
    const dt = clamp((now - (this._prevNow || now)) / 1000, 1 / 240, 1 / 20);
    this._prevNow = now;

    /* --- 3a. measure loudness ------------------------------------------- */
    let target = 0;

    // External drive (see drive()): something else is deciding how open the
    // mouth should be — a viseme timeline, a phoneme track, a slider. It still
    // goes through the same spring below, so it looks identical.
    if (this._extTarget != null && now - this._extAt < 500) {
      target = this._extTarget;
      this.tilt = lerp(this.tilt || 0, this._extTilt || 0, 0.25);
      this.raw = target;
    } else if (this.audioDriven && this.analyser) {
      this.analyser.getByteTimeDomainData(this._buf);
      let sum = 0;
      for (let i = 0; i < this._buf.length; i++) {
        const v = (this._buf[i] - 128) / 128;
        sum += v * v;
      }
      let rms = Math.sqrt(sum / this._buf.length);

      // Pre-smooth the loudness itself. One analysis block is 23 ms of audio,
      // which is short enough to catch the flutter inside a single vowel.
      const aR = 1 - Math.exp(-dt / (o.rmsTau / 1000));
      this._rmsS = this._rmsS === undefined ? rms : this._rmsS + (rms - this._rmsS) * aR;
      rms = this._rmsS;

      // Auto-gain: track the loudest recent moment and normalise against it,
      // so a quiet recording still opens the mouth fully.
      if (o.autoGain) {
        this.peak = Math.max(this.peak * 0.9985, rms);
        this.raw = rms / Math.max(this.peak, 0.02);
      } else {
        this.raw = rms * 3;
      }

      // Noise gate, response curve, sensitivity.
      const gated = (this.raw - o.gate) / (1 - o.gate);
      target = clamp(Math.pow(clamp(gated, 0, 1), o.gamma) * o.sensitivity, 0, 1);

      // Sustain: while speech is happening, hold the mouth partly open instead
      // of letting it shut between syllables.
      // The activity envelope rises fast and falls in ~sustainTau ms. That is
      // the whole trick: a 60 ms gap between syllables barely dents it, but a
      // real 400 ms pause lets it collapse so the mouth genuinely closes.
      const prevAct = this._act === undefined ? 0 : this._act;
      const tau = (target > prevAct ? 50 : o.sustainTau) / 1000;
      this._act = prevAct + (target - prevAct) * (1 - Math.exp(-dt / tau));
      if (o.sustain > 0) target = Math.max(target, this._act * o.sustain * 2.2);
      target = clamp(target, 0, 1);

      /* Spectral tilt -> mouth SHAPE, not just size.
         Bright, sibilant sounds (s, sh, t, ee) sit high in the spectrum and are
         made with a wide mouth; dark vowels (oo, oh) sit low and are round.
         One cheap number — the spectral centroid — captures enough of that to
         stop every syllable looking identical. */
      this.analyser.getByteFrequencyData(this._spec);
      const bins = Math.min(this._spec.length, Math.floor(this._spec.length * 0.5));
      let num = 0, den = 0;
      for (let i = 2; i < bins; i++) { num += i * this._spec[i]; den += this._spec[i]; }
      const centroid = den > 0 ? num / den / bins : 0.35;
      this._tiltAvg = this._tiltAvg === undefined ? centroid : lerp(this._tiltAvg, centroid, 0.02);
      const tiltTarget = clamp((centroid - this._tiltAvg) * 4, -1, 1);
      this.tilt = lerp(this.tilt || 0, tiltTarget, 0.25);
    } else {
      this.tilt = lerp(this.tilt || 0, 0, 0.1);
    }

    /* --- 3b. smooth it --------------------------------------------------- */
    const prev = this.level;

    if (o.smoothing === 'spring') {
      // Critically damped spring. `level` is the jaw position, `_vel` its
      // speed: the mouth accelerates toward the target and decelerates into
      // it, so it can never step discontinuously no matter how spiky the audio.
      const hz = target > this.level ? o.openHz : o.closeHz;
      const w = 2 * Math.PI * hz;
      const z = o.damping;
      const acc = w * w * (target - this.level) - 2 * z * w * (this._vel || 0);
      this._vel = (this._vel || 0) + acc * dt;
      this.level += this._vel * dt;
      if (this.level < 0) { this.level = 0; this._vel = 0; }
      if (this.level > 1) { this.level = 1; this._vel = 0; }
    } else {
      const k = target > this.level ? o.attack : o.release;
      this.level = lerp(this.level, target, k);
    }
    if (this.level < 0.002 && target === 0) this.level = 0;

    // A sharp rise in loudness is a stressed syllable. Real speakers nod into
    // those. Track the rise and let it decay.
    const rise = Math.max(0, this.level - prev) / Math.max(dt, 1e-3);
    this.stress = Math.max(rise * 0.10, (this.stress || 0) * Math.exp(-dt / 0.16));

    /* --- 3c. blinking ---------------------------------------------------- */
    this._updateBlink(now);

    /* --- 3d. paint ------------------------------------------------------- */
    this._render(this.level, now);

    if (o.onFrame) o.onFrame({ level: this.level, raw: this.raw, blinking: this._blink.amount > 0.01 });
  }

  _updateBlink(now) {
    const b = this.opt.blink;
    const s = this._blink;
    if (!b.enabled) { s.amount = 0; return; }

    if (s.phase === 'idle') {
      if (now >= s.next) { s.phase = 'closing'; s.t = now; }
      s.amount = 0;
      return;
    }

    const dt = now - s.t;
    if (s.phase === 'closing') {
      s.amount = easeIn(clamp(dt / b.closeMs, 0, 1));
      if (dt >= b.closeMs) { s.phase = 'holding'; s.t = now; }
    } else if (s.phase === 'holding') {
      s.amount = 1;
      if (dt >= b.holdMs) { s.phase = 'opening'; s.t = now; }
    } else if (s.phase === 'opening') {
      s.amount = 1 - easeOut(clamp(dt / b.openMs, 0, 1));
      if (dt >= b.openMs) {
        s.amount = 0;
        if (s.queued > 0) {                 // second half of a double blink
          s.queued--;
          s.phase = 'closing';
          s.t = now + 40;
        } else {
          s.phase = 'idle';
          s.queued = Math.random() < b.doubleChance ? 1 : 0;
          s.next = now + rand(b.minGap, b.maxGap);
        }
      }
    }
  }

  /**
   * Drive the mouth from something other than audio loudness — a viseme
   * timeline, phoneme timings, or your own logic.
   *
   *   level: 0 (shut) .. 1 (widest)
   *   tilt: -1 (rounded, "oo") .. +1 (wide, "ee") — shapes the mouth
   *
   * Call it every frame while you are in charge; it lapses after 500 ms of
   * silence, at which point audio analysis takes back over. The value still
   * goes through the spring, so it is smoothed exactly like audio input.
   */
  drive(level, tilt = 0) {
    this._extTarget = clamp(level, 0, 1);
    this._extTilt = clamp(tilt, -1, 1);
    this._extAt = performance.now();
    return this;
  }

  /** Hand control back to audio analysis immediately. */
  releaseDrive() {
    this._extTarget = null;
    return this;
  }

  /** Force a blink right now (handy when the avatar starts speaking). */
  blinkNow() {
    this._blink.phase = 'closing';
    this._blink.t = performance.now();
    return this;
  }

  _render(level, now) {
    const o = this.opt;
    const L = o.levels;

    /* --- mouth: cross-fade between the two nearest frames ---------------- */
    const keys = FRAME_ORDER.filter((k) => this.layers[k]);
    let idx = 0;
    while (idx < L.length - 2 && level > L[idx + 1]) idx++;
    const span = Math.max(L[idx + 1] - L[idx], 1e-6);
    let t = clamp((level - L[idx]) / span, 0, 1);
    if (!o.crossfade) t = t > 0.5 ? 1 : 0;     // hard-swap mode

    /* Mouth SHAPE: a small stretch about the mouth's own centre. Because the
       overlay layers are transparent everywhere except the mouth, transforming
       them moves only the mouth — the head underneath does not budge. */
    const m = o.mouth;
    const tilt = this.tilt || 0;
    const msx = 1 + tilt * m.widthDrive * level - (tilt < 0 ? tilt * m.roundDrive * level : 0);
    const msy = 1 - tilt * m.widthDrive * 0.5 * level;
    const originX = m.cx == null ? 50 : (m.cx / this.natural.w) * 100;
    const originY = m.cy == null ? 50 : (m.cy / this.natural.h) * 100;
    const mouthTf = `scale(${msx.toFixed(4)}, ${msy.toFixed(4)})`;

    keys.forEach((key, i) => {
      const el = this.layers[key];
      let a = 0;
      if (i === 0) a = 1;                       // bottom layer always opaque
      else if (i === idx + 1) a = t;
      else if (i <= idx) a = 1;
      el.style.opacity = String(a);
      if (i > 0 && (m.widthDrive || m.roundDrive)) {
        el.style.transformOrigin = `${originX}% ${originY}%`;
        el.style.transform = mouthTf;
      }
    });

    /* --- blink ------------------------------------------------------------ */
    const bAmt = this._blink.amount;
    if (this.blinkLayers) {
      const n = this.blinkLayers.length;
      // closure 0 -> no lid; 1 -> last frame. Nearest step, one at a time.
      const idxB = bAmt <= 0.001 ? -1 : clamp(Math.ceil(bAmt * n) - 1, 0, n - 1);
      if (idxB !== this._lastBlinkIdx) {
        if (this._lastBlinkIdx >= 0) this.blinkLayers[this._lastBlinkIdx].style.opacity = '0';
        if (idxB >= 0) this.blinkLayers[idxB].style.opacity = '1';
        this._lastBlinkIdx = idxB;
      }
    } else if (this.blinkLayer) {
      this.blinkLayer.style.opacity = String(bAmt > 0.5 ? 1 : 0);   // real photo: snap
    } else {
      const hidden = ((1 - bAmt) * 100).toFixed(2);
      const n = this.natural;
      ['left', 'right'].forEach((side, i) => {
        const r = this.opt.eyes[side];
        const { lid, lash } = this.lids[i];
        lid.style.clipPath = `inset(0 0 ${hidden}% 0)`;
        lash.style.opacity = bAmt > 0.02 ? String(Math.min(1, bAmt * 1.6)) : '0';
        // the lash rides the lid's leading edge
        lash.style.top = `${((r.y + bAmt * r.h * (this.opt.eyes.lashAt ?? 1)) / n.h) * 100}%`;
      });
    }

    /* --- idle motion: this is what makes it read as video ---------------- */
    const t0 = (now - this._t0);
    let tx = 0, ty = 0, rot = 0, sx = 1, sy = 1;
    if (o.idle.enabled) {
      const a = o.idle.amount;
      tx = (Math.sin(t0 * 0.00037) * 1.5 + Math.sin(t0 * 0.00091 + 1.3) * 0.7) * a;
      ty = (Math.sin(t0 * 0.00053 + 0.6) * 1.1 + Math.sin(t0 * 0.00131) * 0.45) * a;
      rot = (Math.sin(t0 * 0.00029 + 2.1) * 0.35 + Math.sin(t0 * 0.00083) * 0.15) * a;
      if (o.idle.breathe) {
        const br = Math.sin(t0 * 0.0009);
        sx = 1 + br * 0.0022 * a;
        sy = 1 + br * 0.0030 * a;
      }
    }
    // talking adds a small jaw drop + vertical stretch, and a nod on stress
    ty += level * o.jaw.drop + clamp(this.stress || 0, 0, 1) * o.jaw.nod;
    sy += level * o.jaw.squash;

    this.stage.style.transform =
      `translate3d(${tx.toFixed(2)}px, ${ty.toFixed(2)}px, 0) rotate(${rot.toFixed(3)}deg) scale(${sx.toFixed(4)}, ${sy.toFixed(4)})`;
  }

  /* ---------------------------------------------------------------------
   * 4. RUNTIME TUNING (used by the calibration panel, and safe in production)
   * ------------------------------------------------------------------- */
  set(partial) {
    this.opt = merge(this.opt, partial);
    if (partial.eyes) this._applyEyes();
    return this;
  }

  /**
   * Position the two synthetic eyelids.
   *
   * The lid is a box the size of the eye rectangle. Its background is the
   * avatar photo itself, scaled so it lines up 1:1 with the displayed avatar,
   * then shifted UP by `donorOffsetY` px so the lid is painted with the skin
   * that sits just above the eye. That is why the lid always matches skin
   * tone and lighting for free.
   *
   * CSS percentage background-position means:
   *     offset_px = P% * (elementSize - imageSize)
   * so to put image pixel `x` at the element's left edge we need
   *     P = x / (imageW - elementW)
   */
  _applyEyes() {
    if (!this.lids.length) return;
    const { eyes } = this.opt;
    const n = this.natural;
    ['left', 'right'].forEach((side, i) => {
      const r = eyes[side];
      const { lid, lash } = this.lids[i];

      // donorScaleY stretches the borrowed skin vertically, which is what you
      // need when there is only a thin band of clean skin between brow and eye.
      const sy = eyes.donorScaleY || 1;
      const outer = eyes.maskOuter, inner = eyes.maskInner;
      // ellipse radii = outer, expressed as a share of the box half-size, with
      // the opaque core at inner/outer along the gradient ray
      const mask = `radial-gradient(ellipse ${(outer * 50).toFixed(1)}% ${(outer * 50).toFixed(1)}%`
        + ` at 50% ${(eyes.maskCy * 100).toFixed(0)}%, #000 ${((inner / outer) * 100).toFixed(1)}%, transparent 100%)`;

      Object.assign(lid.style, {
        left: pct(r.x, n.w),
        top: pct(r.y, n.h),
        width: pct(r.w, n.w),
        height: pct(r.h, n.h),
        maskImage: mask,
        webkitMaskImage: mask,
        backgroundSize: `${(n.w / r.w) * 100}% ${(n.h / r.h) * 100 * sy}%`,
        backgroundPosition:
          `${(r.x / (n.w - r.w)) * 100}% ${((r.y - eyes.donorOffsetY) * sy / (n.h * sy - r.h)) * 100}%`,
      });

      // a hairline that fades out at both ends, so it reads as lashes and not
      // as a drawn rectangle
      const lashGrad = `linear-gradient(90deg, transparent 0%, ${eyes.lash} 22%, ${eyes.lash} 78%, transparent 100%)`;
      Object.assign(lash.style, {
        left: pct(r.x + r.w * 0.05, n.w),
        width: pct(r.w * 0.90, n.w),
        height: `${eyes.lashPx}px`,
        background: lashGrad,
        filter: 'blur(0.4px)',
        top: pct(r.y, n.h),
      });
    });
  }
}

/* ---------- tiny utils --------------------------------------------------- */
function pct(v, total) { return `${(v / total) * 100}%`; }
function easeIn(x) { return x * x; }
function easeOut(x) { return 1 - (1 - x) * (1 - x); }

export default TalkingAvatar;
